-- conv3x3_3chan_32out_bn_relu_time_mux.vhd
-- Resource-shared (time-multiplexed) COMPLETE 32-output ONE-WINDOW
-- scheduler for FOLDED Conv-BN-ReLU, extending
-- conv3x3_3chan_4out_bn_relu_time_mux.vhd's verified 4-kernel pattern to
-- ALL 32 first-layer output channels (the complete first Conv2d layer).
--
-- This is NOT a full streaming convolution engine and NOT full U-Net
-- inference. It computes ALL THIRTY-TWO first-layer folded Conv-BN-ReLU
-- output values (kernels 0-31 of enc1.block.0.weight, BatchNorm folded,
-- INT8 quantized, Q.16 fixed-point) for a SINGLE, already-captured
-- 3-channel 3x3 patch, by reusing:
--   (a) ONE conv3x3_dot_time_mux instance (existing, UNMODIFIED)
--       sequentially across the 96 (kernel, channel) combinations needed
--       (32 kernels x 3 input channels), instead of instantiating 96
--       parallel dot-product units, AND
--   (b) ONE Q.16 fixed-point multiply-add-ReLU unit, reused once per
--       kernel (not once per output, and not 32 in parallel), to apply
--       that kernel's own SCALE_FX/BIAS_FX and ReLU.
--
-- This completes the scale-up described in
-- hardware/vhdl_conv3x3/resource_shared_first_layer_conv_bn_relu_plan.md:
-- the SAME FSM structure and the SAME two shared compute resources as the
-- verified 4-kernel prototype (conv3x3_3chan_4out_bn_relu_time_mux.vhd,
-- preserved unmodified), just with NUM_KERNELS widened from 4 to 32 via
-- the new first_layer_32out_bn_relu_resource_shared_pkg -- no change to
-- the FSM logic itself was needed, since every loop bound in the FSM
-- (step range, kernel_idx range, y_regs array size, the "last kernel"
-- termination check) was already expressed in terms of the package's
-- NUM_KERNELS constant, not a hardcoded "4".
--
-- ---- Scheduling order ----------------------------------------------------
-- step = kernel_idx * 3 + channel_idx, for step = 0 .. 95 (32 kernels x 3
-- channels). After the third channel of each kernel (channel_idx = 2),
-- that kernel's three per-channel raw dot-product results are summed
-- (raw_sum, exact INT32), then passed through a TWO-STAGE registered
-- Q.16 fixed-point BN+ReLU sequence -- the SAME two-stage structure
-- already verified to close 100 MHz timing in
-- stream_conv3x3_3chan_kernel0_bn_relu_pipelined.vhd (Stage 1: register
-- product_fx = raw_sum * SCALE_FX; Stage 2: compute biased_fx =
-- product_fx + BIAS_FX, apply ReLU, register final y(kernel_idx)) --
-- before the scheduler advances to the next kernel.
--
-- ---- Interface -----------------------------------------------------------
-- Start/done handshake, one shot per patch (identical contract to
-- conv3x3_3chan_4out_bn_relu_time_mux.vhd):
--   - While idle, asserting `start` for one cycle begins scheduling all 96
--     dot operations (plus 32 BN+ReLU applications) against the currently
--     -presented 3x3x3 patch. The patch must remain stable for the entire run.
--   - `done` pulses for exactly one cycle when y0..y31 are all valid.
--   - `start` is ignored while busy.
--
-- ---- Weight/constant source ---------------------------------------------
-- Kernels 0-31's folded INT8 weights and Q.16 SCALE_FX/BIAS_FX constants
-- come from hardware/vhdl_conv3x3/first_layer_32out_bn_relu_resource_shared_pkg.vhd
-- (generated by scripts/generate_resource_shared_32out_bn_relu_vectors.py
-- --num-kernels 32, an existing script that required NO changes to scale
-- from 4 to 32 kernels). Weights are not exposed as ports; this module
-- hardwires all 32 kernels internally, matching the existing time-mux
-- convention.
--
-- ---- Cycle count -----------------------------------------------------
-- conv3x3_dot_time_mux takes 10 clock cycles per dot product, plus one
-- registration-gap cycle before each dispatch becomes visible. Each
-- kernel additionally costs 2 cycles for the BN+ReLU stage. This module's
-- own testbench MEASURES the actual total cycle count directly rather
-- than asserting a precomputed exact figure (same convention as every
-- other time-mux testbench here).
--
-- ---- Scope ----------------------------------------------------------------
-- This module computes ONE 3-channel 3x3 spatial window's 32 FOLDED
-- Conv-BN-ReLU output values -- the COMPLETE first Conv2d layer's output
-- channels for that one window. It does NOT slide a window across an
-- image, does NOT stream pixels, does NOT implement padding, and has NOT
-- been run on real FPGA hardware. It is a resource-sharing PROTOTYPE, not
-- a claim of measured speedup or a complete time-multiplexed accelerator,
-- and not a claim that the full U-Net or downstream layers are
-- implemented.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.first_layer_32out_bn_relu_resource_shared_pkg.all;

entity conv3x3_3chan_32out_bn_relu_time_mux is
    port (
        clk   : in  std_logic;
        rst   : in  std_logic;             -- synchronous reset, active high
        start : in  std_logic;             -- pulse (while idle) to begin scheduling

        -- One 3-channel 3x3 patch (row-major: p0 p1 p2 / p3 p4 p5 / p6 p7 p8),
        -- held stable for the duration of one run.
        c0_p0 : in signed(7 downto 0);  c0_p1 : in signed(7 downto 0);  c0_p2 : in signed(7 downto 0);
        c0_p3 : in signed(7 downto 0);  c0_p4 : in signed(7 downto 0);  c0_p5 : in signed(7 downto 0);
        c0_p6 : in signed(7 downto 0);  c0_p7 : in signed(7 downto 0);  c0_p8 : in signed(7 downto 0);

        c1_p0 : in signed(7 downto 0);  c1_p1 : in signed(7 downto 0);  c1_p2 : in signed(7 downto 0);
        c1_p3 : in signed(7 downto 0);  c1_p4 : in signed(7 downto 0);  c1_p5 : in signed(7 downto 0);
        c1_p6 : in signed(7 downto 0);  c1_p7 : in signed(7 downto 0);  c1_p8 : in signed(7 downto 0);

        c2_p0 : in signed(7 downto 0);  c2_p1 : in signed(7 downto 0);  c2_p2 : in signed(7 downto 0);
        c2_p3 : in signed(7 downto 0);  c2_p4 : in signed(7 downto 0);  c2_p5 : in signed(7 downto 0);
        c2_p6 : in signed(7 downto 0);  c2_p7 : in signed(7 downto 0);  c2_p8 : in signed(7 downto 0);

        busy : out std_logic;              -- '1' while scheduling is in progress
        done : out std_logic;              -- one-cycle pulse when y0..y31 are all valid
        y0 : out signed(47 downto 0);
        y1 : out signed(47 downto 0);
        y2 : out signed(47 downto 0);
        y3 : out signed(47 downto 0);
        y4 : out signed(47 downto 0);
        y5 : out signed(47 downto 0);
        y6 : out signed(47 downto 0);
        y7 : out signed(47 downto 0);
        y8 : out signed(47 downto 0);
        y9 : out signed(47 downto 0);
        y10 : out signed(47 downto 0);
        y11 : out signed(47 downto 0);
        y12 : out signed(47 downto 0);
        y13 : out signed(47 downto 0);
        y14 : out signed(47 downto 0);
        y15 : out signed(47 downto 0);
        y16 : out signed(47 downto 0);
        y17 : out signed(47 downto 0);
        y18 : out signed(47 downto 0);
        y19 : out signed(47 downto 0);
        y20 : out signed(47 downto 0);
        y21 : out signed(47 downto 0);
        y22 : out signed(47 downto 0);
        y23 : out signed(47 downto 0);
        y24 : out signed(47 downto 0);
        y25 : out signed(47 downto 0);
        y26 : out signed(47 downto 0);
        y27 : out signed(47 downto 0);
        y28 : out signed(47 downto 0);
        y29 : out signed(47 downto 0);
        y30 : out signed(47 downto 0);
        y31 : out signed(47 downto 0)
    );
end entity conv3x3_3chan_32out_bn_relu_time_mux;

architecture rtl of conv3x3_3chan_32out_bn_relu_time_mux is

    -- ----------------------------------------------------------------
    -- Convert the package's plain-integer kernel constants to
    -- signed(7 downto 0) arrays, once, at elaboration time (same helper
    -- pattern as every other design in this repo).
    -- ----------------------------------------------------------------
    type signed8_kernel_t is array (0 to 8) of signed(7 downto 0);

    function to_signed_kernel(k : int8_kernel_t) return signed8_kernel_t is
        variable r : signed8_kernel_t;
    begin
        for i in 0 to 8 loop
            r(i) := to_signed(k(i), 8);
        end loop;
        return r;
    end function to_signed_kernel;

    -- ----------------------------------------------------------------
    -- Per-channel pixel windows, packed into arrays for the mux below.
    -- ----------------------------------------------------------------
    signal ch0_arr, ch1_arr, ch2_arr : signed8_kernel_t;

    -- ----------------------------------------------------------------
    -- Scheduler FSM
    -- ----------------------------------------------------------------
    type state_t is (S_IDLE, S_RUN, S_BN1, S_BN2);
    signal state : state_t := S_IDLE;

    signal step        : integer range 0 to NUM_KERNELS * 3 - 1 := 0;
    signal channel_idx  : integer range 0 to 2 := 0;   -- step mod 3
    signal kernel_idx   : integer range 0 to NUM_KERNELS - 1 := 0;   -- step / 3

    signal partial_sum : signed(31 downto 0) := (others => '0');

    -- ---- Resource-shared Q.16 fixed-point BN+ReLU unit (ONE instance,
    -- reused once per kernel, two registered stages -- same structure
    -- verified in stream_conv3x3_3chan_kernel0_bn_relu_pipelined.vhd) ----
    signal raw_sum_r     : signed(31 downto 0) := (others => '0');
    signal bn_kernel_idx : integer range 0 to NUM_KERNELS - 1 := 0;  -- latched kernel_idx for BN stages
    signal product_fx_r  : signed(47 downto 0) := (others => '0');
    signal biased_fx_comb : signed(47 downto 0);

    type y_arr_t is array (0 to NUM_KERNELS - 1) of signed(47 downto 0);
    signal y_regs : y_arr_t := (others => (others => '0'));

    signal done_r : std_logic := '0';

    -- ----------------------------------------------------------------
    -- Single shared conv3x3_dot_time_mux instance and its interconnect.
    -- ----------------------------------------------------------------
    signal dot_start : std_logic := '0';
    signal dot_busy  : std_logic;
    signal dot_done  : std_logic;
    signal dot_y     : signed(31 downto 0);

    signal dot_p_arr : signed8_kernel_t;
    signal dot_w_arr : signed8_kernel_t;

    signal dot_p0, dot_p1, dot_p2, dot_p3, dot_p4, dot_p5, dot_p6, dot_p7, dot_p8 : signed(7 downto 0);
    signal dot_w0, dot_w1, dot_w2, dot_w3, dot_w4, dot_w5, dot_w6, dot_w7, dot_w8 : signed(7 downto 0);

    constant ZERO32 : signed(31 downto 0) := (others => '0');

begin

    -- ================================================================
    -- Pack input ports into arrays and derive step -> (kernel, channel).
    -- ================================================================
    ch0_arr(0) <= c0_p0; ch0_arr(1) <= c0_p1; ch0_arr(2) <= c0_p2;
    ch0_arr(3) <= c0_p3; ch0_arr(4) <= c0_p4; ch0_arr(5) <= c0_p5;
    ch0_arr(6) <= c0_p6; ch0_arr(7) <= c0_p7; ch0_arr(8) <= c0_p8;

    ch1_arr(0) <= c1_p0; ch1_arr(1) <= c1_p1; ch1_arr(2) <= c1_p2;
    ch1_arr(3) <= c1_p3; ch1_arr(4) <= c1_p4; ch1_arr(5) <= c1_p5;
    ch1_arr(6) <= c1_p6; ch1_arr(7) <= c1_p7; ch1_arr(8) <= c1_p8;

    ch2_arr(0) <= c2_p0; ch2_arr(1) <= c2_p1; ch2_arr(2) <= c2_p2;
    ch2_arr(3) <= c2_p3; ch2_arr(4) <= c2_p4; ch2_arr(5) <= c2_p5;
    ch2_arr(6) <= c2_p6; ch2_arr(7) <= c2_p7; ch2_arr(8) <= c2_p8;

    channel_idx <= step mod 3;
    kernel_idx  <= step / 3;

    -- ================================================================
    -- Combinational muxes: select this step's pixel channel and folded
    -- weight set (from the per-channel weight LUTs) for the shared
    -- conv3x3_dot_time_mux instance.
    -- ================================================================
    dot_p_arr <= ch0_arr when channel_idx = 0 else
                 ch1_arr when channel_idx = 1 else
                 ch2_arr;

    dot_p0 <= dot_p_arr(0); dot_p1 <= dot_p_arr(1); dot_p2 <= dot_p_arr(2);
    dot_p3 <= dot_p_arr(3); dot_p4 <= dot_p_arr(4); dot_p5 <= dot_p_arr(5);
    dot_p6 <= dot_p_arr(6); dot_p7 <= dot_p_arr(7); dot_p8 <= dot_p_arr(8);

    dot_w_arr <= to_signed_kernel(CH0_WEIGHT_LUT(kernel_idx)) when channel_idx = 0 else
                 to_signed_kernel(CH1_WEIGHT_LUT(kernel_idx)) when channel_idx = 1 else
                 to_signed_kernel(CH2_WEIGHT_LUT(kernel_idx));

    dot_w0 <= dot_w_arr(0); dot_w1 <= dot_w_arr(1); dot_w2 <= dot_w_arr(2);
    dot_w3 <= dot_w_arr(3); dot_w4 <= dot_w_arr(4); dot_w5 <= dot_w_arr(5);
    dot_w6 <= dot_w_arr(6); dot_w7 <= dot_w_arr(7); dot_w8 <= dot_w_arr(8);

    -- ================================================================
    -- The ONE reusable time-multiplexed dot-product lane, shared across
    -- all 96 (kernel, channel) operations.
    -- ================================================================
    dot_inst : entity work.conv3x3_dot_time_mux
        port map (
            clk   => clk,
            rst   => rst,
            start => dot_start,
            p0 => dot_p0, p1 => dot_p1, p2 => dot_p2,
            p3 => dot_p3, p4 => dot_p4, p5 => dot_p5,
            p6 => dot_p6, p7 => dot_p7, p8 => dot_p8,
            w0 => dot_w0, w1 => dot_w1, w2 => dot_w2,
            w3 => dot_w3, w4 => dot_w4, w5 => dot_w5,
            w6 => dot_w6, w7 => dot_w7, w8 => dot_w8,
            bias  => ZERO32,   -- per-channel bias always 0; folded kernel bias added in BN+ReLU stage
            busy  => dot_busy,
            done  => dot_done,
            y     => dot_y
        );

    -- ================================================================
    -- Resource-shared BN+ReLU Stage 2 combinational expression (registered
    -- into y_regs in the FSM below). product_fx_r is Q.16 (raw_sum_r is
    -- Q.0, SCALE_FX_LUT is Q.16 -- product is automatically Q.16, no
    -- shift); BIAS_FX_LUT is already Q.16, so the add needs no shift either.
    -- ================================================================
    biased_fx_comb <= product_fx_r + to_signed(BIAS_FX_LUT(bn_kernel_idx), 48);

    -- ================================================================
    -- Scheduler FSM: dispatches the 96 dot operations (S_RUN), then for
    -- each completed kernel (channel_idx = 2), runs the shared 2-stage
    -- BN+ReLU sequence (S_BN1: register product_fx; S_BN2: compute
    -- biased_fx, apply ReLU, register y_regs(kernel_idx)) before either
    -- dispatching the next kernel's first dot op or asserting done.
    -- ================================================================
    main : process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                state         <= S_IDLE;
                step          <= 0;
                partial_sum   <= (others => '0');
                raw_sum_r     <= (others => '0');
                bn_kernel_idx <= 0;
                product_fx_r  <= (others => '0');
                y_regs        <= (others => (others => '0'));
                done_r        <= '0';
                dot_start     <= '0';

            else
                done_r <= '0';

                case state is
                    when S_IDLE =>
                        dot_start <= '0';
                        if start = '1' then
                            step        <= 0;
                            partial_sum <= (others => '0');
                            dot_start   <= '1';
                            state       <= S_RUN;
                        end if;

                    when S_RUN =>
                        -- De-assert the one-cycle start pulse issued last edge.
                        if dot_start = '1' then
                            dot_start <= '0';
                        end if;

                        if dot_done = '1' then
                            if channel_idx = 2 then
                                -- Third channel of this kernel just completed:
                                -- latch the exact raw INT32 sum and enter the
                                -- shared BN+ReLU sequence for this kernel.
                                raw_sum_r     <= partial_sum + resize(dot_y, 32);
                                bn_kernel_idx <= kernel_idx;
                                partial_sum   <= (others => '0');
                                state         <= S_BN1;
                            else
                                partial_sum <= partial_sum + resize(dot_y, 32);
                                step        <= step + 1;
                                dot_start   <= '1';
                            end if;
                        end if;

                    when S_BN1 =>
                        -- Stage 1: register product_fx = raw_sum_r * SCALE_FX(kernel)
                        product_fx_r <= resize(raw_sum_r * to_signed(SCALE_FX_LUT(bn_kernel_idx), 18), 48);
                        state        <= S_BN2;

                    when S_BN2 =>
                        -- Stage 2: biased_fx = product_fx_r + BIAS_FX(kernel); ReLU;
                        -- register final y_regs(kernel), then decide next step.
                        if biased_fx_comb > 0 then
                            y_regs(bn_kernel_idx) <= biased_fx_comb;
                        else
                            y_regs(bn_kernel_idx) <= (others => '0');
                        end if;

                        if bn_kernel_idx = NUM_KERNELS - 1 then
                            done_r <= '1';
                            state  <= S_IDLE;
                        else
                            step      <= step + 1;
                            dot_start <= '1';
                            state     <= S_RUN;
                        end if;
                end case;
            end if;
        end if;
    end process main;

    busy <= '0' when state = S_IDLE else '1';
    done <= done_r;

    y0 <= y_regs(0);
    y1 <= y_regs(1);
    y2 <= y_regs(2);
    y3 <= y_regs(3);
    y4 <= y_regs(4);
    y5 <= y_regs(5);
    y6 <= y_regs(6);
    y7 <= y_regs(7);
    y8 <= y_regs(8);
    y9 <= y_regs(9);
    y10 <= y_regs(10);
    y11 <= y_regs(11);
    y12 <= y_regs(12);
    y13 <= y_regs(13);
    y14 <= y_regs(14);
    y15 <= y_regs(15);
    y16 <= y_regs(16);
    y17 <= y_regs(17);
    y18 <= y_regs(18);
    y19 <= y_regs(19);
    y20 <= y_regs(20);
    y21 <= y_regs(21);
    y22 <= y_regs(22);
    y23 <= y_regs(23);
    y24 <= y_regs(24);
    y25 <= y_regs(25);
    y26 <= y_regs(26);
    y27 <= y_regs(27);
    y28 <= y_regs(28);
    y29 <= y_regs(29);
    y30 <= y_regs(30);
    y31 <= y_regs(31);

end architecture rtl;
