-- first_conv_bn_relu_kernel3_real_tile_q20_pkg.vhd
-- VHDL-2008 package of INT8 folded weights, Q.20 fixed-point
-- SCALE_FX/BIAS_FX constants, and Q.20 fixed-point golden output
-- constants for the kernel-3 folded Conv-BN-ReLU design, evaluated on a
-- REAL UAVSAR-tile-derived patch (see real_tile_stimulus_pkg.vhd for the
-- pixel data), NOT the synthetic 5x5x3 toy patch.
--
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py --kernel-id 3
-- Source data : hardware/vhdl_conv3x3/real_tile_vectors/kernel3/kernel3_real_tile_bn_relu_fixed_point_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 3 only), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- BatchNorm folding ----------------------------------------------------
-- scale_bn[3] = 1.108772
-- b_folded[3] = -0.019410
-- (eps = 1e-05, torch.nn.BatchNorm2d default)
--
-- ---- Folded weight quantization ------------------------------------------
-- scale_w_folded[3] = 0.00168395
-- symmetric per-output-channel INT8, SAME convention as
-- scripts/analyze_first_layer_fixed_point_segmentation_impact.py.
--
-- ---- REAL-TILE activation quantization (NOT scale_x=1.0) -------------------
-- scale_x = 0.01808654, computed from the FULL normalized 256x256 tile
-- 'tile_16_42.tif', matching
-- analyze_first_layer_fixed_point_segmentation_impact.py's per-tile
-- convention exactly. This is the KEY difference from every toy-patch
-- kernel package in this repo, where scale_x = 1.0 was exact by
-- construction.
--
-- ---- Fixed-point format (Q.20, signed, 20 fractional bits) --------------
-- real_value ~= fixed_value / 2^20
-- SCALE_FX = round(scale_x * scale_w_folded[3] * 2^20)
-- BIAS_FX  = round(b_folded[3] * 2^20)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX (already Q.20, no shift);
--           biased_fx = product_fx + BIAS_FX (same format, no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weights (IDENTICAL to
-- first_conv_bn_relu_kernel3_pkg.vhd's, since weights do not depend on
-- input), the REAL-TILE fixed-point scale/bias constants, and the exact
-- Q.20 fixed-point expected outputs for a REAL 6x6 UAVSAR
-- patch, so a testbench can confirm the EXISTING, UNMODIFIED
-- stream_conv3x3_3chan_kernel3_bn_relu_pipelined datapath produces the SAME
-- fixed-point integer values as this Python script on REAL sensor-derived
-- data. It does NOT validate the other 31 output channels, does NOT
-- implement padding, and does NOT claim board-tested or measured
-- performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_conv_bn_relu_kernel3_real_tile_q20_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    -- IDENTICAL to first_conv_bn_relu_kernel3_pkg's K3_FOLDED_CH*_W --
    -- weights do not depend on the input patch.
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    constant K3_RT_FOLDED_CH0_W : int8_kernel_t := (-91, 61, -55, 75, -36, 67, -97, -62, 37);
    constant K3_RT_FOLDED_CH1_W : int8_kernel_t := (21, -37, 71, 83, -94, -70, 115, -43, -46);
    constant K3_RT_FOLDED_CH2_W : int8_kernel_t := (-127, -81, 25, -23, -106, -3, -86, -103, -68);

    -- Fixed-point Q.20 constants -- REAL scale_x baked in (differs
    -- from the toy-patch package's SCALE_FX, which assumed scale_x=1.0).
    constant FRAC_BITS : integer := 20;
    constant SCALE_FX  : integer := 32;   -- unsigned, Q.20
    constant BIAS_FX   : integer := -20353;   -- signed,   Q.20

    -- 16 Q.20 fixed-point expected outputs (row-major,
    -- output_index 0..15), EXACT integers -- this is what the
    -- VHDL testbench compares against.
    type fx_outputs_t is array (0 to 15) of integer;
    constant K3_RT_BN_RELU_EXPECTED_FX : fx_outputs_t := (
        169535, 1290143, 1591039, 859807,
        0, 1362175, 1357951, 1496863,
        0, 0, 1320767, 1455359,
        0, 0, 906527, 1290079
    );

end package first_conv_bn_relu_kernel3_real_tile_q20_pkg;
