-- first_layer_kernels0_to15_pkg.vhd
-- VHDL-2008 package of INT8 weight and INT32 golden-output constants for
-- first-layer U-Net convolution kernels 0-15.
--
-- Generated by: scripts/export_first_layer_multi_kernel_vhdl_vectors.py
-- Source data : hardware/vhdl_conv3x3/test_vectors/multi_kernel_first_layer/first_layer_kernels0_to15_int8.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight  (shape [32, 3, 3, 3])
-- Output chs : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
--
-- ---- Quantization -------------------------------------------------------
-- Scheme : symmetric per-tensor INT8 for weights, scale computed per kernel
--          scale_w = max(|w_float|) / 127
-- Input  : canonical 5x5x3 toy patch (ch0=1..25, ch1=2xch0, ch2=-1xch0),
--          scale_x = 1.0 (already integer-valued)
--
-- ---- Bias -----------------------------------------------------------------
-- The first Conv2d in this U-Net has NO direct bias (Conv2d -> BatchNorm;
-- BN params are NOT folded here). Therefore bias_int32 = 0 for every kernel.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies weight and golden-output constants so a testbench can
-- confirm the VHDL stream_conv3x3_3chan_cell integer datapath produces the
-- SAME INT32 values as the Python golden-vector script when driven with real
-- trained-model INT8 weights, across kernels 0-15.
-- It does NOT validate full quantized U-Net inference (BatchNorm is not applied),
-- and it does NOT cover the full set of 32 first-layer output channels.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_layer_kernels0_to15_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    -- 9 INT32 expected outputs per kernel, row-major (output_index 0..8)
    type int32_outputs_t is array (0 to 8) of integer;

    constant NUM_KERNELS : integer := 16;
    type kernel_id_t is array (0 to NUM_KERNELS - 1) of integer;
    constant KERNEL_IDS : kernel_id_t := (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);

    -- ==================================================================
    -- Kernel (output channel) 0
    --   scale_w = 0.00136063
    -- ==================================================================
    constant KERNEL0_CH0_W : int8_kernel_t := (110, 117, -38, 127, -28, 33, -66, 86, 124);
    constant KERNEL0_CH1_W : int8_kernel_t := (-103, 120, 24, 102, 20, 67, -19, 108, 20);
    constant KERNEL0_CH2_W : int8_kernel_t := (-68, 31, -72, -21, -59, 92, -112, -66, -44);
    constant KERNEL0_BIAS  : integer := 0;
    constant KERNEL0_EXPECTED : int32_outputs_t := (
        11287, 12749, 14211,
        18597, 20059, 21521,
        25907, 27369, 28831
    );

    -- ==================================================================
    -- Kernel (output channel) 1
    --   scale_w = 0.00150574
    -- ==================================================================
    constant KERNEL1_CH0_W : int8_kernel_t := (-72, 13, -127, 119, -101, 103, 28, -30, 86);
    constant KERNEL1_CH1_W : int8_kernel_t := (23, 102, 15, -39, 41, -32, 59, 124, 82);
    constant KERNEL1_CH2_W : int8_kernel_t := (-55, 68, 18, 65, -75, -127, -45, -90, 107);
    constant KERNEL1_BIAS  : integer := 0;
    constant KERNEL1_EXPECTED : int32_outputs_t := (
        9214, 10117, 11020,
        13729, 14632, 15535,
        18244, 19147, 20050
    );

    -- ==================================================================
    -- Kernel (output channel) 2
    --   scale_w = 0.00153375
    -- ==================================================================
    constant KERNEL2_CH0_W : int8_kernel_t := (36, 52, 39, -1, 99, -91, 10, -85, 37);
    constant KERNEL2_CH1_W : int8_kernel_t := (-41, 40, -25, 106, -72, -74, -73, 114, 43);
    constant KERNEL2_CH2_W : int8_kernel_t := (118, -106, -127, -99, -86, 46, 44, 102, -68);
    constant KERNEL2_BIAS  : integer := 0;
    constant KERNEL2_EXPECTED : int32_outputs_t := (
        1522, 1830, 2138,
        3062, 3370, 3678,
        4602, 4910, 5218
    );

    -- ==================================================================
    -- Kernel (output channel) 3
    --   scale_w = 0.00151875
    -- ==================================================================
    constant KERNEL3_CH0_W : int8_kernel_t := (-91, 61, -55, 75, -36, 67, -97, -62, 37);
    constant KERNEL3_CH1_W : int8_kernel_t := (21, -37, 71, 83, -94, -70, 115, -43, -46);
    constant KERNEL3_CH2_W : int8_kernel_t := (-127, -81, 25, -23, -106, -3, -86, -103, -68);
    constant KERNEL3_BIAS  : integer := 0;
    constant KERNEL3_EXPECTED : int32_outputs_t := (
        2636, 3107, 3578,
        4991, 5462, 5933,
        7346, 7817, 8288
    );

    -- ==================================================================
    -- Kernel (output channel) 4
    --   scale_w = 0.00155379
    -- ==================================================================
    constant KERNEL4_CH0_W : int8_kernel_t := (-99, -73, 127, 23, 45, -113, -79, -38, 26);
    constant KERNEL4_CH1_W : int8_kernel_t := (-108, -54, -78, -6, -46, -13, -85, -89, -73);
    constant KERNEL4_CH2_W : int8_kernel_t := (-35, -94, 106, -25, 113, 41, -104, 87, -28);
    constant KERNEL4_BIAS  : integer := 0;
    constant KERNEL4_EXPECTED : int32_outputs_t := (
        -9630, -10976, -12322,
        -16360, -17706, -19052,
        -23090, -24436, -25782
    );

    -- ==================================================================
    -- Kernel (output channel) 5
    --   scale_w = 0.00149192
    -- ==================================================================
    constant KERNEL5_CH0_W : int8_kernel_t := (-49, -107, -127, 35, -31, 50, -108, 94, -96);
    constant KERNEL5_CH1_W : int8_kernel_t := (-20, 29, 69, 105, 117, -101, 33, -56, -14);
    constant KERNEL5_CH2_W : int8_kernel_t := (-94, 120, -91, 69, 45, 44, -70, 117, 29);
    constant KERNEL5_BIAS  : integer := 0;
    constant KERNEL5_EXPECTED : int32_outputs_t := (
        -2734, -2918, -3102,
        -3654, -3838, -4022,
        -4574, -4758, -4942
    );

    -- ==================================================================
    -- Kernel (output channel) 6
    --   scale_w = 0.00140468
    -- ==================================================================
    constant KERNEL6_CH0_W : int8_kernel_t := (18, -123, 56, -18, -61, 118, 32, -72, -65);
    constant KERNEL6_CH1_W : int8_kernel_t := (-8, 72, -40, -78, -50, -106, 49, 108, -127);
    constant KERNEL6_CH2_W : int8_kernel_t := (34, 70, 26, -43, 76, 75, 56, -19, -29);
    constant KERNEL6_BIAS  : integer := 0;
    constant KERNEL6_EXPECTED : int32_outputs_t := (
        -5077, -5798, -6519,
        -8682, -9403, -10124,
        -12287, -13008, -13729
    );

    -- ==================================================================
    -- Kernel (output channel) 7
    --   scale_w = 0.00148245
    -- ==================================================================
    constant KERNEL7_CH0_W : int8_kernel_t := (16, -21, -37, 86, 114, -9, -26, 3, -5);
    constant KERNEL7_CH1_W : int8_kernel_t := (32, 37, -117, -46, 110, 52, -5, -78, -78);
    constant KERNEL7_CH2_W : int8_kernel_t := (-115, -42, 44, 85, 61, -113, -76, -21, 127);
    constant KERNEL7_BIAS  : integer := 0;
    constant KERNEL7_EXPECTED : int32_outputs_t := (
        -2419, -2434, -2449,
        -2494, -2509, -2524,
        -2569, -2584, -2599
    );

    -- ==================================================================
    -- Kernel (output channel) 8
    --   scale_w = 0.00148884
    -- ==================================================================
    constant KERNEL8_CH0_W : int8_kernel_t := (21, -29, 58, -47, -82, 97, -56, -24, -123);
    constant KERNEL8_CH1_W : int8_kernel_t := (89, 101, 51, -88, -127, -102, 99, 65, 113);
    constant KERNEL8_CH2_W : int8_kernel_t := (73, 41, 7, -93, -108, -115, 56, -60, -19);
    constant KERNEL8_BIAS  : integer := 0;
    constant KERNEL8_EXPECTED : int32_outputs_t := (
        3061, 3496, 3931,
        5236, 5671, 6106,
        7411, 7846, 8281
    );

    -- ==================================================================
    -- Kernel (output channel) 9
    --   scale_w = 0.00145723
    -- ==================================================================
    constant KERNEL9_CH0_W : int8_kernel_t := (-77, -27, -96, -85, 46, -38, 83, -42, -92);
    constant KERNEL9_CH1_W : int8_kernel_t := (-18, -60, -38, -119, 81, -83, 72, 64, 101);
    constant KERNEL9_CH2_W : int8_kernel_t := (-98, 96, -62, 51, 127, -15, 4, -27, -104);
    constant KERNEL9_BIAS  : integer := 0;
    constant KERNEL9_EXPECTED : int32_outputs_t := (
        2571, 2271, 1971,
        1071, 771, 471,
        -429, -729, -1029
    );

    -- ==================================================================
    -- Kernel (output channel) 10
    --   scale_w = 0.00148124
    -- ==================================================================
    constant KERNEL10_CH0_W : int8_kernel_t := (67, -124, 82, 100, 127, -28, -104, 32, 74);
    constant KERNEL10_CH1_W : int8_kernel_t := (-126, -24, -77, -11, -60, -49, -40, -122, 109);
    constant KERNEL10_CH2_W : int8_kernel_t := (113, -16, -15, -53, -112, -126, 49, -72, -83);
    constant KERNEL10_BIAS  : integer := 0;
    constant KERNEL10_EXPECTED : int32_outputs_t := (
        1470, 1211, 952,
        175, -84, -343,
        -1120, -1379, -1638
    );

    -- ==================================================================
    -- Kernel (output channel) 11
    --   scale_w = 0.00148546
    -- ==================================================================
    constant KERNEL11_CH0_W : int8_kernel_t := (-15, -47, -45, 0, -32, -48, -65, -109, 103);
    constant KERNEL11_CH1_W : int8_kernel_t := (-52, 34, -44, 11, 120, 60, -110, 52, 123);
    constant KERNEL11_CH2_W : int8_kernel_t := (32, 85, 127, -20, 25, -90, -27, 94, 64);
    constant KERNEL11_BIAS  : integer := 0;
    constant KERNEL11_EXPECTED : int32_outputs_t := (
        1449, 1289, 1129,
        649, 489, 329,
        -151, -311, -471
    );

    -- ==================================================================
    -- Kernel (output channel) 12
    --   scale_w = 0.00147002
    -- ==================================================================
    constant KERNEL12_CH0_W : int8_kernel_t := (-77, -112, -95, -127, -109, -38, 87, 15, -107);
    constant KERNEL12_CH1_W : int8_kernel_t := (-96, 66, -101, -13, 58, -62, -17, -16, -32);
    constant KERNEL12_CH2_W : int8_kernel_t := (-60, -118, -109, -68, 121, -68, -91, 23, 28);
    constant KERNEL12_BIAS  : integer := 0;
    constant KERNEL12_EXPECTED : int32_outputs_t := (
        -4040, -4687, -5334,
        -7275, -7922, -8569,
        -10510, -11157, -11804
    );

    -- ==================================================================
    -- Kernel (output channel) 13
    --   scale_w = 0.00152153
    -- ==================================================================
    constant KERNEL13_CH0_W : int8_kernel_t := (68, 95, 72, -127, 10, 77, -12, -74, 122);
    constant KERNEL13_CH1_W : int8_kernel_t := (-47, -72, -113, 5, 56, 29, 26, -95, -116);
    constant KERNEL13_CH2_W : int8_kernel_t := (3, 117, 75, -73, -15, -90, -60, 24, 71);
    constant KERNEL13_BIAS  : integer := 0;
    constant KERNEL13_EXPECTED : int32_outputs_t := (
        -3262, -3737, -4212,
        -5637, -6112, -6587,
        -8012, -8487, -8962
    );

    -- ==================================================================
    -- Kernel (output channel) 14
    --   scale_w = 0.00139875
    -- ==================================================================
    constant KERNEL14_CH0_W : int8_kernel_t := (116, -125, 95, -95, 53, 119, 4, 127, -114);
    constant KERNEL14_CH1_W : int8_kernel_t := (-54, 78, -32, -30, -60, 93, 66, 42, -77);
    constant KERNEL14_CH2_W : int8_kernel_t := (-111, 14, 39, -63, -39, 93, 11, 6, -32);
    constant KERNEL14_BIAS  : integer := 0;
    constant KERNEL14_EXPECTED : int32_outputs_t := (
        1844, 2158, 2472,
        3414, 3728, 4042,
        4984, 5298, 5612
    );

    -- ==================================================================
    -- Kernel (output channel) 15
    --   scale_w = 0.00145941
    -- ==================================================================
    constant KERNEL15_CH0_W : int8_kernel_t := (-120, -119, -62, -64, 42, -37, -53, 127, 45);
    constant KERNEL15_CH1_W : int8_kernel_t := (94, -62, -59, 45, -86, -86, -8, -50, -102);
    constant KERNEL15_CH2_W : int8_kernel_t := (79, 108, 23, -21, -123, -48, 30, 62, -16);
    constant KERNEL15_BIAS  : integer := 0;
    constant KERNEL15_EXPECTED : int32_outputs_t := (
        -5745, -6708, -7671,
        -10560, -11523, -12486,
        -15375, -16338, -17301
    );

end package first_layer_kernels0_to15_pkg;
