-- first_conv_bn_relu_kernel15_real_tile_q20_pkg.vhd
-- VHDL-2008 package of INT8 folded weights, Q.20 fixed-point
-- SCALE_FX/BIAS_FX constants, and Q.20 fixed-point golden output
-- constants for the kernel-15 folded Conv-BN-ReLU design, evaluated on a
-- REAL UAVSAR-tile-derived patch (see real_tile_stimulus_pkg.vhd for the
-- pixel data), NOT the synthetic 5x5x3 toy patch.
--
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py --kernel-id 15
-- Source data : hardware/vhdl_conv3x3/real_tile_vectors/kernel15/kernel15_real_tile_bn_relu_fixed_point_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 15 only), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- BatchNorm folding ----------------------------------------------------
-- scale_bn[15] = 1.577265
-- b_folded[15] = 0.012658
-- (eps = 1e-05, torch.nn.BatchNorm2d default)
--
-- ---- Folded weight quantization ------------------------------------------
-- scale_w_folded[15] = 0.00230187
-- symmetric per-output-channel INT8, SAME convention as
-- scripts/analyze_first_layer_fixed_point_segmentation_impact.py.
--
-- ---- REAL-TILE activation quantization (NOT scale_x=1.0) -------------------
-- scale_x = 0.01808654, computed from the FULL normalized 256x256 tile
-- 'tile_16_42.tif', matching
-- analyze_first_layer_fixed_point_segmentation_impact.py's per-tile
-- convention exactly. This is the KEY difference from every toy-patch
-- kernel package in this repo, where scale_x = 1.0 was exact by
-- construction.
--
-- ---- Fixed-point format (Q.20, signed, 20 fractional bits) --------------
-- real_value ~= fixed_value / 2^20
-- SCALE_FX = round(scale_x * scale_w_folded[15] * 2^20)
-- BIAS_FX  = round(b_folded[15] * 2^20)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX (already Q.20, no shift);
--           biased_fx = product_fx + BIAS_FX (same format, no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weights (IDENTICAL to
-- first_conv_bn_relu_kernel15_pkg.vhd's, since weights do not depend on
-- input), the REAL-TILE fixed-point scale/bias constants, and the exact
-- Q.20 fixed-point expected outputs for a REAL 6x6 UAVSAR
-- patch, so a testbench can confirm the EXISTING, UNMODIFIED
-- stream_conv3x3_3chan_kernel15_bn_relu_pipelined datapath produces the SAME
-- fixed-point integer values as this Python script on REAL sensor-derived
-- data. It does NOT validate the other 31 output channels, does NOT
-- implement padding, and does NOT claim board-tested or measured
-- performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_conv_bn_relu_kernel15_real_tile_q20_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    -- IDENTICAL to first_conv_bn_relu_kernel15_pkg's K15_FOLDED_CH*_W --
    -- weights do not depend on the input patch.
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    constant K15_RT_FOLDED_CH0_W : int8_kernel_t := (-120, -119, -62, -64, 42, -37, -53, 127, 45);
    constant K15_RT_FOLDED_CH1_W : int8_kernel_t := (94, -62, -59, 45, -86, -86, -8, -50, -102);
    constant K15_RT_FOLDED_CH2_W : int8_kernel_t := (79, 108, 23, -21, -123, -48, 30, 62, -16);

    -- Fixed-point Q.20 constants -- REAL scale_x baked in (differs
    -- from the toy-patch package's SCALE_FX, which assumed scale_x=1.0).
    constant FRAC_BITS : integer := 20;
    constant SCALE_FX  : integer := 44;   -- unsigned, Q.20
    constant BIAS_FX   : integer := 13272;   -- signed,   Q.20

    -- 16 Q.20 fixed-point expected outputs (row-major,
    -- output_index 0..15), EXACT integers -- this is what the
    -- VHDL testbench compares against.
    type fx_outputs_t is array (0 to 15) of integer;
    constant K15_RT_BN_RELU_EXPECTED_FX : fx_outputs_t := (
        1142268, 754100, 0, 0,
        549852, 905328, 744772, 343976,
        240356, 1275060, 652504, 538896,
        0, 0, 117860, 688716
    );

end package first_conv_bn_relu_kernel15_real_tile_q20_pkg;
