-- first_layer_32out_folded_bn_relu_real_tile_q20_pkg.vhd
-- Consolidated, all-32-kernel Q.20 real-tile folded Conv-BN-ReLU constants
-- for first_layer_32out_folded_arithmetic_core.vhd.
--
-- Generated by: scripts/generate_first_layer_32out_folded_arithmetic_core_vectors.py
--
-- ---- This is a MERGE, not a new derivation ---------------------------------
-- Every constant below is copied VERBATIM from two existing, independently
-- generated, already-verified VHDL package families -- no new value is
-- invented here:
--   - Raw INT8 weights: hardware/vhdl_conv3x3/first_layer_kernels0_to31_pkg.vhd
--     (weight source for the already-synthesized 740/740-DSP 32-output
--     direct-parallel design, first_layer_32out_dsp_200t_summary.md).
--   - Q.20 SCALE_FX/BIAS_FX: hardware/vhdl_conv3x3/
--     first_conv_bn_relu_kernel{0..31}_real_tile_q20_pkg.vhd (already
--     GHDL-verified, real_tile_all32_kernels_q20_verification_summary.md).
-- The generator script ASSERTS that the two families' raw INT8 weights are
-- bit-for-bit identical (expected: a strictly positive per-channel
-- BatchNorm scale cancels out of symmetric max-abs INT8 quantization) before
-- writing this file.
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (all 32 output channels), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- Fixed-point format (Q.20, signed, 20 fractional bits) ----------------
-- real_value ~= fixed_value / 2^20
-- Datapath per kernel k: raw_conv_int32 = sum over 27 taps of
--   (window[i] * weight[k][i]);
--   product_fx = raw_conv_int32 * SCALE_FX_LUT(k)  (Q.20, exact, no shift);
--   biased_fx  = product_fx + BIAS_FX_LUT(k)        (Q.20, exact, no shift);
--   y[k]       = biased_fx if biased_fx > 0 else 0  (ReLU).
-- SCALE_FX_LUT/BIAS_FX_LUT already bake in the REAL per-tile activation
-- scale (scale_x, from tile_16_42.tif), NOT scale_x=1.0.
--
-- ---- What this validates ----------------------------------------------------
-- This package supplies ALL 32 output channels' folded-datapath constants
-- in ONE file, for a NEW single-shot (not streamed) arithmetic-core
-- prototype that accepts one already-flattened 27-value window and
-- produces all 32 Conv-BN-ReLU outputs in a single pipelined pass. It does
-- NOT implement padding, does NOT implement image streaming/line buffers,
-- and does NOT claim board-tested or measured performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_layer_32out_folded_bn_relu_real_tile_q20_pkg is

    constant NUM_KERNELS : integer := 32;
    constant FRAC_BITS   : integer := 20;

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;
    type weight_lut_t  is array (0 to NUM_KERNELS - 1) of int8_kernel_t;
    type fx_lut_t       is array (0 to NUM_KERNELS - 1) of integer;

    -- Raw INT8 weights, one LUT per input channel, indexed by output kernel 0-31.
    -- IDENTICAL values to first_layer_kernels0_to31_pkg.vhd's KERNEL{k}_CH{c}_W.
    constant CH0_WEIGHT_LUT : weight_lut_t := (
        (110, 117, -38, 127, -28, 33, -66, 86, 124),
        (-72, 13, -127, 119, -101, 103, 28, -30, 86),
        (36, 52, 39, -1, 99, -91, 10, -85, 37),
        (-91, 61, -55, 75, -36, 67, -97, -62, 37),
        (-99, -73, 127, 23, 45, -113, -79, -38, 26),
        (-49, -107, -127, 35, -31, 50, -108, 94, -96),
        (18, -123, 56, -18, -61, 118, 32, -72, -65),
        (16, -21, -37, 86, 114, -9, -26, 3, -5),
        (21, -29, 58, -47, -82, 97, -56, -24, -123),
        (-77, -27, -96, -85, 46, -38, 83, -42, -92),
        (67, -124, 82, 100, 127, -28, -104, 32, 74),
        (-15, -47, -45, 0, -32, -48, -65, -109, 103),
        (-77, -112, -95, -127, -109, -38, 87, 15, -107),
        (68, 95, 72, -127, 10, 77, -12, -74, 122),
        (116, -125, 95, -95, 53, 119, 4, 127, -114),
        (-120, -119, -62, -64, 42, -37, -53, 127, 45),
        (-49, 73, -104, 85, -50, 0, -24, 16, -39),
        (-79, -11, 29, 46, -94, 48, -65, -109, -71),
        (69, -19, 116, 124, 41, 40, 23, -9, -10),
        (-100, -83, -110, 113, -125, 98, -6, -17, 80),
        (-79, -8, -28, 24, 122, 12, 76, 101, 104),
        (-66, -117, -109, -80, -127, -79, 46, 104, -43),
        (-64, -106, -16, -119, 87, 11, -73, 66, -127),
        (-3, -103, -73, -2, -76, -15, 53, -124, 45),
        (-14, -55, 99, -70, 101, 6, 22, 96, -20),
        (100, -25, -25, -109, -19, 92, 24, -68, 40),
        (-63, -108, 29, -105, 53, 39, -108, 39, -10),
        (-71, 85, -127, -117, 68, 66, 105, -101, -98),
        (1, 60, -95, 126, -65, -36, -30, -84, -127),
        (45, -68, -127, 64, 28, -66, 121, -55, 84),
        (-68, 28, 38, 58, 78, -32, 83, 108, -34),
        (-13, 25, -73, 33, -127, -95, -120, -43, -52)
    );

    constant CH1_WEIGHT_LUT : weight_lut_t := (
        (-103, 120, 24, 102, 20, 67, -19, 108, 20),
        (23, 102, 15, -39, 41, -32, 59, 124, 82),
        (-41, 40, -25, 106, -72, -74, -73, 114, 43),
        (21, -37, 71, 83, -94, -70, 115, -43, -46),
        (-108, -54, -78, -6, -46, -13, -85, -89, -73),
        (-20, 29, 69, 105, 117, -101, 33, -56, -14),
        (-8, 72, -40, -78, -50, -106, 49, 108, -127),
        (32, 37, -117, -46, 110, 52, -5, -78, -78),
        (89, 101, 51, -88, -127, -102, 99, 65, 113),
        (-18, -60, -38, -119, 81, -83, 72, 64, 101),
        (-126, -24, -77, -11, -60, -49, -40, -122, 109),
        (-52, 34, -44, 11, 120, 60, -110, 52, 123),
        (-96, 66, -101, -13, 58, -62, -17, -16, -32),
        (-47, -72, -113, 5, 56, 29, 26, -95, -116),
        (-54, 78, -32, -30, -60, 93, 66, 42, -77),
        (94, -62, -59, 45, -86, -86, -8, -50, -102),
        (93, -5, 98, 124, -66, -98, 105, 100, -100),
        (127, 112, 117, 77, 99, -18, -71, 67, -68),
        (-2, 48, 115, -34, -48, -31, -67, 17, 97),
        (-9, 86, 98, -112, 54, 28, 31, 23, 38),
        (-48, -30, 61, -37, 58, -32, -91, 50, 16),
        (-33, 74, -55, -59, 84, -107, 15, 116, 22),
        (-51, -25, -113, -85, -22, 101, 127, 85, -77),
        (-86, -60, 46, 99, -36, -54, -118, -70, -114),
        (-69, -21, 98, -92, 27, -127, 64, 42, 5),
        (-39, 112, -109, -41, -125, -50, 41, 118, 20),
        (61, 76, -127, 120, 110, 52, -113, -41, -34),
        (66, 112, 76, 19, 41, 123, -85, -59, 92),
        (73, 33, -126, -84, 127, 45, 55, -74, -58),
        (62, -107, 80, -117, -72, -22, -85, 124, -25),
        (104, 70, 127, -75, -66, -38, 14, 92, -75),
        (14, -28, 55, 112, 42, -56, -125, 41, -69)
    );

    constant CH2_WEIGHT_LUT : weight_lut_t := (
        (-68, 31, -72, -21, -59, 92, -112, -66, -44),
        (-55, 68, 18, 65, -75, -127, -45, -90, 107),
        (118, -106, -127, -99, -86, 46, 44, 102, -68),
        (-127, -81, 25, -23, -106, -3, -86, -103, -68),
        (-35, -94, 106, -25, 113, 41, -104, 87, -28),
        (-94, 120, -91, 69, 45, 44, -70, 117, 29),
        (34, 70, 26, -43, 76, 75, 56, -19, -29),
        (-115, -42, 44, 85, 61, -113, -76, -21, 127),
        (73, 41, 7, -93, -108, -115, 56, -60, -19),
        (-98, 96, -62, 51, 127, -15, 4, -27, -104),
        (113, -16, -15, -53, -112, -126, 49, -72, -83),
        (32, 85, 127, -20, 25, -90, -27, 94, 64),
        (-60, -118, -109, -68, 121, -68, -91, 23, 28),
        (3, 117, 75, -73, -15, -90, -60, 24, 71),
        (-111, 14, 39, -63, -39, 93, 11, 6, -32),
        (79, 108, 23, -21, -123, -48, 30, 62, -16),
        (-8, -127, -107, 29, 35, 26, -33, 122, 21),
        (-90, -45, 25, 67, -54, -79, 19, -77, -85),
        (97, 54, -104, -71, -30, -27, 0, -127, 35),
        (-61, -14, 127, 90, -3, -123, 7, -88, 107),
        (55, 127, 86, 120, 5, -114, -93, -83, -117),
        (36, -72, 3, 5, 34, 52, 108, -99, 2),
        (-85, 113, 43, 1, 15, -109, -47, 124, -33),
        (-30, 26, -125, 111, 82, -127, -62, 43, -22),
        (53, 2, 69, -100, -20, 52, 120, 62, -89),
        (127, 23, 73, 100, 103, -69, 119, 77, -59),
        (-33, 73, 45, 100, -49, 42, 49, -101, -123),
        (-91, -75, 92, 38, 38, -59, -3, 117, -79),
        (-16, -20, -85, 14, 17, -16, 25, -46, 38),
        (50, -113, 73, -40, -96, 19, 62, 113, -76),
        (74, -48, 87, -3, -122, -76, -97, 76, -90),
        (60, 80, 44, 115, 116, 20, -99, 107, -69)
    );

    -- Q.20 BatchNorm-fold scale/bias, one entry per output kernel 0-31.
    -- IDENTICAL values to first_conv_bn_relu_kernel{k}_real_tile_q20_pkg.vhd's
    -- SCALE_FX/BIAS_FX.
    constant SCALE_FX_LUT : fx_lut_t := (39, 63, 109, 32, 31, 84, 109, 103, 62, 51, 41, 64, 20, 84, 76, 44, 68, 64, 62, 83, 67, 51, 49, 28, 64, 48, 88, 74, 53, 72, 65, 65);
    constant BIAS_FX_LUT  : fx_lut_t := (-14969, -23250, -12572, -20353, 19398, 2953, 41960, 22770, -24508, -9810, 9601, -167, -2994, 42166, -1310, 13272, -25661, -46937, -9382, -14008, 6437, -2622, -3046, 11650, 15463, 20081, -12795, -34963, -3479, 11510, -16216, 9895);

end package first_layer_32out_folded_bn_relu_real_tile_q20_pkg;
