-- first_layer_16out_folded_bn_relu_real_tile_q20_pkg.vhd
-- 16-kernel (output channels 0-15 of 32) Q.20 real-tile folded
-- Conv-BN-ReLU constants for first_layer_16out_folded_arithmetic_core.vhd.
--
-- Generated by: scripts/generate_first_layer_16out_folded_arithmetic_core_pkg.py
--
-- ---- This is a SLICE of an already-verified merge, not a new derivation ---
-- Every constant below is copied VERBATIM from
-- hardware/vhdl_conv3x3/first_layer_32out_folded_bn_relu_real_tile_q20_pkg.vhd
-- (itself an already-GHDL-verified MERGE of two independent source
-- families -- see that file's header), keeping only output channels
-- 0-15. No new weight, scale, or bias value is invented here. The
-- generator script additionally cross-checks this slice, kernel by kernel,
-- against the existing, independently-generated
-- first_conv_bn_relu_kernel{0..15}_real_tile_q20_pkg.vhd files before
-- writing this file.
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (output channels 0-15 of 32),
--              folded with enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- Fixed-point format (Q.20, signed, 20 fractional bits) ----------------
-- real_value ~= fixed_value / 2^20
-- Datapath per kernel k: raw_conv_int32 = sum over 27 taps of
--   (window[i] * weight[k][i]);
--   product_fx = raw_conv_int32 * SCALE_FX_LUT(k)  (Q.20, exact, no shift);
--   biased_fx  = product_fx + BIAS_FX_LUT(k)        (Q.20, exact, no shift);
--   y[k]       = biased_fx if biased_fx > 0 else 0  (ReLU).
-- SCALE_FX_LUT/BIAS_FX_LUT already bake in the REAL per-tile activation
-- scale (scale_x, from tile_16_42.tif), NOT scale_x=1.0.
--
-- ---- What this validates ----------------------------------------------------
-- This package supplies output channels 0-15's folded-datapath
-- constants in ONE file, for a NEW single-shot (not streamed) arithmetic-core
-- artifact that accepts one already-flattened 27-value window and produces
-- 16 Conv-BN-ReLU outputs in a single pipelined pass. It does NOT
-- implement padding, does NOT implement image streaming/line buffers, and
-- does NOT claim board-tested or measured performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_layer_16out_folded_bn_relu_real_tile_q20_pkg is

    constant NUM_KERNELS : integer := 16;
    constant FRAC_BITS   : integer := 20;

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;
    type weight_lut_t  is array (0 to NUM_KERNELS - 1) of int8_kernel_t;
    type fx_lut_t       is array (0 to NUM_KERNELS - 1) of integer;

    -- Raw INT8 weights, one LUT per input channel, indexed by output kernel 0-15.
    -- IDENTICAL values to first_layer_32out_folded_bn_relu_real_tile_q20_pkg.vhd's
    -- CH{c}_WEIGHT_LUT(0..15).
    constant CH0_WEIGHT_LUT : weight_lut_t := (
        (110, 117, -38, 127, -28, 33, -66, 86, 124),
        (-72, 13, -127, 119, -101, 103, 28, -30, 86),
        (36, 52, 39, -1, 99, -91, 10, -85, 37),
        (-91, 61, -55, 75, -36, 67, -97, -62, 37),
        (-99, -73, 127, 23, 45, -113, -79, -38, 26),
        (-49, -107, -127, 35, -31, 50, -108, 94, -96),
        (18, -123, 56, -18, -61, 118, 32, -72, -65),
        (16, -21, -37, 86, 114, -9, -26, 3, -5),
        (21, -29, 58, -47, -82, 97, -56, -24, -123),
        (-77, -27, -96, -85, 46, -38, 83, -42, -92),
        (67, -124, 82, 100, 127, -28, -104, 32, 74),
        (-15, -47, -45, 0, -32, -48, -65, -109, 103),
        (-77, -112, -95, -127, -109, -38, 87, 15, -107),
        (68, 95, 72, -127, 10, 77, -12, -74, 122),
        (116, -125, 95, -95, 53, 119, 4, 127, -114),
        (-120, -119, -62, -64, 42, -37, -53, 127, 45)
    );

    constant CH1_WEIGHT_LUT : weight_lut_t := (
        (-103, 120, 24, 102, 20, 67, -19, 108, 20),
        (23, 102, 15, -39, 41, -32, 59, 124, 82),
        (-41, 40, -25, 106, -72, -74, -73, 114, 43),
        (21, -37, 71, 83, -94, -70, 115, -43, -46),
        (-108, -54, -78, -6, -46, -13, -85, -89, -73),
        (-20, 29, 69, 105, 117, -101, 33, -56, -14),
        (-8, 72, -40, -78, -50, -106, 49, 108, -127),
        (32, 37, -117, -46, 110, 52, -5, -78, -78),
        (89, 101, 51, -88, -127, -102, 99, 65, 113),
        (-18, -60, -38, -119, 81, -83, 72, 64, 101),
        (-126, -24, -77, -11, -60, -49, -40, -122, 109),
        (-52, 34, -44, 11, 120, 60, -110, 52, 123),
        (-96, 66, -101, -13, 58, -62, -17, -16, -32),
        (-47, -72, -113, 5, 56, 29, 26, -95, -116),
        (-54, 78, -32, -30, -60, 93, 66, 42, -77),
        (94, -62, -59, 45, -86, -86, -8, -50, -102)
    );

    constant CH2_WEIGHT_LUT : weight_lut_t := (
        (-68, 31, -72, -21, -59, 92, -112, -66, -44),
        (-55, 68, 18, 65, -75, -127, -45, -90, 107),
        (118, -106, -127, -99, -86, 46, 44, 102, -68),
        (-127, -81, 25, -23, -106, -3, -86, -103, -68),
        (-35, -94, 106, -25, 113, 41, -104, 87, -28),
        (-94, 120, -91, 69, 45, 44, -70, 117, 29),
        (34, 70, 26, -43, 76, 75, 56, -19, -29),
        (-115, -42, 44, 85, 61, -113, -76, -21, 127),
        (73, 41, 7, -93, -108, -115, 56, -60, -19),
        (-98, 96, -62, 51, 127, -15, 4, -27, -104),
        (113, -16, -15, -53, -112, -126, 49, -72, -83),
        (32, 85, 127, -20, 25, -90, -27, 94, 64),
        (-60, -118, -109, -68, 121, -68, -91, 23, 28),
        (3, 117, 75, -73, -15, -90, -60, 24, 71),
        (-111, 14, 39, -63, -39, 93, 11, 6, -32),
        (79, 108, 23, -21, -123, -48, 30, 62, -16)
    );

    -- Q.20 BatchNorm-fold scale/bias, one entry per output kernel 0-15.
    -- IDENTICAL values to first_layer_32out_folded_bn_relu_real_tile_q20_pkg.vhd's
    -- SCALE_FX_LUT/BIAS_FX_LUT(0..15).
    constant SCALE_FX_LUT : fx_lut_t := (39, 63, 109, 32, 31, 84, 109, 103, 62, 51, 41, 64, 20, 84, 76, 44);
    constant BIAS_FX_LUT  : fx_lut_t := (-14969, -23250, -12572, -20353, 19398, 2953, 41960, 22770, -24508, -9810, 9601, -167, -2994, 42166, -1310, 13272);

end package first_layer_16out_folded_bn_relu_real_tile_q20_pkg;
