-- first_conv_bn_relu_kernel0_relu_clamp_pkg.vhd
-- *** SYNTHETIC RELU CLAMP UNIT TEST -- NOT a real UAVSAR tile, NOT real model inference. ***
-- VHDL-2008 package of INT8 folded weights, Q.16 fixed-point
-- SCALE_FX/BIAS_FX constants, and Q.16 fixed-point golden output
-- constants for the kernel-0 folded Conv-BN-ReLU proof-of-concept.
--
-- Generated by: scripts/generate_bn_relu_fixed_point_vectors.py --kernel-id 0 --input-mode synthetic_relu_clamp
-- Source data : hardware/vhdl_conv3x3/test_vectors/conv_bn_relu_kernel0_relu_clamp/kernel0_relu_clamp_bn_relu_fixed_point_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 0 only), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- BatchNorm folding ----------------------------------------------------
-- scale_bn[0] = gamma[0] / sqrt(running_var[0] + eps) = 1.515678
-- b_folded[0] = beta[0] - running_mean[0] * scale_bn[0] = -0.014275
-- (eps = 1e-05, torch.nn.BatchNorm2d default)
--
-- ---- Folded weight quantization ------------------------------------------
-- scale_w_folded[0] = max(|w_folded[0]|) / 127 = 0.00206228
-- symmetric per-channel INT8, SAME convention as
-- scripts/analyze_first_conv_bn_relu_fidelity.py, applied to kernel 0 only.
--
-- ---- Fixed-point format (Q.16, signed, 16 fractional bits) --------------
-- real_value ~= fixed_value / 2^16
-- SCALE_FX = round(scale_x * scale_w_folded[0] * 2^16), scale_x = 1.0 exact
--            for this input patch (see generator script docstring)
-- BIAS_FX  = round(b_folded[0] * 2^16)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX (already Q.16, no shift);
--           biased_fx = product_fx + BIAS_FX (same format, no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weights, the fixed-point scale/bias
-- constants, and the exact Q.16 fixed-point expected outputs so a
-- testbench can confirm a kernel-0 folded Conv-BN-ReLU VHDL design produces
-- the SAME fixed-point integer values as this Python script for kernel 0 on
-- a SYNTHETIC all-zero unit-test input designed to force the ReLU clamp branch (NOT a real UAVSAR tile).
-- It does NOT validate the other 31 output
-- channels, does NOT implement padding, and does NOT claim board-tested
-- or measured performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_conv_bn_relu_kernel0_relu_clamp_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    -- FOLDED (BatchNorm-absorbed) INT8 weights, kernel 0
    constant K0_FOLDED_CH0_W : int8_kernel_t := (110, 117, -38, 127, -28, 33, -66, 86, 124);
    constant K0_FOLDED_CH1_W : int8_kernel_t := (-103, 120, 24, 102, 20, 67, -19, 108, 20);
    constant K0_FOLDED_CH2_W : int8_kernel_t := (-68, 31, -72, -21, -59, 92, -112, -66, -44);

    -- Fixed-point Q.16 constants
    constant FRAC_BITS : integer := 16;
    constant SCALE_FX  : integer := 135;   -- unsigned, Q.16
    constant BIAS_FX   : integer := -936;   -- signed,   Q.16

    -- 9 Q.16 fixed-point expected outputs (row-major, output_index 0..8),
    -- EXACT integers -- this is what the VHDL testbench compares against.
    type fx_outputs_t is array (0 to 8) of integer;
    constant K0_BN_RELU_EXPECTED_FX : fx_outputs_t := (
        0, 0, 0,
        0, 0, 0,
        0, 0, 0
    );

end package first_conv_bn_relu_kernel0_relu_clamp_pkg;
