-- first_layer_kernels0_to31_pkg.vhd
-- VHDL-2008 package of INT8 weight and INT32 golden-output constants for
-- first-layer U-Net convolution kernels 0-31.
--
-- Generated by: scripts/export_first_layer_multi_kernel_vhdl_vectors.py
-- Source data : hardware/vhdl_conv3x3/test_vectors/multi_kernel_first_layer/first_layer_kernels0_to31_int8.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight  (shape [32, 3, 3, 3])
-- Output chs : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
--
-- ---- Quantization -------------------------------------------------------
-- Scheme : symmetric per-tensor INT8 for weights, scale computed per kernel
--          scale_w = max(|w_float|) / 127
-- Input  : canonical 5x5x3 toy patch (ch0=1..25, ch1=2xch0, ch2=-1xch0),
--          scale_x = 1.0 (already integer-valued)
--
-- ---- Bias -----------------------------------------------------------------
-- The first Conv2d in this U-Net has NO direct bias (Conv2d -> BatchNorm;
-- BN params are NOT folded here). Therefore bias_int32 = 0 for every kernel.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies weight and golden-output constants so a testbench can
-- confirm the VHDL stream_conv3x3_3chan_cell integer datapath produces the
-- SAME INT32 values as the Python golden-vector script when driven with real
-- trained-model INT8 weights, across kernels 0-31.
-- It does NOT validate full quantized U-Net inference (BatchNorm is not applied),
-- and it does NOT cover the full set of 32 first-layer output channels.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_layer_kernels0_to31_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    -- 9 INT32 expected outputs per kernel, row-major (output_index 0..8)
    type int32_outputs_t is array (0 to 8) of integer;

    constant NUM_KERNELS : integer := 32;
    type kernel_id_t is array (0 to NUM_KERNELS - 1) of integer;
    constant KERNEL_IDS : kernel_id_t := (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31);

    -- ==================================================================
    -- Kernel (output channel) 0
    --   scale_w = 0.00136063
    -- ==================================================================
    constant KERNEL0_CH0_W : int8_kernel_t := (110, 117, -38, 127, -28, 33, -66, 86, 124);
    constant KERNEL0_CH1_W : int8_kernel_t := (-103, 120, 24, 102, 20, 67, -19, 108, 20);
    constant KERNEL0_CH2_W : int8_kernel_t := (-68, 31, -72, -21, -59, 92, -112, -66, -44);
    constant KERNEL0_BIAS  : integer := 0;
    constant KERNEL0_EXPECTED : int32_outputs_t := (
        11287, 12749, 14211,
        18597, 20059, 21521,
        25907, 27369, 28831
    );

    -- ==================================================================
    -- Kernel (output channel) 1
    --   scale_w = 0.00150574
    -- ==================================================================
    constant KERNEL1_CH0_W : int8_kernel_t := (-72, 13, -127, 119, -101, 103, 28, -30, 86);
    constant KERNEL1_CH1_W : int8_kernel_t := (23, 102, 15, -39, 41, -32, 59, 124, 82);
    constant KERNEL1_CH2_W : int8_kernel_t := (-55, 68, 18, 65, -75, -127, -45, -90, 107);
    constant KERNEL1_BIAS  : integer := 0;
    constant KERNEL1_EXPECTED : int32_outputs_t := (
        9214, 10117, 11020,
        13729, 14632, 15535,
        18244, 19147, 20050
    );

    -- ==================================================================
    -- Kernel (output channel) 2
    --   scale_w = 0.00153375
    -- ==================================================================
    constant KERNEL2_CH0_W : int8_kernel_t := (36, 52, 39, -1, 99, -91, 10, -85, 37);
    constant KERNEL2_CH1_W : int8_kernel_t := (-41, 40, -25, 106, -72, -74, -73, 114, 43);
    constant KERNEL2_CH2_W : int8_kernel_t := (118, -106, -127, -99, -86, 46, 44, 102, -68);
    constant KERNEL2_BIAS  : integer := 0;
    constant KERNEL2_EXPECTED : int32_outputs_t := (
        1522, 1830, 2138,
        3062, 3370, 3678,
        4602, 4910, 5218
    );

    -- ==================================================================
    -- Kernel (output channel) 3
    --   scale_w = 0.00151875
    -- ==================================================================
    constant KERNEL3_CH0_W : int8_kernel_t := (-91, 61, -55, 75, -36, 67, -97, -62, 37);
    constant KERNEL3_CH1_W : int8_kernel_t := (21, -37, 71, 83, -94, -70, 115, -43, -46);
    constant KERNEL3_CH2_W : int8_kernel_t := (-127, -81, 25, -23, -106, -3, -86, -103, -68);
    constant KERNEL3_BIAS  : integer := 0;
    constant KERNEL3_EXPECTED : int32_outputs_t := (
        2636, 3107, 3578,
        4991, 5462, 5933,
        7346, 7817, 8288
    );

    -- ==================================================================
    -- Kernel (output channel) 4
    --   scale_w = 0.00155379
    -- ==================================================================
    constant KERNEL4_CH0_W : int8_kernel_t := (-99, -73, 127, 23, 45, -113, -79, -38, 26);
    constant KERNEL4_CH1_W : int8_kernel_t := (-108, -54, -78, -6, -46, -13, -85, -89, -73);
    constant KERNEL4_CH2_W : int8_kernel_t := (-35, -94, 106, -25, 113, 41, -104, 87, -28);
    constant KERNEL4_BIAS  : integer := 0;
    constant KERNEL4_EXPECTED : int32_outputs_t := (
        -9630, -10976, -12322,
        -16360, -17706, -19052,
        -23090, -24436, -25782
    );

    -- ==================================================================
    -- Kernel (output channel) 5
    --   scale_w = 0.00149192
    -- ==================================================================
    constant KERNEL5_CH0_W : int8_kernel_t := (-49, -107, -127, 35, -31, 50, -108, 94, -96);
    constant KERNEL5_CH1_W : int8_kernel_t := (-20, 29, 69, 105, 117, -101, 33, -56, -14);
    constant KERNEL5_CH2_W : int8_kernel_t := (-94, 120, -91, 69, 45, 44, -70, 117, 29);
    constant KERNEL5_BIAS  : integer := 0;
    constant KERNEL5_EXPECTED : int32_outputs_t := (
        -2734, -2918, -3102,
        -3654, -3838, -4022,
        -4574, -4758, -4942
    );

    -- ==================================================================
    -- Kernel (output channel) 6
    --   scale_w = 0.00140468
    -- ==================================================================
    constant KERNEL6_CH0_W : int8_kernel_t := (18, -123, 56, -18, -61, 118, 32, -72, -65);
    constant KERNEL6_CH1_W : int8_kernel_t := (-8, 72, -40, -78, -50, -106, 49, 108, -127);
    constant KERNEL6_CH2_W : int8_kernel_t := (34, 70, 26, -43, 76, 75, 56, -19, -29);
    constant KERNEL6_BIAS  : integer := 0;
    constant KERNEL6_EXPECTED : int32_outputs_t := (
        -5077, -5798, -6519,
        -8682, -9403, -10124,
        -12287, -13008, -13729
    );

    -- ==================================================================
    -- Kernel (output channel) 7
    --   scale_w = 0.00148245
    -- ==================================================================
    constant KERNEL7_CH0_W : int8_kernel_t := (16, -21, -37, 86, 114, -9, -26, 3, -5);
    constant KERNEL7_CH1_W : int8_kernel_t := (32, 37, -117, -46, 110, 52, -5, -78, -78);
    constant KERNEL7_CH2_W : int8_kernel_t := (-115, -42, 44, 85, 61, -113, -76, -21, 127);
    constant KERNEL7_BIAS  : integer := 0;
    constant KERNEL7_EXPECTED : int32_outputs_t := (
        -2419, -2434, -2449,
        -2494, -2509, -2524,
        -2569, -2584, -2599
    );

    -- ==================================================================
    -- Kernel (output channel) 8
    --   scale_w = 0.00148884
    -- ==================================================================
    constant KERNEL8_CH0_W : int8_kernel_t := (21, -29, 58, -47, -82, 97, -56, -24, -123);
    constant KERNEL8_CH1_W : int8_kernel_t := (89, 101, 51, -88, -127, -102, 99, 65, 113);
    constant KERNEL8_CH2_W : int8_kernel_t := (73, 41, 7, -93, -108, -115, 56, -60, -19);
    constant KERNEL8_BIAS  : integer := 0;
    constant KERNEL8_EXPECTED : int32_outputs_t := (
        3061, 3496, 3931,
        5236, 5671, 6106,
        7411, 7846, 8281
    );

    -- ==================================================================
    -- Kernel (output channel) 9
    --   scale_w = 0.00145723
    -- ==================================================================
    constant KERNEL9_CH0_W : int8_kernel_t := (-77, -27, -96, -85, 46, -38, 83, -42, -92);
    constant KERNEL9_CH1_W : int8_kernel_t := (-18, -60, -38, -119, 81, -83, 72, 64, 101);
    constant KERNEL9_CH2_W : int8_kernel_t := (-98, 96, -62, 51, 127, -15, 4, -27, -104);
    constant KERNEL9_BIAS  : integer := 0;
    constant KERNEL9_EXPECTED : int32_outputs_t := (
        2571, 2271, 1971,
        1071, 771, 471,
        -429, -729, -1029
    );

    -- ==================================================================
    -- Kernel (output channel) 10
    --   scale_w = 0.00148124
    -- ==================================================================
    constant KERNEL10_CH0_W : int8_kernel_t := (67, -124, 82, 100, 127, -28, -104, 32, 74);
    constant KERNEL10_CH1_W : int8_kernel_t := (-126, -24, -77, -11, -60, -49, -40, -122, 109);
    constant KERNEL10_CH2_W : int8_kernel_t := (113, -16, -15, -53, -112, -126, 49, -72, -83);
    constant KERNEL10_BIAS  : integer := 0;
    constant KERNEL10_EXPECTED : int32_outputs_t := (
        1470, 1211, 952,
        175, -84, -343,
        -1120, -1379, -1638
    );

    -- ==================================================================
    -- Kernel (output channel) 11
    --   scale_w = 0.00148546
    -- ==================================================================
    constant KERNEL11_CH0_W : int8_kernel_t := (-15, -47, -45, 0, -32, -48, -65, -109, 103);
    constant KERNEL11_CH1_W : int8_kernel_t := (-52, 34, -44, 11, 120, 60, -110, 52, 123);
    constant KERNEL11_CH2_W : int8_kernel_t := (32, 85, 127, -20, 25, -90, -27, 94, 64);
    constant KERNEL11_BIAS  : integer := 0;
    constant KERNEL11_EXPECTED : int32_outputs_t := (
        1449, 1289, 1129,
        649, 489, 329,
        -151, -311, -471
    );

    -- ==================================================================
    -- Kernel (output channel) 12
    --   scale_w = 0.00147002
    -- ==================================================================
    constant KERNEL12_CH0_W : int8_kernel_t := (-77, -112, -95, -127, -109, -38, 87, 15, -107);
    constant KERNEL12_CH1_W : int8_kernel_t := (-96, 66, -101, -13, 58, -62, -17, -16, -32);
    constant KERNEL12_CH2_W : int8_kernel_t := (-60, -118, -109, -68, 121, -68, -91, 23, 28);
    constant KERNEL12_BIAS  : integer := 0;
    constant KERNEL12_EXPECTED : int32_outputs_t := (
        -4040, -4687, -5334,
        -7275, -7922, -8569,
        -10510, -11157, -11804
    );

    -- ==================================================================
    -- Kernel (output channel) 13
    --   scale_w = 0.00152153
    -- ==================================================================
    constant KERNEL13_CH0_W : int8_kernel_t := (68, 95, 72, -127, 10, 77, -12, -74, 122);
    constant KERNEL13_CH1_W : int8_kernel_t := (-47, -72, -113, 5, 56, 29, 26, -95, -116);
    constant KERNEL13_CH2_W : int8_kernel_t := (3, 117, 75, -73, -15, -90, -60, 24, 71);
    constant KERNEL13_BIAS  : integer := 0;
    constant KERNEL13_EXPECTED : int32_outputs_t := (
        -3262, -3737, -4212,
        -5637, -6112, -6587,
        -8012, -8487, -8962
    );

    -- ==================================================================
    -- Kernel (output channel) 14
    --   scale_w = 0.00139875
    -- ==================================================================
    constant KERNEL14_CH0_W : int8_kernel_t := (116, -125, 95, -95, 53, 119, 4, 127, -114);
    constant KERNEL14_CH1_W : int8_kernel_t := (-54, 78, -32, -30, -60, 93, 66, 42, -77);
    constant KERNEL14_CH2_W : int8_kernel_t := (-111, 14, 39, -63, -39, 93, 11, 6, -32);
    constant KERNEL14_BIAS  : integer := 0;
    constant KERNEL14_EXPECTED : int32_outputs_t := (
        1844, 2158, 2472,
        3414, 3728, 4042,
        4984, 5298, 5612
    );

    -- ==================================================================
    -- Kernel (output channel) 15
    --   scale_w = 0.00145941
    -- ==================================================================
    constant KERNEL15_CH0_W : int8_kernel_t := (-120, -119, -62, -64, 42, -37, -53, 127, 45);
    constant KERNEL15_CH1_W : int8_kernel_t := (94, -62, -59, 45, -86, -86, -8, -50, -102);
    constant KERNEL15_CH2_W : int8_kernel_t := (79, 108, 23, -21, -123, -48, 30, 62, -16);
    constant KERNEL15_BIAS  : integer := 0;
    constant KERNEL15_EXPECTED : int32_outputs_t := (
        -5745, -6708, -7671,
        -10560, -11523, -12486,
        -15375, -16338, -17301
    );

    -- ==================================================================
    -- Kernel (output channel) 16
    --   scale_w = 0.00147818
    -- ==================================================================
    constant KERNEL16_CH0_W : int8_kernel_t := (-49, 73, -104, 85, -50, 0, -24, 16, -39);
    constant KERNEL16_CH1_W : int8_kernel_t := (93, -5, 98, 124, -66, -98, 105, 100, -100);
    constant KERNEL16_CH2_W : int8_kernel_t := (-8, -127, -107, 29, 35, 26, -33, 122, 21);
    constant KERNEL16_BIAS  : integer := 0;
    constant KERNEL16_EXPECTED : int32_outputs_t := (
        -192, 260, 712,
        2068, 2520, 2972,
        4328, 4780, 5232
    );

    -- ==================================================================
    -- Kernel (output channel) 17
    --   scale_w = 0.00146416
    -- ==================================================================
    constant KERNEL17_CH0_W : int8_kernel_t := (-79, -11, 29, 46, -94, 48, -65, -109, -71);
    constant KERNEL17_CH1_W : int8_kernel_t := (127, 112, 117, 77, 99, -18, -71, 67, -68);
    constant KERNEL17_CH2_W : int8_kernel_t := (-90, -45, 25, 67, -54, -79, 19, -77, -85);
    constant KERNEL17_BIAS  : integer := 0;
    constant KERNEL17_EXPECTED : int32_outputs_t := (
        1279, 2176, 3073,
        5764, 6661, 7558,
        10249, 11146, 12043
    );

    -- ==================================================================
    -- Kernel (output channel) 18
    --   scale_w = 0.00148421
    -- ==================================================================
    constant KERNEL18_CH0_W : int8_kernel_t := (69, -19, 116, 124, 41, 40, 23, -9, -10);
    constant KERNEL18_CH1_W : int8_kernel_t := (-2, 48, 115, -34, -48, -31, -67, 17, 97);
    constant KERNEL18_CH2_W : int8_kernel_t := (97, 54, -104, -71, -30, -27, 0, -127, 35);
    constant KERNEL18_BIAS  : integer := 0;
    constant KERNEL18_EXPECTED : int32_outputs_t := (
        4531, 5269, 6007,
        8221, 8959, 9697,
        11911, 12649, 13387
    );

    -- ==================================================================
    -- Kernel (output channel) 19
    --   scale_w = 0.00145993
    -- ==================================================================
    constant KERNEL19_CH0_W : int8_kernel_t := (-100, -83, -110, 113, -125, 98, -6, -17, 80);
    constant KERNEL19_CH1_W : int8_kernel_t := (-9, 86, 98, -112, 54, 28, 31, 23, 38);
    constant KERNEL19_CH2_W : int8_kernel_t := (-61, -14, 127, 90, -3, -123, 7, -88, 107);
    constant KERNEL19_BIAS  : integer := 0;
    constant KERNEL19_EXPECTED : int32_outputs_t := (
        3518, 3800, 4082,
        4928, 5210, 5492,
        6338, 6620, 6902
    );

    -- ==================================================================
    -- Kernel (output channel) 20
    --   scale_w = 0.00148223
    -- ==================================================================
    constant KERNEL20_CH0_W : int8_kernel_t := (-79, -8, -28, 24, 122, 12, 76, 101, 104);
    constant KERNEL20_CH1_W : int8_kernel_t := (-48, -30, 61, -37, 58, -32, -91, 50, 16);
    constant KERNEL20_CH2_W : int8_kernel_t := (55, 127, 86, 120, 5, -114, -93, -83, -117);
    constant KERNEL20_BIAS  : integer := 0;
    constant KERNEL20_EXPECTED : int32_outputs_t := (
        7065, 7297, 7529,
        8225, 8457, 8689,
        9385, 9617, 9849
    );

    -- ==================================================================
    -- Kernel (output channel) 21
    --   scale_w = 0.00151396
    -- ==================================================================
    constant KERNEL21_CH0_W : int8_kernel_t := (-66, -117, -109, -80, -127, -79, 46, 104, -43);
    constant KERNEL21_CH1_W : int8_kernel_t := (-33, 74, -55, -59, 84, -107, 15, 116, 22);
    constant KERNEL21_CH2_W : int8_kernel_t := (36, -72, 3, 5, 34, 52, 108, -99, 2);
    constant KERNEL21_BIAS  : integer := 0;
    constant KERNEL21_EXPECTED : int32_outputs_t := (
        298, -128, -554,
        -1832, -2258, -2684,
        -3962, -4388, -4814
    );

    -- ==================================================================
    -- Kernel (output channel) 22
    --   scale_w = 0.00146320
    -- ==================================================================
    constant KERNEL22_CH0_W : int8_kernel_t := (-64, -106, -16, -119, 87, 11, -73, 66, -127);
    constant KERNEL22_CH1_W : int8_kernel_t := (-51, -25, -113, -85, -22, 101, 127, 85, -77);
    constant KERNEL22_CH2_W : int8_kernel_t := (-85, 113, 43, 1, 15, -109, -47, 124, -33);
    constant KERNEL22_BIAS  : integer := 0;
    constant KERNEL22_EXPECTED : int32_outputs_t := (
        186, -297, -780,
        -2229, -2712, -3195,
        -4644, -5127, -5610
    );

    -- ==================================================================
    -- Kernel (output channel) 23
    --   scale_w = 0.00149760
    -- ==================================================================
    constant KERNEL23_CH0_W : int8_kernel_t := (-3, -103, -73, -2, -76, -15, 53, -124, 45);
    constant KERNEL23_CH1_W : int8_kernel_t := (-86, -60, 46, 99, -36, -54, -118, -70, -114);
    constant KERNEL23_CH2_W : int8_kernel_t := (-30, 26, -125, 111, 82, -127, -62, 43, -22);
    constant KERNEL23_BIAS  : integer := 0;
    constant KERNEL23_EXPECTED : int32_outputs_t := (
        -8387, -9367, -10347,
        -13287, -14267, -15247,
        -18187, -19167, -20147
    );

    -- ==================================================================
    -- Kernel (output channel) 24
    --   scale_w = 0.00156223
    -- ==================================================================
    constant KERNEL24_CH0_W : int8_kernel_t := (-14, -55, 99, -70, 101, 6, 22, 96, -20);
    constant KERNEL24_CH1_W : int8_kernel_t := (-69, -21, 98, -92, 27, -127, 64, 42, 5);
    constant KERNEL24_CH2_W : int8_kernel_t := (53, 2, 69, -100, -20, 52, 120, 62, -89);
    constant KERNEL24_BIAS  : integer := 0;
    constant KERNEL24_EXPECTED : int32_outputs_t := (
        949, 819, 689,
        299, 169, 39,
        -351, -481, -611
    );

    -- ==================================================================
    -- Kernel (output channel) 25
    --   scale_w = 0.00153312
    -- ==================================================================
    constant KERNEL25_CH0_W : int8_kernel_t := (100, -25, -25, -109, -19, 92, 24, -68, 40);
    constant KERNEL25_CH1_W : int8_kernel_t := (-39, 112, -109, -41, -125, -50, 41, 118, 20);
    constant KERNEL25_CH2_W : int8_kernel_t := (127, 23, 73, 100, 103, -69, 119, 77, -59);
    constant KERNEL25_BIAS  : integer := 0;
    constant KERNEL25_EXPECTED : int32_outputs_t := (
        -1807, -2437, -3067,
        -4957, -5587, -6217,
        -8107, -8737, -9367
    );

    -- ==================================================================
    -- Kernel (output channel) 26
    --   scale_w = 0.00150654
    -- ==================================================================
    constant KERNEL26_CH0_W : int8_kernel_t := (-63, -108, 29, -105, 53, 39, -108, 39, -10);
    constant KERNEL26_CH1_W : int8_kernel_t := (61, 76, -127, 120, 110, 52, -113, -41, -34);
    constant KERNEL26_CH2_W : int8_kernel_t := (-33, 73, 45, 100, -49, 42, 49, -101, -123);
    constant KERNEL26_BIAS  : integer := 0;
    constant KERNEL26_EXPECTED : int32_outputs_t := (
        -436, -465, -494,
        -581, -610, -639,
        -726, -755, -784
    );

    -- ==================================================================
    -- Kernel (output channel) 27
    --   scale_w = 0.00147579
    -- ==================================================================
    constant KERNEL27_CH0_W : int8_kernel_t := (-71, 85, -127, -117, 68, 66, 105, -101, -98);
    constant KERNEL27_CH1_W : int8_kernel_t := (66, 112, 76, 19, 41, 123, -85, -59, 92);
    constant KERNEL27_CH2_W : int8_kernel_t := (-91, -75, 92, 38, 38, -59, -3, 117, -79);
    constant KERNEL27_BIAS  : integer := 0;
    constant KERNEL27_EXPECTED : int32_outputs_t := (
        1200, 1802, 2404,
        4210, 4812, 5414,
        7220, 7822, 8424
    );

    -- ==================================================================
    -- Kernel (output channel) 28
    --   scale_w = 0.00148584
    -- ==================================================================
    constant KERNEL28_CH0_W : int8_kernel_t := (1, 60, -95, 126, -65, -36, -30, -84, -127);
    constant KERNEL28_CH1_W : int8_kernel_t := (73, 33, -126, -84, 127, 45, 55, -74, -58);
    constant KERNEL28_CH2_W : int8_kernel_t := (-16, -20, -85, 14, 17, -16, 25, -46, 38);
    constant KERNEL28_BIAS  : integer := 0;
    constant KERNEL28_EXPECTED : int32_outputs_t := (
        -4183, -4362, -4541,
        -5078, -5257, -5436,
        -5973, -6152, -6331
    );

    -- ==================================================================
    -- Kernel (output channel) 29
    --   scale_w = 0.00152581
    -- ==================================================================
    constant KERNEL29_CH0_W : int8_kernel_t := (45, -68, -127, 64, 28, -66, 121, -55, 84);
    constant KERNEL29_CH1_W : int8_kernel_t := (62, -107, 80, -117, -72, -22, -85, 124, -25);
    constant KERNEL29_CH2_W : int8_kernel_t := (50, -113, 73, -40, -96, 19, 62, 113, -76);
    constant KERNEL29_BIAS  : integer := 0;
    constant KERNEL29_EXPECTED : int32_outputs_t := (
        -1122, -1412, -1702,
        -2572, -2862, -3152,
        -4022, -4312, -4602
    );

    -- ==================================================================
    -- Kernel (output channel) 30
    --   scale_w = 0.00136285
    -- ==================================================================
    constant KERNEL30_CH0_W : int8_kernel_t := (-68, 28, 38, 58, 78, -32, 83, 108, -34);
    constant KERNEL30_CH1_W : int8_kernel_t := (104, 70, 127, -75, -66, -38, 14, 92, -75);
    constant KERNEL30_CH2_W : int8_kernel_t := (74, -48, 87, -3, -122, -76, -97, 76, -90);
    constant KERNEL30_BIAS  : integer := 0;
    constant KERNEL30_EXPECTED : int32_outputs_t := (
        4457, 5221, 5985,
        8277, 9041, 9805,
        12097, 12861, 13625
    );

    -- ==================================================================
    -- Kernel (output channel) 31
    --   scale_w = 0.00151049
    -- ==================================================================
    constant KERNEL31_CH0_W : int8_kernel_t := (-13, 25, -73, 33, -127, -95, -120, -43, -52);
    constant KERNEL31_CH1_W : int8_kernel_t := (14, -28, 55, 112, 42, -56, -125, 41, -69);
    constant KERNEL31_CH2_W : int8_kernel_t := (60, 80, 44, 115, 116, 20, -99, 107, -69);
    constant KERNEL31_BIAS  : integer := 0;
    constant KERNEL31_EXPECTED : int32_outputs_t := (
        -7735, -8602, -9469,
        -12070, -12937, -13804,
        -16405, -17272, -18139
    );

end package first_layer_kernels0_to31_pkg;
