-- first_conv_bn_relu_kernel2_pkg.vhd
-- VHDL-2008 package of INT8 folded weights, Q.16 fixed-point
-- SCALE_FX/BIAS_FX constants, and Q.16 fixed-point golden output
-- constants for the kernel-2 folded Conv-BN-ReLU proof-of-concept.
--
-- Generated by: scripts/generate_bn_relu_fixed_point_vectors.py --kernel-id 2
-- Source data : hardware/vhdl_conv3x3/test_vectors/conv_bn_relu_kernel2/kernel2_bn_relu_fixed_point_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 2 only), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- BatchNorm folding ----------------------------------------------------
-- scale_bn[2] = gamma[2] / sqrt(running_var[2] + eps) = 3.753419
-- b_folded[2] = beta[2] - running_mean[2] * scale_bn[2] = -0.011989
-- (eps = 1e-05, torch.nn.BatchNorm2d default)
--
-- ---- Folded weight quantization ------------------------------------------
-- scale_w_folded[2] = max(|w_folded[2]|) / 127 = 0.00575681
-- symmetric per-channel INT8, SAME convention as
-- scripts/analyze_first_conv_bn_relu_fidelity.py, applied to kernel 2 only.
--
-- ---- Fixed-point format (Q.16, signed, 16 fractional bits) --------------
-- real_value ~= fixed_value / 2^16
-- SCALE_FX = round(scale_x * scale_w_folded[2] * 2^16), scale_x = 1.0 exact
--            for this toy patch (see generator script docstring)
-- BIAS_FX  = round(b_folded[2] * 2^16)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX (already Q.16, no shift);
--           biased_fx = product_fx + BIAS_FX (same format, no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weights, the fixed-point scale/bias
-- constants, and the exact Q.16 fixed-point expected outputs so a
-- testbench can confirm a kernel-2 folded Conv-BN-ReLU VHDL design produces
-- the SAME fixed-point integer values as this Python script for kernel 2 on
-- the canonical 5x5x3 toy input. It does NOT validate the other 31 output
-- channels, does NOT implement padding, and does NOT claim board-tested
-- or measured performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_conv_bn_relu_kernel2_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    -- FOLDED (BatchNorm-absorbed) INT8 weights, kernel 2
    constant K2_FOLDED_CH0_W : int8_kernel_t := (36, 52, 39, -1, 99, -91, 10, -85, 37);
    constant K2_FOLDED_CH1_W : int8_kernel_t := (-41, 40, -25, 106, -72, -74, -73, 114, 43);
    constant K2_FOLDED_CH2_W : int8_kernel_t := (118, -106, -127, -99, -86, 46, 44, 102, -68);

    -- Fixed-point Q.16 constants
    constant FRAC_BITS : integer := 16;
    constant SCALE_FX  : integer := 377;   -- unsigned, Q.16
    constant BIAS_FX   : integer := -786;   -- signed,   Q.16

    -- 9 Q.16 fixed-point expected outputs (row-major, output_index 0..8),
    -- EXACT integers -- this is what the VHDL testbench compares against.
    type fx_outputs_t is array (0 to 8) of integer;
    constant K2_BN_RELU_EXPECTED_FX : fx_outputs_t := (
        573008, 689124, 805240,
        1153588, 1269704, 1385820,
        1734168, 1850284, 1966400
    );

end package first_conv_bn_relu_kernel2_pkg;
