-- first_conv_bn_relu_kernel8_real_tile_q20_pkg.vhd
-- VHDL-2008 package of INT8 folded weights, Q.20 fixed-point
-- SCALE_FX/BIAS_FX constants, and Q.20 fixed-point golden output
-- constants for the kernel-8 folded Conv-BN-ReLU design, evaluated on a
-- REAL UAVSAR-tile-derived patch (see real_tile_stimulus_pkg.vhd for the
-- pixel data), NOT the synthetic 5x5x3 toy patch.
--
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py --kernel-id 8
-- Source data : hardware/vhdl_conv3x3/real_tile_vectors/kernel8/kernel8_real_tile_bn_relu_fixed_point_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 8 only), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- BatchNorm folding ----------------------------------------------------
-- scale_bn[8] = 2.195013
-- b_folded[8] = -0.023373
-- (eps = 1e-05, torch.nn.BatchNorm2d default)
--
-- ---- Folded weight quantization ------------------------------------------
-- scale_w_folded[8] = 0.00326803
-- symmetric per-output-channel INT8, SAME convention as
-- scripts/analyze_first_layer_fixed_point_segmentation_impact.py.
--
-- ---- REAL-TILE activation quantization (NOT scale_x=1.0) -------------------
-- scale_x = 0.01808654, computed from the FULL normalized 256x256 tile
-- 'tile_16_42.tif', matching
-- analyze_first_layer_fixed_point_segmentation_impact.py's per-tile
-- convention exactly. This is the KEY difference from every toy-patch
-- kernel package in this repo, where scale_x = 1.0 was exact by
-- construction.
--
-- ---- Fixed-point format (Q.20, signed, 20 fractional bits) --------------
-- real_value ~= fixed_value / 2^20
-- SCALE_FX = round(scale_x * scale_w_folded[8] * 2^20)
-- BIAS_FX  = round(b_folded[8] * 2^20)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX (already Q.20, no shift);
--           biased_fx = product_fx + BIAS_FX (same format, no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weights (IDENTICAL to
-- first_conv_bn_relu_kernel8_pkg.vhd's, since weights do not depend on
-- input), the REAL-TILE fixed-point scale/bias constants, and the exact
-- Q.20 fixed-point expected outputs for a REAL 6x6 UAVSAR
-- patch, so a testbench can confirm the EXISTING, UNMODIFIED
-- stream_conv3x3_3chan_kernel8_bn_relu_pipelined datapath produces the SAME
-- fixed-point integer values as this Python script on REAL sensor-derived
-- data. It does NOT validate the other 31 output channels, does NOT
-- implement padding, and does NOT claim board-tested or measured
-- performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_conv_bn_relu_kernel8_real_tile_q20_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    -- IDENTICAL to first_conv_bn_relu_kernel8_pkg's K8_FOLDED_CH*_W --
    -- weights do not depend on the input patch.
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    constant K8_RT_FOLDED_CH0_W : int8_kernel_t := (21, -29, 58, -47, -82, 97, -56, -24, -123);
    constant K8_RT_FOLDED_CH1_W : int8_kernel_t := (89, 101, 51, -88, -127, -102, 99, 65, 113);
    constant K8_RT_FOLDED_CH2_W : int8_kernel_t := (73, 41, 7, -93, -108, -115, 56, -60, -19);

    -- Fixed-point Q.20 constants -- REAL scale_x baked in (differs
    -- from the toy-patch package's SCALE_FX, which assumed scale_x=1.0).
    constant FRAC_BITS : integer := 20;
    constant SCALE_FX  : integer := 62;   -- unsigned, Q.20
    constant BIAS_FX   : integer := -24508;   -- signed,   Q.20

    -- 16 Q.20 fixed-point expected outputs (row-major,
    -- output_index 0..15), EXACT integers -- this is what the
    -- VHDL testbench compares against.
    type fx_outputs_t is array (0 to 15) of integer;
    constant K8_RT_BN_RELU_EXPECTED_FX : fx_outputs_t := (
        1479922, 1784652, 1533242, 239798,
        0, 1017340, 1356976, 2017834,
        0, 362620, 1768842, 1670944,
        0, 0, 0, 1139914
    );

end package first_conv_bn_relu_kernel8_real_tile_q20_pkg;
