-- first_layer_4out_bn_relu_resource_shared_pkg.vhd
-- VHDL-2008 package for the RESOURCE-SHARED (time-multiplexed) folded
-- Conv-BN-ReLU prototype covering kernels 0-3 of enc1.block.0.weight.
--
-- Generated by: scripts/generate_resource_shared_32out_bn_relu_vectors.py --num-kernels 4
-- Source data : hardware/vhdl_conv3x3/test_vectors/resource_shared_4out_bn_relu/resource_shared_4out_bn_relu_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernels 0-3), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- Fixed-point format (Q.16, signed, 16 fractional bits) --------------
-- real_value ~= fixed_value / 2^16
-- SCALE_FX_LUT(k) = round(scale_x * scale_w_folded[k] * 2^16), scale_x=1.0 exact
-- BIAS_FX_LUT(k)  = round(b_folded[k] * 2^16)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX_LUT(k) (no shift);
--           biased_fx = product_fx + BIAS_FX_LUT(k) (no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- Output ordering (matches this package's EXPECTED_RELU_FX array) ------
-- WINDOW-MAJOR, KERNEL-MINOR: for each of 9 valid window positions
-- (row-major), kernel outputs 0..3 together, before the next window.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weight LUT, per-kernel SCALE_FX/
-- BIAS_FX LUTs, and the exact Q.16 fixed-point expected outputs so a
-- testbench can confirm a resource-shared VHDL design produces the SAME
-- fixed-point integer values as this Python script for kernels 0-3 on
-- the canonical 5x5x3 toy input. It does NOT validate the other
-- 28 output channels, does NOT implement padding, and does NOT claim
-- board-tested or measured performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_layer_4out_bn_relu_resource_shared_pkg is

    constant NUM_KERNELS : integer := 4;
    constant NUM_WINDOWS : integer := 9;
    constant FRAC_BITS   : integer := 16;

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    -- Folded INT8 weight LUT: NUM_KERNELS entries per channel.
    type weight_lut_t is array (0 to 3) of int8_kernel_t;

    constant CH0_WEIGHT_LUT : weight_lut_t := ((110, 117, -38, 127, -28, 33, -66, 86, 124), (-72, 13, -127, 119, -101, 103, 28, -30, 86), (36, 52, 39, -1, 99, -91, 10, -85, 37), (-91, 61, -55, 75, -36, 67, -97, -62, 37));

    constant CH1_WEIGHT_LUT : weight_lut_t := ((-103, 120, 24, 102, 20, 67, -19, 108, 20), (23, 102, 15, -39, 41, -32, 59, 124, 82), (-41, 40, -25, 106, -72, -74, -73, 114, 43), (21, -37, 71, 83, -94, -70, 115, -43, -46));

    constant CH2_WEIGHT_LUT : weight_lut_t := ((-68, 31, -72, -21, -59, 92, -112, -66, -44), (-55, 68, 18, 65, -75, -127, -45, -90, 107), (118, -106, -127, -99, -86, 46, 44, 102, -68), (-127, -81, 25, -23, -106, -3, -86, -103, -68));

    -- Per-kernel Q.16 fixed-point scale/bias LUTs.
    type fx_lut_t is array (0 to 3) of integer;
    constant SCALE_FX_LUT : fx_lut_t := (135, 216, 377, 110);
    constant BIAS_FX_LUT  : fx_lut_t := (-936, -1453, -786, -1272);

    -- 36 Q.16 fixed-point expected outputs, WINDOW-MAJOR /
    -- KERNEL-MINOR order (index = window_idx * NUM_KERNELS + kernel_idx).
    -- EXACT integers -- this is what the VHDL testbench compares against.
    type fx_outputs_t is array (0 to 35) of integer;
    constant EXPECTED_RELU_FX : fx_outputs_t := (
        1522809, 1988771, 573008, 288688, 1720179, 2183819, 689124, 340498,
        1917549, 2378867, 805240, 392308, 2509659, 2964011, 1153588, 547738,
        2707029, 3159059, 1269704, 599548, 2904399, 3354107, 1385820, 651358,
        3496509, 3939251, 1734168, 806788, 3693879, 4134299, 1850284, 858598,
        3891249, 4329347, 1966400, 910408
    );

end package first_layer_4out_bn_relu_resource_shared_pkg;
