-- first_layer_kernels0_to3_pkg.vhd
-- VHDL-2008 package of INT8 weight and INT32 golden-output constants for
-- first-layer U-Net convolution kernels 0-3.
--
-- Generated by: scripts/export_first_layer_multi_kernel_vhdl_vectors.py
-- Source data : hardware/vhdl_conv3x3/test_vectors/multi_kernel_first_layer/first_layer_kernels0_to3_int8.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight  (shape [32, 3, 3, 3])
-- Output chs : [0, 1, 2, 3]
--
-- ---- Quantization -------------------------------------------------------
-- Scheme : symmetric per-tensor INT8 for weights, scale computed per kernel
--          scale_w = max(|w_float|) / 127
-- Input  : canonical 5x5x3 toy patch (ch0=1..25, ch1=2xch0, ch2=-1xch0),
--          scale_x = 1.0 (already integer-valued)
--
-- ---- Bias -----------------------------------------------------------------
-- The first Conv2d in this U-Net has NO direct bias (Conv2d -> BatchNorm;
-- BN params are NOT folded here). Therefore bias_int32 = 0 for every kernel.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies weight and golden-output constants so a testbench can
-- confirm the VHDL stream_conv3x3_3chan_cell integer datapath produces the
-- SAME INT32 values as the Python golden-vector script when driven with real
-- trained-model INT8 weights, across kernels 0-3.
-- It does NOT validate full quantized U-Net inference (BatchNorm is not applied),
-- and it does NOT cover the full set of 32 first-layer output channels.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_layer_kernels0_to3_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    -- 9 INT32 expected outputs per kernel, row-major (output_index 0..8)
    type int32_outputs_t is array (0 to 8) of integer;

    constant NUM_KERNELS : integer := 4;
    type kernel_id_t is array (0 to NUM_KERNELS - 1) of integer;
    constant KERNEL_IDS : kernel_id_t := (0, 1, 2, 3);

    -- ==================================================================
    -- Kernel (output channel) 0
    --   scale_w = 0.00136063
    -- ==================================================================
    constant KERNEL0_CH0_W : int8_kernel_t := (110, 117, -38, 127, -28, 33, -66, 86, 124);
    constant KERNEL0_CH1_W : int8_kernel_t := (-103, 120, 24, 102, 20, 67, -19, 108, 20);
    constant KERNEL0_CH2_W : int8_kernel_t := (-68, 31, -72, -21, -59, 92, -112, -66, -44);
    constant KERNEL0_BIAS  : integer := 0;
    constant KERNEL0_EXPECTED : int32_outputs_t := (
        11287, 12749, 14211,
        18597, 20059, 21521,
        25907, 27369, 28831
    );

    -- ==================================================================
    -- Kernel (output channel) 1
    --   scale_w = 0.00150574
    -- ==================================================================
    constant KERNEL1_CH0_W : int8_kernel_t := (-72, 13, -127, 119, -101, 103, 28, -30, 86);
    constant KERNEL1_CH1_W : int8_kernel_t := (23, 102, 15, -39, 41, -32, 59, 124, 82);
    constant KERNEL1_CH2_W : int8_kernel_t := (-55, 68, 18, 65, -75, -127, -45, -90, 107);
    constant KERNEL1_BIAS  : integer := 0;
    constant KERNEL1_EXPECTED : int32_outputs_t := (
        9214, 10117, 11020,
        13729, 14632, 15535,
        18244, 19147, 20050
    );

    -- ==================================================================
    -- Kernel (output channel) 2
    --   scale_w = 0.00153375
    -- ==================================================================
    constant KERNEL2_CH0_W : int8_kernel_t := (36, 52, 39, -1, 99, -91, 10, -85, 37);
    constant KERNEL2_CH1_W : int8_kernel_t := (-41, 40, -25, 106, -72, -74, -73, 114, 43);
    constant KERNEL2_CH2_W : int8_kernel_t := (118, -106, -127, -99, -86, 46, 44, 102, -68);
    constant KERNEL2_BIAS  : integer := 0;
    constant KERNEL2_EXPECTED : int32_outputs_t := (
        1522, 1830, 2138,
        3062, 3370, 3678,
        4602, 4910, 5218
    );

    -- ==================================================================
    -- Kernel (output channel) 3
    --   scale_w = 0.00151875
    -- ==================================================================
    constant KERNEL3_CH0_W : int8_kernel_t := (-91, 61, -55, 75, -36, 67, -97, -62, 37);
    constant KERNEL3_CH1_W : int8_kernel_t := (21, -37, 71, 83, -94, -70, 115, -43, -46);
    constant KERNEL3_CH2_W : int8_kernel_t := (-127, -81, 25, -23, -106, -3, -86, -103, -68);
    constant KERNEL3_BIAS  : integer := 0;
    constant KERNEL3_EXPECTED : int32_outputs_t := (
        2636, 3107, 3578,
        4991, 5462, 5933,
        7346, 7817, 8288
    );

end package first_layer_kernels0_to3_pkg;
