-- first_conv_bn_relu_kernel0_real_tile_pkg.vhd
-- VHDL-2008 package of INT8 folded weights, Q.16 fixed-point
-- SCALE_FX/BIAS_FX constants, and Q.16 fixed-point golden output
-- constants for the kernel-0 folded Conv-BN-ReLU design, evaluated on a
-- REAL UAVSAR-tile-derived patch (see real_tile_stimulus_pkg.vhd for the
-- pixel data), NOT the synthetic 5x5x3 toy patch.
--
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py --kernel-id 0
-- Source data : hardware/vhdl_conv3x3/real_tile_vectors/kernel0/kernel0_real_tile_bn_relu_fixed_point_vectors.json
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 0 only), folded with
--              enc1.block.1 (BatchNorm2d, eval-mode running stats)
--
-- ---- BatchNorm folding ----------------------------------------------------
-- scale_bn[0] = 1.515678
-- b_folded[0] = -0.014275
-- (eps = 1e-05, torch.nn.BatchNorm2d default)
--
-- ---- Folded weight quantization ------------------------------------------
-- scale_w_folded[0] = 0.00206228
-- symmetric per-output-channel INT8, SAME convention as
-- scripts/analyze_first_layer_fixed_point_segmentation_impact.py.
--
-- ---- REAL-TILE activation quantization (NOT scale_x=1.0) -------------------
-- scale_x = 0.01808654, computed from the FULL normalized 256x256 tile
-- 'tile_16_42.tif', matching
-- analyze_first_layer_fixed_point_segmentation_impact.py's per-tile
-- convention exactly. This is the KEY difference from every toy-patch
-- kernel package in this repo, where scale_x = 1.0 was exact by
-- construction.
--
-- ---- Fixed-point format (Q.16, signed, 16 fractional bits) --------------
-- real_value ~= fixed_value / 2^16
-- SCALE_FX = round(scale_x * scale_w_folded[0] * 2^16)
-- BIAS_FX  = round(b_folded[0] * 2^16)
-- Datapath: product_fx = raw_conv_int32 * SCALE_FX (already Q.16, no shift);
--           biased_fx = product_fx + BIAS_FX (same format, no shift);
--           relu_fx = biased_fx if biased_fx > 0 else 0.
--
-- ---- What this validates --------------------------------------------------
-- This package supplies the folded INT8 weights (IDENTICAL to
-- first_conv_bn_relu_kernel0_pkg.vhd's, since weights do not depend on
-- input), the REAL-TILE fixed-point scale/bias constants, and the exact
-- Q.16 fixed-point expected outputs for a REAL 6x6 UAVSAR
-- patch, so a testbench can confirm the EXISTING, UNMODIFIED
-- stream_conv3x3_3chan_kernel0_bn_relu_pipelined datapath produces the SAME
-- fixed-point integer values as this Python script on REAL sensor-derived
-- data. It does NOT validate the other 31 output channels, does NOT
-- implement padding, and does NOT claim board-tested or measured
-- performance.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package first_conv_bn_relu_kernel0_real_tile_pkg is

    -- 9 INT8 weights per input channel, row-major (w0=top-left .. w8=bottom-right)
    -- IDENTICAL to first_conv_bn_relu_kernel0_pkg's K0_FOLDED_CH*_W --
    -- weights do not depend on the input patch.
    type int8_kernel_t is array (0 to 8) of integer range -128 to 127;

    constant K0_RT_FOLDED_CH0_W : int8_kernel_t := (110, 117, -38, 127, -28, 33, -66, 86, 124);
    constant K0_RT_FOLDED_CH1_W : int8_kernel_t := (-103, 120, 24, 102, 20, 67, -19, 108, 20);
    constant K0_RT_FOLDED_CH2_W : int8_kernel_t := (-68, 31, -72, -21, -59, 92, -112, -66, -44);

    -- Fixed-point Q.16 constants -- REAL scale_x baked in (differs
    -- from the toy-patch package's SCALE_FX, which assumed scale_x=1.0).
    constant FRAC_BITS : integer := 16;
    constant SCALE_FX  : integer := 2;   -- unsigned, Q.16
    constant BIAS_FX   : integer := -936;   -- signed,   Q.16

    -- 16 Q.16 fixed-point expected outputs (row-major,
    -- output_index 0..15), EXACT integers -- this is what the
    -- VHDL testbench compares against.
    type fx_outputs_t is array (0 to 15) of integer;
    constant K0_RT_BN_RELU_EXPECTED_FX : fx_outputs_t := (
        0, 0, 0, 88064,
        4360, 0, 0, 0,
        33406, 0, 0, 0,
        128122, 0, 0, 0
    );

end package first_conv_bn_relu_kernel0_real_tile_pkg;
