-- real_tile_stimulus_pkg.vhd
-- Shared REAL UAVSAR-tile-derived pixel stimulus for the real-tile
-- Conv-BN-ReLU verification testbench(es).
--
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py
-- This package is regenerated identically regardless of --kernel-id (kernel
-- 0 and kernel 2 both observe the SAME real patch) -- content is
-- deterministic given the same --tile-name/--row-offset/--col-offset/
-- --block-size arguments.
--
-- ---- Source -----------------------------------------------------------
-- Tile        : tile_16_42.tif (fp2_lee7_tiles/tile_16_42.tif)
-- Split CSV   : csv_splits/flood_splits_ieee_png_filtered_standard_strict_train_val/strict_no_overlap/heldout_fp2_test.csv
-- Sub-block   : 6x6, top-left offset (row=125, col=125) within the
--               full 256x256 tile
-- Normalization: FloodTileDataset._normalize_per_tile (percentile-clip 1-99
--               + zero-mean/unit-variance), scripts/train_unet_baseline_tuned.py
-- Quantization : scale_x = max(|x_full_tile|) / 127, computed from the FULL
--               normalized tile (matches
--               analyze_first_layer_fixed_point_segmentation_impact.py's
--               convention exactly); scale_x = 0.01808654 for this tile.
--               This 6x6 block is a direct slice of the
--               ALREADY-quantized full-tile INT8 array, not independently
--               re-quantized.
--
-- ---- What this is NOT --------------------------------------------------
-- This is real sensor-derived pixel data (via the model's own real
-- normalization + quantization pipeline), NOT a synthetic toy patch. It is
-- NOT the full 256x256 tile -- only a small, real, contiguous sub-block,
-- chosen so the EXISTING window3x3_stream/stream_conv3x3_3chan_cell
-- streaming interface (unmodified) can be exercised exactly as it already
-- is for the synthetic 5x5 toy patch elsewhere in this repo.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package real_tile_stimulus_pkg is

    constant BLOCK_SIZE : integer := 6;

    -- Flat, row-major INT8 pixel arrays, one per input channel, length
    -- BLOCK_SIZE*BLOCK_SIZE = 36.
    type block_pixels_t is array (0 to 35) of integer range -128 to 127;

    constant REAL_TILE_CH0 : block_pixels_t := (27, -59, -69, -3, 74, -31, 49, -56, -39, -49, -47, 90, 79, 20, -72, -50, -38, -25, 52, 79, -16, -56, -43, -22, 38, 75, 25, -41, -55, -41, -17, 72, 65, -41, -22, -44);
    constant REAL_TILE_CH1 : block_pixels_t := (37, -16, -39, -2, 70, -2, 35, -24, -39, -50, -15, 90, 90, 34, -50, -51, -30, -51, 48, 91, -20, -44, -35, -50, 31, 68, 63, -2, -26, -23, -13, 92, 67, 9, -7, -21);
    constant REAL_TILE_CH2 : block_pixels_t := (17, -58, -84, -26, 15, -17, 10, -59, -60, -59, -46, 123, 93, 48, -78, -76, -58, -69, 19, 63, -61, -71, -72, -71, -17, 67, 69, -50, -76, -74, -26, 77, 31, -30, -56, -52);

end package real_tile_stimulus_pkg;
