#!/usr/bin/env bash
# run_ghdl_3chan_4out_cell.sh
# Simulate tb_stream_conv3x3_3chan_4out_cell using GHDL.
#
# This testbench drives stream_conv3x3_3chan_4out_cell -- the first actual
# multi-output first-layer convolution HARDWARE PROTOTYPE (not a sequential
# weight-reload verification harness) -- with the canonical 5x5x3 toy input
# and checks all 9 output positions x 4 kernels (36 INT32 values) against
# the Python golden vectors baked into first_layer_kernels0_to3_pkg.
#
# Weight source:
#   models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
#   tensor key: enc1.block.0.weight, output channels 0-3
#   Generated by: scripts/export_first_layer_multi_kernel_vhdl_vectors.py
#
# Analyzes (dependency order):
#   window3x3_stream.vhd
#   conv3x3_dot_pipelined.vhd
#   first_layer_kernels0_to3_pkg.vhd
#   stream_conv3x3_3chan_4out_cell.vhd
#   tb_stream_conv3x3_3chan_4out_cell.vhd
#
# Usage:
#   bash hardware/vhdl_conv3x3/run_ghdl_3chan_4out_cell.sh
#   bash hardware/vhdl_conv3x3/run_ghdl_3chan_4out_cell.sh --vcd
#   bash hardware/vhdl_conv3x3/run_ghdl_3chan_4out_cell.sh --wave
#
# Expected output:
#   PASS output 1: y0=11287 y1=9214 y2=1522 y3=2636
#   ...
#   PASS output 9: y0=28831 y1=20050 y2=5218 y3=8288
#   === All stream_conv3x3_3chan_4out_cell tests PASSED === (9 positions x 4 kernels = 36 / 36 outputs match Python golden vectors)
#
# Scope note: this is a 4-output first-layer convolution PROTOTYPE. It is
# NOT full U-Net FPGA inference, has NOT been run on real board hardware,
# and does NOT include BatchNorm folding or a measured speedup figure.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! command -v ghdl &>/dev/null; then
    echo ""
    echo "ERROR: GHDL not found in PATH."
    echo ""
    echo "Install GHDL:"
    echo "  Ubuntu/Debian : sudo apt install ghdl"
    echo "  Fedora/RHEL   : sudo dnf install ghdl"
    echo "  macOS (brew)  : brew install ghdl"
    echo "  Releases      : https://github.com/ghdl/ghdl/releases"
    echo ""
    echo "Alternatively, use Vivado xsim:"
    echo "  xvhdl --2008 window3x3_stream.vhd conv3x3_dot_pipelined.vhd \\"
    echo "               first_layer_kernels0_to3_pkg.vhd \\"
    echo "               stream_conv3x3_3chan_4out_cell.vhd \\"
    echo "               tb_stream_conv3x3_3chan_4out_cell.vhd"
    echo "  xelab -debug typical tb_stream_conv3x3_3chan_4out_cell -s tb_4out_sim"
    echo "  xsim  tb_4out_sim --runall"
    echo ""
    exit 1
fi

echo "Using: $(ghdl --version | head -1)"
echo ""

EXTRA_RUN_FLAGS=""
if [[ "${1:-}" == "--vcd" ]]; then
    EXTRA_RUN_FLAGS="--vcd=tb_stream_conv3x3_3chan_4out_cell.vcd"
    echo "Waveform: tb_stream_conv3x3_3chan_4out_cell.vcd  (open with GTKWave)"
elif [[ "${1:-}" == "--wave" ]]; then
    EXTRA_RUN_FLAGS="--wave=tb_stream_conv3x3_3chan_4out_cell.ghw"
    echo "Waveform: tb_stream_conv3x3_3chan_4out_cell.ghw"
fi

echo "=== [1/3] Analyzing VHDL-2008 sources ==="
ghdl -a --std=08 window3x3_stream.vhd
echo "  OK  window3x3_stream.vhd"
ghdl -a --std=08 conv3x3_dot_pipelined.vhd
echo "  OK  conv3x3_dot_pipelined.vhd"
ghdl -a --std=08 first_layer_kernels0_to3_pkg.vhd
echo "  OK  first_layer_kernels0_to3_pkg.vhd"
ghdl -a --std=08 stream_conv3x3_3chan_4out_cell.vhd
echo "  OK  stream_conv3x3_3chan_4out_cell.vhd"
ghdl -a --std=08 tb_stream_conv3x3_3chan_4out_cell.vhd
echo "  OK  tb_stream_conv3x3_3chan_4out_cell.vhd"
echo ""

echo "=== [2/3] Elaborating tb_stream_conv3x3_3chan_4out_cell ==="
ghdl -e --std=08 tb_stream_conv3x3_3chan_4out_cell
echo "  OK"
echo ""

echo "=== [3/3] Running simulation (stop after 600 ns) ==="
# shellcheck disable=SC2086
ghdl -r --std=08 tb_stream_conv3x3_3chan_4out_cell \
    --stop-time=600ns \
    --assert-level=failure \
    ${EXTRA_RUN_FLAGS}

echo ""
echo "=== Simulation complete ==="
