#!/usr/bin/env bash
# run_ghdl_32out_dsp.sh
# Simulate tb_stream_conv3x3_3chan_32out_cell_dsp using GHDL.
#
# This testbench drives stream_conv3x3_3chan_32out_cell_dsp -- the COMPLETE
# 32-output first Conv2d layer (kernels 0-31 of enc1.block.0.weight,
# DSP-aware) -- with the canonical 5x5x3 toy input and checks all 9 output
# positions x 32 kernels (288 INT32 values) against the Python golden
# vectors (first_layer_kernels0_to31_pkg).
#
# Weight source:
#   models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
#   tensor key: enc1.block.0.weight, output channels 0-31 (ALL channels)
#   Generated by: scripts/export_first_layer_multi_kernel_vhdl_vectors.py 0-31
#
# Analyzes (dependency order):
#   window3x3_stream.vhd
#   conv3x3_dot_pipelined_dsp.vhd
#   first_layer_kernels0_to31_pkg.vhd
#   stream_conv3x3_3chan_32out_cell_dsp.vhd
#   tb_stream_conv3x3_3chan_32out_cell_dsp.vhd
#
# Usage:
#   bash hardware/vhdl_conv3x3/run_ghdl_32out_dsp.sh
#   bash hardware/vhdl_conv3x3/run_ghdl_32out_dsp.sh --vcd
#   bash hardware/vhdl_conv3x3/run_ghdl_32out_dsp.sh --wave
#
# Expected output:
#   PASS output 1: y0=11287 y1=9214 ... y31=-7735
#   ...
#   === All stream_conv3x3_3chan_32out_cell_dsp tests PASSED === (9 positions x 32 kernels = 288 / 288 outputs match Python golden vectors)
#
# Scope note: this is the COMPLETE first-layer output-channel set as a
# HARDWARE PROTOTYPE, extending the existing verified 24-output DSP-aware
# design. It is NOT full U-Net FPGA inference, has NOT been run on real
# board hardware, and does NOT include BatchNorm folding, padding, ReLU,
# or a measured speedup/power figure.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! command -v ghdl &>/dev/null; then
    echo ""
    echo "ERROR: GHDL not found in PATH."
    echo ""
    echo "Install GHDL:"
    echo "  Ubuntu/Debian : sudo apt install ghdl"
    echo "  Fedora/RHEL   : sudo dnf install ghdl"
    echo "  macOS (brew)  : brew install ghdl"
    echo "  Releases      : https://github.com/ghdl/ghdl/releases"
    echo ""
    echo "Alternatively, use Vivado xsim:"
    echo "  xvhdl --2008 window3x3_stream.vhd conv3x3_dot_pipelined_dsp.vhd \\"
    echo "               first_layer_kernels0_to31_pkg.vhd \\"
    echo "               stream_conv3x3_3chan_32out_cell_dsp.vhd \\"
    echo "               tb_stream_conv3x3_3chan_32out_cell_dsp.vhd"
    echo "  xelab -debug typical tb_stream_conv3x3_3chan_32out_cell_dsp -s tb_32out_dsp_sim"
    echo "  xsim  tb_32out_dsp_sim --runall"
    echo ""
    exit 1
fi

echo "Using: $(ghdl --version | head -1)"
echo ""

EXTRA_RUN_FLAGS=""
if [[ "${1:-}" == "--vcd" ]]; then
    EXTRA_RUN_FLAGS="--vcd=tb_stream_conv3x3_3chan_32out_cell_dsp.vcd"
    echo "Waveform: tb_stream_conv3x3_3chan_32out_cell_dsp.vcd  (open with GTKWave)"
elif [[ "${1:-}" == "--wave" ]]; then
    EXTRA_RUN_FLAGS="--wave=tb_stream_conv3x3_3chan_32out_cell_dsp.ghw"
    echo "Waveform: tb_stream_conv3x3_3chan_32out_cell_dsp.ghw"
fi

echo "=== [1/3] Analyzing VHDL-2008 sources ==="
ghdl -a --std=08 window3x3_stream.vhd
echo "  OK  window3x3_stream.vhd"
ghdl -a --std=08 conv3x3_dot_pipelined_dsp.vhd
echo "  OK  conv3x3_dot_pipelined_dsp.vhd"
ghdl -a --std=08 first_layer_kernels0_to31_pkg.vhd
echo "  OK  first_layer_kernels0_to31_pkg.vhd"
ghdl -a --std=08 stream_conv3x3_3chan_32out_cell_dsp.vhd
echo "  OK  stream_conv3x3_3chan_32out_cell_dsp.vhd"
ghdl -a --std=08 tb_stream_conv3x3_3chan_32out_cell_dsp.vhd
echo "  OK  tb_stream_conv3x3_3chan_32out_cell_dsp.vhd"
echo ""

echo "=== [2/3] Elaborating tb_stream_conv3x3_3chan_32out_cell_dsp ==="
ghdl -e --std=08 tb_stream_conv3x3_3chan_32out_cell_dsp
echo "  OK"
echo ""

echo "=== [3/3] Running simulation (stop after 600 ns) ==="
# shellcheck disable=SC2086
ghdl -r --std=08 tb_stream_conv3x3_3chan_32out_cell_dsp \
    --stop-time=600ns \
    --assert-level=failure \
    ${EXTRA_RUN_FLAGS}

echo ""
echo "=== Simulation complete ==="
