#!/usr/bin/env bash
# run_ghdl_3chan_kernels0_to3.sh
# Simulate tb_stream_conv3x3_3chan_kernels0_to3 using GHDL.
#
# This testbench reuses ONE stream_conv3x3_3chan_cell instance to verify
# FOUR first-layer output channels (kernels 0, 1, 2, 3), reloading INT8
# weights from first_layer_kernels0_to3_pkg between kernel runs and
# checking each kernel's 9 expected INT32 outputs against Python golden
# vectors.
#
# Weight source:
#   models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
#   tensor key: enc1.block.0.weight, output channels 0-3
#   Generated by: scripts/export_first_layer_multi_kernel_vhdl_vectors.py
#
# Analyzes (dependency order):
#   window3x3_stream.vhd
#   conv3x3_dot_pipelined.vhd
#   stream_conv3x3_3chan_cell.vhd
#   first_layer_kernels0_to3_pkg.vhd
#   tb_stream_conv3x3_3chan_kernels0_to3.vhd
#
# Usage:
#   bash hardware/vhdl_conv3x3/run_ghdl_3chan_kernels0_to3.sh
#   bash hardware/vhdl_conv3x3/run_ghdl_3chan_kernels0_to3.sh --vcd
#   bash hardware/vhdl_conv3x3/run_ghdl_3chan_kernels0_to3.sh --wave
#
# Expected output:
#   PASS kernel 0 output 1: y = 11287
#   ...
#   === Kernel 0 : all 9 outputs PASSED ===
#   PASS kernel 1 output 1: y = 9214
#   ...
#   === Kernel 3 : all 9 outputs PASSED ===
#   === All stream_conv3x3_3chan_kernels0_to3 tests PASSED === (4 kernels x 9 / 9 outputs match Python golden vectors)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if ! command -v ghdl &>/dev/null; then
    echo ""
    echo "ERROR: GHDL not found in PATH."
    echo ""
    echo "Install GHDL:"
    echo "  Ubuntu/Debian : sudo apt install ghdl"
    echo "  Fedora/RHEL   : sudo dnf install ghdl"
    echo "  macOS (brew)  : brew install ghdl"
    echo "  Releases      : https://github.com/ghdl/ghdl/releases"
    echo ""
    echo "Alternatively, use Vivado xsim:"
    echo "  xvhdl --2008 window3x3_stream.vhd conv3x3_dot_pipelined.vhd \\"
    echo "               stream_conv3x3_3chan_cell.vhd first_layer_kernels0_to3_pkg.vhd \\"
    echo "               tb_stream_conv3x3_3chan_kernels0_to3.vhd"
    echo "  xelab -debug typical tb_stream_conv3x3_3chan_kernels0_to3 -s tb_k03_sim"
    echo "  xsim  tb_k03_sim --runall"
    echo ""
    exit 1
fi

echo "Using: $(ghdl --version | head -1)"
echo ""

EXTRA_RUN_FLAGS=""
if [[ "${1:-}" == "--vcd" ]]; then
    EXTRA_RUN_FLAGS="--vcd=tb_stream_conv3x3_3chan_kernels0_to3.vcd"
    echo "Waveform: tb_stream_conv3x3_3chan_kernels0_to3.vcd  (open with GTKWave)"
elif [[ "${1:-}" == "--wave" ]]; then
    EXTRA_RUN_FLAGS="--wave=tb_stream_conv3x3_3chan_kernels0_to3.ghw"
    echo "Waveform: tb_stream_conv3x3_3chan_kernels0_to3.ghw"
fi

echo "=== [1/3] Analyzing VHDL-2008 sources ==="
ghdl -a --std=08 window3x3_stream.vhd
echo "  OK  window3x3_stream.vhd"
ghdl -a --std=08 conv3x3_dot_pipelined.vhd
echo "  OK  conv3x3_dot_pipelined.vhd"
ghdl -a --std=08 stream_conv3x3_3chan_cell.vhd
echo "  OK  stream_conv3x3_3chan_cell.vhd"
ghdl -a --std=08 first_layer_kernels0_to3_pkg.vhd
echo "  OK  first_layer_kernels0_to3_pkg.vhd"
ghdl -a --std=08 tb_stream_conv3x3_3chan_kernels0_to3.vhd
echo "  OK  tb_stream_conv3x3_3chan_kernels0_to3.vhd"
echo ""

echo "=== [2/3] Elaborating tb_stream_conv3x3_3chan_kernels0_to3 ==="
ghdl -e --std=08 tb_stream_conv3x3_3chan_kernels0_to3
echo "  OK"
echo ""

echo "=== [3/3] Running simulation (stop after 2000 ns) ==="
# shellcheck disable=SC2086
ghdl -r --std=08 tb_stream_conv3x3_3chan_kernels0_to3 \
    --stop-time=2000ns \
    --assert-level=failure \
    ${EXTRA_RUN_FLAGS}

echo ""
echo "=== Simulation complete ==="
