-- stream_conv3x3_3chan_kernel0_bn_relu_pipelined_relu_clamp.vhd
-- *** SYNTHETIC RELU CLAMP UNIT TEST -- NOT a real UAVSAR tile, NOT real model inference. ***
--
-- ReLU-clamp (negative-branch) unit test for the pipelined kernel-0
-- folded Conv-BN-ReLU proof-of-concept.
--
-- hardware/vhdl_conv3x3/stream_conv3x3_3chan_kernel0_bn_relu_pipelined.vhd
-- and hardware/vhdl_conv3x3/stream_conv3x3_3chan_kernel2_bn_relu_pipelined.vhd
-- were both verified against the canonical 5x5x3 TOY input, where every one
-- of the 9 biased_fx values happened to already be positive -- so
-- relu_fx == biased_fx for every output in both prior tests, and the ReLU
-- clamp (negative) branch was never numerically exercised. This module is
-- STRUCTURALLY IDENTICAL to those two designs (same reused, unmodified
-- stream_conv3x3_3chan_cell sub-component, same two-stage pipeline, same
-- Q.16 fixed-point arithmetic, same 48-bit datapath) -- it uses kernel 0's
-- SAME folded INT8 weights and SAME SCALE_FX/BIAS_FX constants, but is fed
-- a SYNTHETIC ALL-ZERO input patch (via
-- first_conv_bn_relu_kernel0_relu_clamp_pkg, generated by
-- scripts/generate_bn_relu_fixed_point_vectors.py --kernel-id 0
-- --input-mode synthetic_relu_clamp) that deterministically forces
-- raw_conv_int32 = 0 for every output position, so biased_fx = BIAS_FX =
-- -936 < 0 for all 9 positions -- exercising the ReLU clamp branch for
-- every single output.
--
-- This is a targeted unit test of ReLU behavior, NOT a representation of
-- any real UAVSAR tile or real model inference example.
--
-- ---- Architecture (identical structure to the kernel0/kernel2 pipelined designs) --
--   stream_conv3x3_3chan_cell (existing, unmodified, kernel-0 folded
--     INT8 weights, bias=0)          -> raw_y (INT32), 4-cycle latency
--   Stage 1 (registered): product_fx_r  <= raw_y * SCALE_FX   (Q.16, exact)
--   Stage 2 (registered): biased_fx     = product_fx_r + BIAS_FX (Q.16)
--                          y_bn_relu_fx_r <= biased_fx if biased_fx > 0
--                                            else 0                 (ReLU)
--
-- ---- Fixed-point format -------------------------------------------------
-- Q.16 (signed, 16 fractional bits), SAME SCALE_FX=135 and BIAS_FX=-936 as
-- kernel 0's other tests -- only the INPUT changes here, not the
-- arithmetic, weights, or constants.
--
-- ---- Latency ------------------------------------------------------------
-- 6 clock cycles total, IDENTICAL to the kernel0/kernel2 pipelined
-- designs (4 from stream_conv3x3_3chan_cell + 2 for the pipelined
-- multiply / bias-add+ReLU stages).
--
-- ---- Scope ----------------------------------------------------------------
-- Kernel 0 ONLY, SYNTHETIC input ONLY. Not all 32 output channels, not a
-- real UAVSAR tile, no downstream layers, no full model pipeline. Not
-- board-tested, not a measured-speedup or measured-power claim.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.first_conv_bn_relu_kernel0_relu_clamp_pkg.all;

entity stream_conv3x3_3chan_kernel0_bn_relu_pipelined_relu_clamp is
    generic (
        IMG_WIDTH : positive := 5
    );
    port (
        clk      : in  std_logic;
        rst      : in  std_logic;        -- synchronous, active high
        valid_in : in  std_logic;

        -- Three input-channel pixel streams (row-major, one triplet per clock)
        pixel_c0 : in signed(7 downto 0);
        pixel_c1 : in signed(7 downto 0);
        pixel_c2 : in signed(7 downto 0);

        -- Output: one Q.16 fixed-point result per valid window triplet,
        -- ReLU already applied, 6-cycle latency.
        valid_out    : out std_logic;
        y_bn_relu_fx : out signed(47 downto 0)
    );
end entity stream_conv3x3_3chan_kernel0_bn_relu_pipelined_relu_clamp;

architecture rtl of stream_conv3x3_3chan_kernel0_bn_relu_pipelined_relu_clamp is

    constant ZERO32 : signed(31 downto 0) := (others => '0');

    -- Fixed-point constants from the package -- SAME as the kernel0
    -- pipelined design (SCALE_FX=135, BIAS_FX=-936); only the testbench's
    -- input stimulus differs.
    constant SCALE_FX_SIGNED : signed(17 downto 0) := to_signed(SCALE_FX, 18);
    constant BIAS_FX_SIGNED  : signed(47 downto 0) := to_signed(BIAS_FX, 48);

    -- Raw INT32 convolution output from the reused, unmodified 1-output cell
    signal raw_y     : signed(31 downto 0);
    signal raw_valid : std_logic;

    -- ---- Stage 1: registered multiply ----
    signal product_fx_r : signed(47 downto 0) := (others => '0');
    signal valid_s1_r    : std_logic           := '0';

    -- ---- Stage 2: registered bias-add + ReLU ----
    signal biased_fx_comb : signed(47 downto 0);   -- combinational, within stage 2 only
    signal y_bn_relu_fx_r : signed(47 downto 0) := (others => '0');
    signal valid_s2_r      : std_logic           := '0';

begin

    -- ================================================================
    -- Raw convolution: EXISTING, UNMODIFIED stream_conv3x3_3chan_cell,
    -- fed kernel 0's FOLDED INT8 weights with bias=0 -- IDENTICAL
    -- weights to the kernel0 pipelined design's instantiation. The
    -- testbench drives an all-zero synthetic pixel stream, not the
    -- canonical toy patch.
    -- ================================================================
    raw_conv : entity work.stream_conv3x3_3chan_cell
        generic map (IMG_WIDTH => IMG_WIDTH)
        port map (
            clk => clk,  rst => rst,  valid_in => valid_in,
            pixel_c0 => pixel_c0,  pixel_c1 => pixel_c1,  pixel_c2 => pixel_c2,
            c0_w0 => to_signed(K0_FOLDED_CH0_W(0), 8),
            c0_w1 => to_signed(K0_FOLDED_CH0_W(1), 8),
            c0_w2 => to_signed(K0_FOLDED_CH0_W(2), 8),
            c0_w3 => to_signed(K0_FOLDED_CH0_W(3), 8),
            c0_w4 => to_signed(K0_FOLDED_CH0_W(4), 8),
            c0_w5 => to_signed(K0_FOLDED_CH0_W(5), 8),
            c0_w6 => to_signed(K0_FOLDED_CH0_W(6), 8),
            c0_w7 => to_signed(K0_FOLDED_CH0_W(7), 8),
            c0_w8 => to_signed(K0_FOLDED_CH0_W(8), 8),
            c1_w0 => to_signed(K0_FOLDED_CH1_W(0), 8),
            c1_w1 => to_signed(K0_FOLDED_CH1_W(1), 8),
            c1_w2 => to_signed(K0_FOLDED_CH1_W(2), 8),
            c1_w3 => to_signed(K0_FOLDED_CH1_W(3), 8),
            c1_w4 => to_signed(K0_FOLDED_CH1_W(4), 8),
            c1_w5 => to_signed(K0_FOLDED_CH1_W(5), 8),
            c1_w6 => to_signed(K0_FOLDED_CH1_W(6), 8),
            c1_w7 => to_signed(K0_FOLDED_CH1_W(7), 8),
            c1_w8 => to_signed(K0_FOLDED_CH1_W(8), 8),
            c2_w0 => to_signed(K0_FOLDED_CH2_W(0), 8),
            c2_w1 => to_signed(K0_FOLDED_CH2_W(1), 8),
            c2_w2 => to_signed(K0_FOLDED_CH2_W(2), 8),
            c2_w3 => to_signed(K0_FOLDED_CH2_W(3), 8),
            c2_w4 => to_signed(K0_FOLDED_CH2_W(4), 8),
            c2_w5 => to_signed(K0_FOLDED_CH2_W(5), 8),
            c2_w6 => to_signed(K0_FOLDED_CH2_W(6), 8),
            c2_w7 => to_signed(K0_FOLDED_CH2_W(7), 8),
            c2_w8 => to_signed(K0_FOLDED_CH2_W(8), 8),
            bias      => ZERO32,
            valid_out => raw_valid,
            y         => raw_y
        );

    -- ================================================================
    -- Stage 1 (registered): product_fx = raw_y * SCALE_FX
    -- ================================================================
    stage1_multiply : process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                product_fx_r <= (others => '0');
                valid_s1_r    <= '0';
            else
                product_fx_r <= resize(raw_y * SCALE_FX_SIGNED, 48);
                valid_s1_r    <= raw_valid;
            end if;
        end if;
    end process stage1_multiply;

    -- ================================================================
    -- Stage 2 (registered): biased_fx = product_fx_r + BIAS_FX, then
    -- ReLU clamp. For this synthetic all-zero-input test, product_fx_r
    -- is 0 for every position, so biased_fx_comb = BIAS_FX_SIGNED = -936
    -- (< 0) for every position -- this is the branch under test.
    -- ================================================================
    biased_fx_comb <= product_fx_r + BIAS_FX_SIGNED;

    stage2_bias_relu : process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                y_bn_relu_fx_r <= (others => '0');
                valid_s2_r      <= '0';
            else
                if biased_fx_comb > 0 then
                    y_bn_relu_fx_r <= biased_fx_comb;
                else
                    y_bn_relu_fx_r <= (others => '0');
                end if;
                valid_s2_r <= valid_s1_r;
            end if;
        end if;
    end process stage2_bias_relu;

    valid_out    <= valid_s2_r;
    y_bn_relu_fx <= y_bn_relu_fx_r;

end architecture rtl;
