-- stream_conv3x3_3chan_kernel0_bn_relu.vhd
-- Kernel-0 folded Conv -> BatchNorm bias/scale -> ReLU proof-of-concept.
--
-- This is NOT a new convolution architecture. It reuses the existing,
-- verified, UNMODIFIED stream_conv3x3_3chan_cell.vhd (the original
-- 1-output raw-convolution prototype) as a black-box sub-component,
-- feeding it kernel 0's FOLDED (BatchNorm-absorbed) INT8 weights instead
-- of the raw unfolded weights, with bias=0 (as in every prior VHDL
-- prototype in this repo -- Conv2d itself has no direct bias). A new
-- fixed-point stage is added AFTER that sub-component's raw INT32 output
-- to apply the folded scale + folded bias + ReLU, entirely in Q.16
-- fixed-point integer arithmetic (no floating point in hardware).
--
-- Motivation: hardware/vhdl_conv3x3/first_conv_bn_relu_fidelity_summary.md
-- (a Python-only numerical study) showed that folding BatchNorm into the
-- Conv2d weights/bias is exact in float and remains close after INT8-style
-- quantization, for the full 32-channel first Conv-BN-ReLU stage. That
-- study explicitly noted NO VHDL implements BatchNorm/bias/ReLU. This
-- module is the first VHDL proof-of-concept closing that gap, for kernel 0
-- only, using genuine fixed-point (not float-rescaled) arithmetic.
--
-- ---- Architecture -----------------------------------------------------
--   stream_conv3x3_3chan_cell (existing, unmodified, kernel-0 folded
--     INT8 weights, bias=0)          -> raw_y (INT32), 4-cycle latency
--   bn_relu_stage (1 registered stage):
--     product_fx = raw_y * SCALE_FX                (Q.16, exact, no shift)
--     biased_fx  = product_fx + BIAS_FX             (Q.16, exact, no shift)
--     y_bn_relu_fx = biased_fx if biased_fx > 0 else 0   (ReLU, Q.16)
--
-- ---- Fixed-point format -------------------------------------------------
-- Q.16 (signed, 16 fractional bits): real_value ~= fixed_value / 2^16.
-- SCALE_FX and BIAS_FX are compile-time constants from
-- first_conv_bn_relu_kernel0_pkg (generated by
-- scripts/generate_kernel0_bn_relu_fixed_point_vectors.py). Because raw_y
-- has 0 fractional bits (exact integer) and SCALE_FX has 16 fractional
-- bits, their product is automatically in Q.16 format with NO shift
-- required; BIAS_FX is generated directly in the same Q.16 format, so no
-- shift is needed to add it either -- this datapath contains only one
-- multiply, one add, and one compare-and-select, no runtime shifts.
--
-- ---- Latency ------------------------------------------------------------
-- 5 clock cycles total: 4 cycles from stream_conv3x3_3chan_cell (unchanged)
-- + 1 cycle for the new BN+ReLU stage.
--
-- ---- Scope ----------------------------------------------------------------
-- Kernel 0 ONLY (not all 32 output channels). Canonical 5x5x3 toy input,
-- valid (no-padding) 3x3 output region only -- same as every other VHDL
-- prototype in this repo. No pooling, no downstream layers, no full model
-- pipeline. Not board-tested, not a measured-speedup or measured-power
-- claim.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.first_conv_bn_relu_kernel0_pkg.all;

entity stream_conv3x3_3chan_kernel0_bn_relu is
    generic (
        IMG_WIDTH : positive := 5
    );
    port (
        clk      : in  std_logic;
        rst      : in  std_logic;        -- synchronous, active high
        valid_in : in  std_logic;

        -- Three input-channel pixel streams (row-major, one triplet per clock)
        pixel_c0 : in signed(7 downto 0);
        pixel_c1 : in signed(7 downto 0);
        pixel_c2 : in signed(7 downto 0);

        -- Output: one Q.16 fixed-point result per valid window triplet,
        -- ReLU already applied, 5-cycle latency.
        valid_out    : out std_logic;
        y_bn_relu_fx : out signed(47 downto 0)
    );
end entity stream_conv3x3_3chan_kernel0_bn_relu;

architecture rtl of stream_conv3x3_3chan_kernel0_bn_relu is

    constant ZERO32 : signed(31 downto 0) := (others => '0');

    -- Fixed-point constants from the package, widened to fixed VHDL widths.
    -- SCALE_FX is small and always non-negative by construction (a folded
    -- weight quantization scale); 18 bits gives generous headroom.
    constant SCALE_FX_SIGNED : signed(17 downto 0) := to_signed(SCALE_FX, 18);
    constant BIAS_FX_SIGNED  : signed(47 downto 0) := to_signed(BIAS_FX, 48);

    -- Raw INT32 convolution output from the reused, unmodified 1-output cell
    signal raw_y     : signed(31 downto 0);
    signal raw_valid : std_logic;

    -- Registered BN+ReLU stage output
    signal biased_fx_r : signed(47 downto 0) := (others => '0');
    signal valid_bn_r  : std_logic            := '0';

    -- Combinational product/bias-add, registered at the end of the process
    signal biased_fx_comb : signed(47 downto 0);

begin

    -- ================================================================
    -- Raw convolution: EXISTING, UNMODIFIED stream_conv3x3_3chan_cell,
    -- fed kernel 0's FOLDED INT8 weights (not the raw unfolded weights
    -- used elsewhere in this repo) with bias=0.
    -- ================================================================
    raw_conv : entity work.stream_conv3x3_3chan_cell
        generic map (IMG_WIDTH => IMG_WIDTH)
        port map (
            clk => clk,  rst => rst,  valid_in => valid_in,
            pixel_c0 => pixel_c0,  pixel_c1 => pixel_c1,  pixel_c2 => pixel_c2,
            c0_w0 => to_signed(K0_FOLDED_CH0_W(0), 8),
            c0_w1 => to_signed(K0_FOLDED_CH0_W(1), 8),
            c0_w2 => to_signed(K0_FOLDED_CH0_W(2), 8),
            c0_w3 => to_signed(K0_FOLDED_CH0_W(3), 8),
            c0_w4 => to_signed(K0_FOLDED_CH0_W(4), 8),
            c0_w5 => to_signed(K0_FOLDED_CH0_W(5), 8),
            c0_w6 => to_signed(K0_FOLDED_CH0_W(6), 8),
            c0_w7 => to_signed(K0_FOLDED_CH0_W(7), 8),
            c0_w8 => to_signed(K0_FOLDED_CH0_W(8), 8),
            c1_w0 => to_signed(K0_FOLDED_CH1_W(0), 8),
            c1_w1 => to_signed(K0_FOLDED_CH1_W(1), 8),
            c1_w2 => to_signed(K0_FOLDED_CH1_W(2), 8),
            c1_w3 => to_signed(K0_FOLDED_CH1_W(3), 8),
            c1_w4 => to_signed(K0_FOLDED_CH1_W(4), 8),
            c1_w5 => to_signed(K0_FOLDED_CH1_W(5), 8),
            c1_w6 => to_signed(K0_FOLDED_CH1_W(6), 8),
            c1_w7 => to_signed(K0_FOLDED_CH1_W(7), 8),
            c1_w8 => to_signed(K0_FOLDED_CH1_W(8), 8),
            c2_w0 => to_signed(K0_FOLDED_CH2_W(0), 8),
            c2_w1 => to_signed(K0_FOLDED_CH2_W(1), 8),
            c2_w2 => to_signed(K0_FOLDED_CH2_W(2), 8),
            c2_w3 => to_signed(K0_FOLDED_CH2_W(3), 8),
            c2_w4 => to_signed(K0_FOLDED_CH2_W(4), 8),
            c2_w5 => to_signed(K0_FOLDED_CH2_W(5), 8),
            c2_w6 => to_signed(K0_FOLDED_CH2_W(6), 8),
            c2_w7 => to_signed(K0_FOLDED_CH2_W(7), 8),
            c2_w8 => to_signed(K0_FOLDED_CH2_W(8), 8),
            bias      => ZERO32,
            valid_out => raw_valid,
            y         => raw_y
        );

    -- ================================================================
    -- Fixed-point folded scale + folded bias + ReLU, one registered stage.
    -- product_fx = raw_y * SCALE_FX  -- exact, already Q.16 (raw_y is Q.0)
    -- biased_fx  = product_fx + BIAS_FX  -- exact, Q.16 (same format)
    -- ReLU: clamp negative results to zero.
    -- ================================================================
    biased_fx_comb <= resize(raw_y * SCALE_FX_SIGNED, 48) + BIAS_FX_SIGNED;

    bn_relu_stage : process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                biased_fx_r <= (others => '0');
                valid_bn_r  <= '0';
            else
                if biased_fx_comb > 0 then
                    biased_fx_r <= biased_fx_comb;
                else
                    biased_fx_r <= (others => '0');
                end if;
                valid_bn_r <= raw_valid;
            end if;
        end if;
    end process bn_relu_stage;

    valid_out    <= valid_bn_r;
    y_bn_relu_fx <= biased_fx_r;

end architecture rtl;
