-- tb_first_layer_32out_folded_arithmetic_core_vectors_pkg.vhd
-- Golden test-vector stimulus/expected constants for
-- tb_first_layer_32out_folded_arithmetic_core.vhd.
--
-- Generated by: scripts/generate_first_layer_32out_folded_arithmetic_core_vectors.py
-- Source vectors: hardware/vhdl_conv3x3/test_vectors/
--                 first_layer_32out_folded_arithmetic_core/first_layer_32out_folded_arithmetic_core_vectors.json
--
-- 5 flattened 27-value test windows (channel-major, then
-- row-major within the 3x3 window -- window[0..8]=channel0, window[9..17]=
-- channel1, window[18..26]=channel2):
--   window 0: real_window_0
--   window 1: all_zero
--   window 2: all_max_pos
--   window 3: all_max_neg
--   window 4: checkerboard
--
-- Window 0 (real_window_0) is a genuine 3x3x3 window sliced from the
-- EXISTING real_tile_stimulus_pkg.vhd's real UAVSAR-tile-derived 6x6
-- block (top-left valid window). Its expected 32-output vector was
-- CROSS-CHECKED by the generator script against the existing, already
-- GHDL-verified first_conv_bn_relu_kernel{0..31}_real_tile_q20_pkg.vhd's
-- K{k}_RT_BN_RELU_EXPECTED_FX(0) constants for all 32 kernels, and matches
-- exactly. Windows 1-4 are synthetic edge cases (all-zero, max-positive,
-- max-negative, checkerboard) computed directly from
-- first_layer_32out_folded_bn_relu_real_tile_q20_pkg's weight/scale/bias
-- LUTs.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package tb_first_layer_32out_folded_arithmetic_core_vectors_pkg is

    constant NUM_TEST_WINDOWS : integer := 5;
    constant NUM_KERNELS      : integer := 32;

    type window27_t     is array (0 to 26) of integer range -128 to 127;
    type windows_lut_t  is array (0 to NUM_TEST_WINDOWS - 1) of window27_t;
    type y32_t           is array (0 to NUM_KERNELS - 1) of integer;
    type expected_lut_t is array (0 to NUM_TEST_WINDOWS - 1) of y32_t;

    constant TEST_WINDOWS : windows_lut_t := (
        (27, -59, -69, 49, -56, -39, 79, 20, -72, 37, -16, -39, 35, -24, -39, 90, 34, -50, 17, -58, -84, 10, -59, -60, 93, 48, -78),
        (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
        (127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127),
        (-128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128),
        (100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100, -100, 100)
    );

    -- Q.20 fixed-point expected outputs (ReLU already applied), one 32-wide
    -- row per test window, in the same order as TEST_WINDOWS above.
    constant EXPECTED_Y : expected_lut_t := (
        (0, 62052, 2857507, 169535, 0, 802297, 1808305, 0, 1479922, 745449, 143179, 0, 566006, 0, 200698, 1142268, 3447099, 649895, 0, 0, 0, 1851075, 590246, 564650, 458663, 982241, 0, 0, 1549951, 2909510, 1364384, 0),
        (0, 0, 0, 0, 19398, 2953, 41960, 22770, 0, 0, 9601, 0, 0, 42166, 0, 13272, 0, 0, 0, 0, 6437, 0, 0, 11650, 15463, 20081, 0, 0, 0, 11510, 0, 9895),
        (2387236, 2057010, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1836761, 0, 0, 1195538, 0, 984751, 0, 2329196, 1345781, 2193250, 0, 0, 0, 1974311, 2647457, 0, 1590891, 0, 0, 1742099, 0),
        (0, 0, 852452, 2736255, 2685894, 88969, 725608, 312818, 1578564, 2314158, 2575873, 0, 2859086, 515254, 0, 2609624, 0, 1452199, 0, 0, 0, 2249538, 2374042, 2860930, 0, 0, 1417733, 0, 2357353, 1338614, 0, 883495),
        (0, 0, 6941628, 0, 1544598, 0, 3606260, 1650170, 0, 0, 1948901, 2700633, 485006, 3788566, 2172290, 0, 0, 0, 1088018, 0, 0, 818478, 0, 580050, 47463, 3922481, 1052005, 0, 0, 1653110, 0, 0)
    );

end package tb_first_layer_32out_folded_arithmetic_core_vectors_pkg;
