-- tb_stream_conv3x3_3chan_4out_bn_relu_time_mux.vhd
-- Self-checking testbench for stream_conv3x3_3chan_4out_bn_relu_time_mux.
--
-- This is a RESOURCE-SHARED (time-multiplexed) folded Conv-BN-ReLU
-- PROTOTYPE testbench, not full U-Net inference and not a board demo. It
-- streams the canonical 5x5x3 toy image into the DUT exactly as
-- tb_stream_conv3x3_3chan_8out_time_mux.vhd streams it into the raw
-- 8-output time-mux design, then waits (with no back-pressure or overlap)
-- for the DUT's internal one-window scheduler to sequentially process all
-- 9 buffered windows, checking each window's 4 kernel outputs (Q.16
-- fixed-point, folded BatchNorm + ReLU applied) as they appear.
--
-- ---- Input patch --------------------------------------------------------
-- Canonical 5x5x3 toy patch matching every other testbench in this directory:
--   Channel 0: 1..25 row-major
--   Channel 1: 2 x channel 0  (2..50)
--   Channel 2: -1 x channel 0  (-1..-25)
--
-- ---- Expected outputs -----------------------------------------------------
-- Golden vectors sourced from first_layer_4out_bn_relu_resource_shared_pkg's
-- EXPECTED_RELU_FX array (generated by
-- scripts/generate_resource_shared_32out_bn_relu_vectors.py --num-kernels 4),
-- WINDOW-MAJOR / KERNEL-MINOR order: index = window_idx*4 + kernel_idx.
--
-- ---- Timing behavior (two non-overlapped phases) -------------------------
-- Phase 1 (capture): pixels stream in at 1/clock for ~25 clocks. No
-- valid_out pulses occur during this phase.
-- Phase 2 (process): the DUT's internal scheduler processes the 9
-- buffered windows ONE AT A TIME (no overlap). This testbench does NOT
-- assert an exact precomputed total cycle count -- it MEASURES and
-- reports the actual total directly, with only a generous safety bound
-- to catch a runaway FSM (same convention as
-- tb_stream_conv3x3_3chan_8out_time_mux.vhd).
--
-- ---- What this validates -----------------------------------------------
-- This testbench confirms that stream_conv3x3_3chan_4out_bn_relu_time_mux,
-- built by wrapping the UNMODIFIED window3x3_stream generators and a NEW
-- resource-shared conv3x3_3chan_4out_bn_relu_time_mux scheduler (which
-- itself reuses the UNMODIFIED conv3x3_dot_time_mux engine) in the SAME
-- two-phase capture-then-process FSM pattern already verified for the raw
-- 8-output time-mux design, reproduces the same 9x4=36 Q.16 fixed-point
-- values the Python golden generator computes for kernels 0-3's folded
-- Conv-BN-ReLU stage. It does NOT validate full quantized U-Net inference,
-- does NOT cover the remaining 28 of 32 first-layer output channels, does
-- NOT overlap window capture with compute, and has NOT been run on real
-- FPGA hardware.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.first_layer_4out_bn_relu_resource_shared_pkg.all;

entity tb_stream_conv3x3_3chan_4out_bn_relu_time_mux is
end entity tb_stream_conv3x3_3chan_4out_bn_relu_time_mux;

architecture sim of tb_stream_conv3x3_3chan_4out_bn_relu_time_mux is

    constant CLK_PERIOD : time     := 10 ns;
    constant IMG_W      : positive := 5;

    -- Generous sanity bound only, NOT an asserted exact cycle count: ~25
    -- cycles to stream the image + 9 windows x (up to ~400 cycles each,
    -- padded above the 12-dot-op + 4x2-cycle-BN+ReLU estimate) to catch a
    -- genuinely runaway FSM, not to pin an exact timing model.
    constant MAX_CYCLES : integer := 25 + NUM_WINDOWS * 400;

    signal clk      : std_logic := '0';
    signal rst      : std_logic := '1';
    signal valid_in : std_logic := '0';

    signal pixel_c0 : signed(7 downto 0) := (others => '0');
    signal pixel_c1 : signed(7 downto 0) := (others => '0');
    signal pixel_c2 : signed(7 downto 0) := (others => '0');

    signal valid_out : std_logic;
    signal all_done  : std_logic;
    signal s_y0, s_y1, s_y2, s_y3 : signed(47 downto 0);

begin

    clk <= not clk after CLK_PERIOD / 2;

    dut : entity work.stream_conv3x3_3chan_4out_bn_relu_time_mux
        generic map (IMG_WIDTH => IMG_W)
        port map (
            clk      => clk,
            rst      => rst,
            valid_in => valid_in,
            pixel_c0 => pixel_c0,
            pixel_c1 => pixel_c1,
            pixel_c2 => pixel_c2,
            valid_out => valid_out,
            y0 => s_y0, y1 => s_y1, y2 => s_y2, y3 => s_y3,
            all_done => all_done
        );

    stim : process

        variable out_count    : integer := 0;   -- window count (0..8)
        variable total_cycles : integer := 0;
        variable all_done_seen_at : integer := -1;

        procedure check_output(window_num : integer) is
            -- window_num is 1-based window count; convert to 0-based
            -- window index for the WINDOW-MAJOR/KERNEL-MINOR golden array.
            variable widx : integer := window_num - 1;
            variable base : integer := widx * NUM_KERNELS;
        begin
            assert to_integer(s_y0) = EXPECTED_RELU_FX(base + 0)
                report "FAIL window " & integer'image(window_num) & " kernel 0: y0 = " &
                       integer'image(to_integer(s_y0)) & "  expected " &
                       integer'image(EXPECTED_RELU_FX(base + 0))
                severity failure;
            assert to_integer(s_y1) = EXPECTED_RELU_FX(base + 1)
                report "FAIL window " & integer'image(window_num) & " kernel 1: y1 = " &
                       integer'image(to_integer(s_y1)) & "  expected " &
                       integer'image(EXPECTED_RELU_FX(base + 1))
                severity failure;
            assert to_integer(s_y2) = EXPECTED_RELU_FX(base + 2)
                report "FAIL window " & integer'image(window_num) & " kernel 2: y2 = " &
                       integer'image(to_integer(s_y2)) & "  expected " &
                       integer'image(EXPECTED_RELU_FX(base + 2))
                severity failure;
            assert to_integer(s_y3) = EXPECTED_RELU_FX(base + 3)
                report "FAIL window " & integer'image(window_num) & " kernel 3: y3 = " &
                       integer'image(to_integer(s_y3)) & "  expected " &
                       integer'image(EXPECTED_RELU_FX(base + 3))
                severity failure;

            report "PASS window " & integer'image(window_num) &
                   ": y0=" & integer'image(to_integer(s_y0)) &
                   " y1=" & integer'image(to_integer(s_y1)) &
                   " y2=" & integer'image(to_integer(s_y2)) &
                   " y3=" & integer'image(to_integer(s_y3)) &
                   " (@ cycle " & integer'image(total_cycles) & ")";
        end procedure check_output;

    begin
        -- ---- Reset (3 clocks) ----------------------------------------
        rst      <= '1';
        valid_in <= '0';
        pixel_c0 <= (others => '0');
        pixel_c1 <= (others => '0');
        pixel_c2 <= (others => '0');
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        rst  <= '0';
        wait until rising_edge(clk);
        wait for 1 ns;

        -- ---- PHASE 1: stream the 5x5 image (one pixel triplet/clock) ---
        valid_in <= '1';
        for i in 1 to 25 loop
            pixel_c0 <= to_signed(i,    8);
            pixel_c1 <= to_signed(2*i,  8);
            pixel_c2 <= to_signed(-i,   8);
            wait until rising_edge(clk);
            wait for 1 ns;
            total_cycles := total_cycles + 1;

            if valid_out = '1' then
                out_count := out_count + 1;
                check_output(out_count);
            end if;
        end loop;
        valid_in <= '0';

        -- ---- PHASE 2: wait for the DUT to sequentially process all 9 --
        -- buffered windows through its internal resource-shared scheduler.
        while out_count < NUM_WINDOWS loop
            assert total_cycles <= MAX_CYCLES
                report "FAIL: did not observe all " & integer'image(NUM_WINDOWS) &
                       " windows within " & integer'image(MAX_CYCLES) &
                       " cycles (runaway FSM?)"
                severity failure;

            wait until rising_edge(clk);
            wait for 1 ns;
            total_cycles := total_cycles + 1;

            if valid_out = '1' then
                out_count := out_count + 1;
                check_output(out_count);
            end if;

            if all_done = '1' then
                all_done_seen_at := out_count;
            end if;
        end loop;

        -- ---- Final checks --------------------------------------------
        assert out_count = NUM_WINDOWS
            report "FAIL: expected exactly " & integer'image(NUM_WINDOWS) &
                   " valid windows, observed " & integer'image(out_count)
            severity failure;

        assert all_done_seen_at = NUM_WINDOWS
            report "FAIL: all_done did not pulse on the same cycle as the " &
                   integer'image(NUM_WINDOWS) & "th window's valid_out " &
                   "(all_done seen at window count " & integer'image(all_done_seen_at) & ")"
            severity failure;

        report "Total cycles for streaming capture + sequential processing: " &
               integer'image(total_cycles) & " (measured, not asserted exact)";

        report "=== All stream_conv3x3_3chan_4out_bn_relu_time_mux tests PASSED ===" &
               "  (" & integer'image(NUM_WINDOWS) & " windows x " & integer'image(NUM_KERNELS) &
               " kernels = " & integer'image(NUM_WINDOWS * NUM_KERNELS) & " / " &
               integer'image(NUM_WINDOWS * NUM_KERNELS) &
               " outputs match Python Q.16 fixed-point golden vectors)" severity note;
        report "    NOTE: RESOURCE-SHARED (time-multiplexed) folded Conv-BN-ReLU PROTOTYPE," &
               " kernels 0-3 only (of 32). Not full U-Net inference, not board-tested," &
               " not a measured speedup/power claim, not a real UAVSAR inference example." severity note;

        wait;
    end process stim;

end architecture sim;
