-- tb_stream_conv3x3_3chan_8out_cell_dsp.vhd
-- Self-checking testbench for stream_conv3x3_3chan_8out_cell_dsp.
--
-- Identical stimulus and checks to tb_stream_conv3x3_3chan_8out_cell.vhd,
-- retargeted at the DSP-aware DUT. Since stream_conv3x3_3chan_8out_cell_dsp
-- is numerically and cycle-accurately identical to the LUT-only baseline
-- (only the multiply-to-DSP48E1 synthesis mapping differs, which has no
-- effect on RTL simulation), this testbench is expected to produce
-- bit-identical PASS results to the LUT-only baseline's testbench.
--
-- ---- Source of weights --------------------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight  (shape [32, 3, 3, 3])
-- Output chs : 0, 1, 2, 3, 4, 5, 6, 7 (baked into
--              stream_conv3x3_3chan_8out_cell_dsp via first_layer_kernels0_to7_pkg
--              -- not loaded via ports here)
--
-- ---- Input patch --------------------------------------------------------
-- Canonical 5x5x3 toy patch matching all prior testbenches in this directory:
--   Channel 0: 1..25 row-major
--   Channel 1: 2 x channel 0  (2..50)
--   Channel 2: -1 x channel 0  (-1..-25)
--
-- ---- Expected INT32 outputs (3x3 valid convolution, row-major) ----------
-- Golden vectors sourced from first_layer_kernels0_to7_pkg's
-- KERNEL{0..7}_EXPECTED constants (generated by
-- scripts/export_first_layer_multi_kernel_vhdl_vectors.py 0-7).
--
-- ---- Timing (4-cycle cell latency, single pass) --------------------------
--   Outputs 1-3: main loop i=17, 18, 19
--   Outputs 4-6: main loop i=22, 23, 24
--   Outputs 7-9: drain d=2, d=3, d=4  (4-clock drain; d=1 is empty)
-- One pass over the image: y0..y7 all become valid together on every
-- valid_out pulse, so all eight kernels are checked per output position.
--
-- ---- What this validates -----------------------------------------------
-- This testbench confirms that stream_conv3x3_3chan_8out_cell_dsp produces,
-- in ONE streaming pass, the same 9x8=72 INT32 values that the Python
-- golden-vector script produces for kernels 0-7 -- i.e. that swapping in the
-- DSP-steered dot-product module did not change simulated behavior. It does
-- NOT validate full quantized U-Net inference (BatchNorm is not applied),
-- does NOT cover the remaining 24 of 32 first-layer output channels, and has
-- NOT been run on real FPGA hardware -- this is a simulation-only functional
-- check of the DSP-aware 8-output prototype.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.first_layer_kernels0_to7_pkg.all;

entity tb_stream_conv3x3_3chan_8out_cell_dsp is
end entity tb_stream_conv3x3_3chan_8out_cell_dsp;

architecture sim of tb_stream_conv3x3_3chan_8out_cell_dsp is

    constant CLK_PERIOD : time     := 10 ns;
    constant IMG_W      : positive := 5;

    -- Testbench-driven signals
    signal clk      : std_logic := '0';
    signal rst      : std_logic := '1';
    signal valid_in : std_logic := '0';

    signal pixel_c0 : signed(7 downto 0) := (others => '0');
    signal pixel_c1 : signed(7 downto 0) := (others => '0');
    signal pixel_c2 : signed(7 downto 0) := (others => '0');

    -- DUT outputs
    signal valid_out : std_logic;
    signal s_y0, s_y1, s_y2, s_y3, s_y4, s_y5, s_y6, s_y7 : signed(31 downto 0);

begin

    -- ----------------------------------------------------------------
    -- Free-running clock
    -- ----------------------------------------------------------------
    clk <= not clk after CLK_PERIOD / 2;

    -- ----------------------------------------------------------------
    -- DUT: stream_conv3x3_3chan_8out_cell_dsp
    -- ----------------------------------------------------------------
    dut : entity work.stream_conv3x3_3chan_8out_cell_dsp
        generic map (IMG_WIDTH => IMG_W)
        port map (
            clk      => clk,
            rst      => rst,
            valid_in => valid_in,
            pixel_c0 => pixel_c0,
            pixel_c1 => pixel_c1,
            pixel_c2 => pixel_c2,
            valid_out => valid_out,
            y0 => s_y0,
            y1 => s_y1,
            y2 => s_y2,
            y3 => s_y3,
            y4 => s_y4,
            y5 => s_y5,
            y6 => s_y6,
            y7 => s_y7
        );

    -- ----------------------------------------------------------------
    -- Stimulus and self-checking
    -- ----------------------------------------------------------------
    stim : process

        variable out_count : integer := 0;

        procedure check_one(kernel_id : integer; got : signed(31 downto 0);
                             expected : int32_outputs_t; out_num : integer) is
        begin
            assert to_integer(got) = expected(out_num - 1)
                report "FAIL output " & integer'image(out_num) &
                       " kernel " & integer'image(kernel_id) &
                       ": y = " & integer'image(to_integer(got)) &
                       "  expected " & integer'image(expected(out_num - 1))
                severity failure;
        end procedure check_one;

        procedure check_output(out_num : integer) is
        begin
            check_one(0, s_y0, KERNEL0_EXPECTED, out_num);
            check_one(1, s_y1, KERNEL1_EXPECTED, out_num);
            check_one(2, s_y2, KERNEL2_EXPECTED, out_num);
            check_one(3, s_y3, KERNEL3_EXPECTED, out_num);
            check_one(4, s_y4, KERNEL4_EXPECTED, out_num);
            check_one(5, s_y5, KERNEL5_EXPECTED, out_num);
            check_one(6, s_y6, KERNEL6_EXPECTED, out_num);
            check_one(7, s_y7, KERNEL7_EXPECTED, out_num);

            report "PASS output " & integer'image(out_num) &
                   ": y0=" & integer'image(to_integer(s_y0)) &
                   " y1=" & integer'image(to_integer(s_y1)) &
                   " y2=" & integer'image(to_integer(s_y2)) &
                   " y3=" & integer'image(to_integer(s_y3)) &
                   " y4=" & integer'image(to_integer(s_y4)) &
                   " y5=" & integer'image(to_integer(s_y5)) &
                   " y6=" & integer'image(to_integer(s_y6)) &
                   " y7=" & integer'image(to_integer(s_y7));
        end procedure check_output;

    begin
        -- ---- Reset (3 clocks) ----------------------------------------
        rst      <= '1';
        valid_in <= '0';
        pixel_c0 <= (others => '0');
        pixel_c1 <= (others => '0');
        pixel_c2 <= (others => '0');
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        rst  <= '0';
        wait until rising_edge(clk);
        wait for 1 ns;

        -- ---- Stream 5x5 image (one pixel triplet per clock) ----------
        -- Channel 0: pixel i  (1..25)
        -- Channel 1: 2*i      (2..50, fits INT8)
        -- Channel 2: -i       (-1..-25, fits INT8)
        --
        -- 4-cycle cell latency (window gen + 3-stage dot product + final sum):
        --   first output visible at i=17.
        --
        -- Outputs during main loop: i=17,18,19 (windows 1-3)
        --                           i=22,23,24 (windows 4-6)
        -- i=25: no output (windows 7-9 still in pipeline)

        valid_in <= '1';
        for i in 1 to 25 loop
            pixel_c0 <= to_signed(i,    8);
            pixel_c1 <= to_signed(2*i,  8);
            pixel_c2 <= to_signed(-i,   8);
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out = '1' then
                out_count := out_count + 1;
                check_output(out_count);
            end if;
        end loop;

        -- ---- Drain: 4 clocks to flush windows 7, 8, 9 ---------------
        -- Windows 7-9 triggered by pixels 23, 24, 25 exit at
        -- drain clocks d=2, d=3, d=4.  d=1 is empty.

        valid_in <= '0';
        for d in 1 to 4 loop
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out = '1' then
                out_count := out_count + 1;
                check_output(out_count);
            end if;
        end loop;

        -- ---- Final checks --------------------------------------------
        assert out_count = 9
            report "FAIL: expected exactly 9 valid output positions, observed " &
                   integer'image(out_count)
            severity failure;

        report "=== All stream_conv3x3_3chan_8out_cell_dsp tests PASSED ===" &
               "  (9 positions x 8 kernels = 72 / 72 outputs match Python golden vectors)"
               severity note;
        report "    Kernels: enc1.block.0.weight channels 0-7 from" &
               " alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt" severity note;
        report "    NOTE: DSP-aware 8-output first-layer convolution PROTOTYPE only." &
               " Not full U-Net inference, not board-tested, BatchNorm not folded." severity note;

        wait;
    end process stim;

end architecture sim;
