-- tb_stream_conv3x3_3chan_first_layer_real_tile_bn_relu_q20.vhd
-- Self-checking testbench: REAL-TILE verification of the existing
-- kernel-0 and kernel-2 folded Conv-BN-ReLU pipelined VHDL prototypes.
--
-- This is a REAL-DATA VERIFICATION SUBSET (kernel 0 and kernel 2 of the
-- complete first Conv2d layer's 32 output channels), NOT full 32-output
-- real-tile verification and NOT a new hardware architecture. Both DUTs
-- (stream_conv3x3_3chan_kernel0_bn_relu_real_tile_q20 and
-- stream_conv3x3_3chan_kernel2_bn_relu_real_tile_q20) are structurally
-- IDENTICAL to the already-verified toy-patch pipelined designs
-- (stream_conv3x3_3chan_kernel{0,2}_bn_relu_pipelined) -- same
-- stream_conv3x3_3chan_cell sub-component, same two-stage Q.20
-- BatchNorm-fold + ReLU pipeline -- driven here with a REAL,
-- per-tile-normalized-and-quantized 6x6x3 UAVSAR patch
-- (real_tile_stimulus_pkg) instead of the synthetic 5x5x3 toy patch.
--
-- ---- Source of the real patch --------------------------------------------
-- Tile        : tile_16_42.tif (first row of heldout_fp2_test.csv)
-- Checkpoint  : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py
-- Normalization: FloodTileDataset._normalize_per_tile (train_unet_baseline_tuned.py)
-- Quantization : per-tile scale_x (analyze_first_layer_fixed_point_segmentation_impact.py
--                convention), applied to the FULL tile, then a 6x6 sub-block
--                sliced from the already-quantized INT8 tile.
--
-- ---- Both DUTs see the IDENTICAL pixel stream ----------------------------
-- Kernel 0 and kernel 2 are two DIFFERENT output channels of the SAME
-- trained Conv2d layer, evaluated on the SAME real patch -- so both DUTs
-- are driven by the same pixel_c0/c1/c2 signals in this testbench, and
-- (since both share the identical stream_conv3x3_3chan_cell/window3x3_stream
-- architecture and IMG_WIDTH) their valid_out pulses occur on IDENTICAL
-- clock cycles; only their y_bn_relu_fx values differ (different folded
-- weights, different real-tile SCALE_FX/BIAS_FX).
--
-- ---- Checking style (deliberately NOT severity failure per-check) --------
-- Unlike most other testbenches in this repo, mismatches here are reported
-- as WARNINGS (not immediate FAILUREs) so the simulation continues through
-- all checks and this testbench can report a max-absolute-integer-difference
-- summary across every check, not just the first mismatch. A single
-- final assertion (severity failure) fires at the very end if any check
-- failed, so `--assert-level=failure` still causes a nonzero-status batch
-- run to be flagged, without truncating the max-diff computation.
--
-- ---- What this validates -----------------------------------------------
-- Confirms the EXISTING, UNMODIFIED kernel-0/kernel-2 folded Conv-BN-ReLU
-- pipelined datapath produces the SAME fixed-point integer values as the
-- Python golden-vector generator on a REAL UAVSAR-tile-derived patch. It
-- does NOT validate the other 30 output channels, does NOT implement
-- padding, and has NOT been run on real FPGA hardware -- this is a
-- simulation-only, real-data-input functional check of a real-data
-- verification SUBSET (2 of 32 kernels).

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.real_tile_stimulus_pkg.all;
use work.first_conv_bn_relu_kernel0_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel2_real_tile_q20_pkg.all;

entity tb_stream_conv3x3_3chan_first_layer_real_tile_bn_relu_q20 is
end entity tb_stream_conv3x3_3chan_first_layer_real_tile_bn_relu_q20;

architecture sim of tb_stream_conv3x3_3chan_first_layer_real_tile_bn_relu_q20 is

    constant CLK_PERIOD  : time     := 10 ns;
    constant N_POSITIONS : integer  := (BLOCK_SIZE - 2) * (BLOCK_SIZE - 2);
    constant DRAIN_CYCLES : integer := 15;   -- generous margin beyond the fixed
                                              -- 6-cycle datapath latency

    signal clk      : std_logic := '0';
    signal rst      : std_logic := '1';
    signal valid_in : std_logic := '0';

    signal pixel_c0 : signed(7 downto 0) := (others => '0');
    signal pixel_c1 : signed(7 downto 0) := (others => '0');
    signal pixel_c2 : signed(7 downto 0) := (others => '0');

    signal valid_out_k0    : std_logic;
    signal y_bn_relu_fx_k0 : signed(47 downto 0);
    signal valid_out_k2    : std_logic;
    signal y_bn_relu_fx_k2 : signed(47 downto 0);

begin

    clk <= not clk after CLK_PERIOD / 2;

    dut_k0 : entity work.stream_conv3x3_3chan_kernel0_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k0, y_bn_relu_fx => y_bn_relu_fx_k0
        );

    dut_k2 : entity work.stream_conv3x3_3chan_kernel2_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k2, y_bn_relu_fx => y_bn_relu_fx_k2
        );

    stim : process
        variable out_count_k0 : integer := 0;
        variable out_count_k2 : integer := 0;
        variable pass_count   : integer := 0;
        variable fail_count   : integer := 0;
        variable max_abs_diff : integer := 0;
        variable expected     : integer;
        variable got          : integer;
        variable diff         : integer;

        procedure check_output(kernel_id : integer; out_num : integer;
                                expected_v : integer; got_v : integer) is
        begin
            diff := abs(got_v - expected_v);
            if diff > max_abs_diff then
                max_abs_diff := diff;
            end if;
            if got_v = expected_v then
                pass_count := pass_count + 1;
                report "PASS kernel " & integer'image(kernel_id) &
                       " output " & integer'image(out_num) &
                       ": y_bn_relu_fx = " & integer'image(got_v) &
                       "  (REAL TILE, Q.20 fixed-point, ReLU applied)";
            else
                fail_count := fail_count + 1;
                report "FAIL kernel " & integer'image(kernel_id) &
                       " output " & integer'image(out_num) &
                       ": y_bn_relu_fx = " & integer'image(got_v) &
                       "  expected " & integer'image(expected_v) &
                       "  abs_diff = " & integer'image(diff)
                    severity warning;
            end if;
        end procedure check_output;

    begin
        -- ---- Reset (3 clocks) ----------------------------------------
        rst      <= '1';
        valid_in <= '0';
        pixel_c0 <= (others => '0');
        pixel_c1 <= (others => '0');
        pixel_c2 <= (others => '0');
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        rst  <= '0';
        wait until rising_edge(clk);
        wait for 1 ns;

        -- ---- Stream the REAL BLOCK_SIZE x BLOCK_SIZE patch (one pixel
        -- triplet per clock, row-major, matching real_tile_stimulus_pkg's
        -- flat layout) ----------------------------------------------------
        valid_in <= '1';
        for i in 0 to BLOCK_SIZE * BLOCK_SIZE - 1 loop
            pixel_c0 <= to_signed(REAL_TILE_CH0(i), 8);
            pixel_c1 <= to_signed(REAL_TILE_CH1(i), 8);
            pixel_c2 <= to_signed(REAL_TILE_CH2(i), 8);
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out_k0 = '1' then
                out_count_k0 := out_count_k0 + 1;
                expected := K0_RT_BN_RELU_EXPECTED_FX(out_count_k0 - 1);
                got      := to_integer(y_bn_relu_fx_k0);
                check_output(0, out_count_k0, expected, got);
            end if;
            if valid_out_k2 = '1' then
                out_count_k2 := out_count_k2 + 1;
                expected := K2_RT_BN_RELU_EXPECTED_FX(out_count_k2 - 1);
                got      := to_integer(y_bn_relu_fx_k2);
                check_output(2, out_count_k2, expected, got);
            end if;
        end loop;

        -- ---- Drain: flush the pipeline for both DUTs ------------------
        valid_in <= '0';
        for d in 1 to DRAIN_CYCLES loop
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out_k0 = '1' then
                out_count_k0 := out_count_k0 + 1;
                expected := K0_RT_BN_RELU_EXPECTED_FX(out_count_k0 - 1);
                got      := to_integer(y_bn_relu_fx_k0);
                check_output(0, out_count_k0, expected, got);
            end if;
            if valid_out_k2 = '1' then
                out_count_k2 := out_count_k2 + 1;
                expected := K2_RT_BN_RELU_EXPECTED_FX(out_count_k2 - 1);
                got      := to_integer(y_bn_relu_fx_k2);
                check_output(2, out_count_k2, expected, got);
            end if;
        end loop;

        -- ---- Structural checks: exactly N_POSITIONS outputs per kernel --
        assert out_count_k0 = N_POSITIONS
            report "FAIL: kernel 0 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k0)
            severity warning;
        assert out_count_k2 = N_POSITIONS
            report "FAIL: kernel 2 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k2)
            severity warning;
        if out_count_k0 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        if out_count_k2 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;

        -- ---- Concise summary report (PASS/FAIL count + max abs diff) --
        report "=== REAL-TILE first-layer Conv-BN-ReLU verification summary ===" severity note;
        report "    Kernel 0: " & integer'image(out_count_k0) & " / " &
               integer'image(N_POSITIONS) & " outputs observed" severity note;
        report "    Kernel 2: " & integer'image(out_count_k2) & " / " &
               integer'image(N_POSITIONS) & " outputs observed" severity note;
        report "    PASS count = " & integer'image(pass_count) &
               "   FAIL count = " & integer'image(fail_count) severity note;
        report "    Max absolute integer difference (Q.20 fixed-point) = " &
               integer'image(max_abs_diff) severity note;

        if fail_count = 0 then
            report "=== All tb_stream_conv3x3_3chan_first_layer_real_tile_bn_relu_q20 tests PASSED ===" &
                   "  (" & integer'image(pass_count) & " / " & integer'image(pass_count) &
                   " outputs match Python Q.20 fixed-point golden vectors on REAL UAVSAR tile data)"
                severity note;
        else
            report "=== " & integer'image(fail_count) & " CHECK(S) FAILED ===" severity failure;
        end if;
        report "    Kernel 0/2 folded Conv-BN-ReLU (REAL TILE tile_16_42.tif), enc1.block.0/1 from" &
               " alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt" severity note;
        report "    NOTE: real-data verification SUBSET (kernel 0 and kernel 2 of 32 channels)." &
               " Not board-tested, not a measured speedup/power claim." severity note;

        wait;
    end process stim;

end architecture sim;
