-- tb_stream_conv3x3_3chan_kernel0_bn_relu.vhd
-- Self-checking testbench for stream_conv3x3_3chan_kernel0_bn_relu.
--
-- Drives the canonical 5x5x3 toy patch (same stimulus as every other
-- testbench in this repo) and checks all 9 valid output positions against
-- the EXACT Q.16 fixed-point integer golden values from
-- first_conv_bn_relu_kernel0_pkg (generated by
-- scripts/generate_kernel0_bn_relu_fixed_point_vectors.py). This compares
-- fixed-point integers to fixed-point integers -- NOT a float-vs-fixed-point
-- comparison.
--
-- ---- Source of weights/constants -----------------------------------------
-- Checkpoint : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Tensor key : enc1.block.0.weight (kernel 0), folded with enc1.block.1
--              (BatchNorm2d, eval-mode running stats)
-- Fixed pt.  : Q.16 (signed, 16 fractional bits); SCALE_FX, BIAS_FX from
--              first_conv_bn_relu_kernel0_pkg
--
-- ---- Input patch --------------------------------------------------------
-- Canonical 5x5x3 toy patch, identical to every prior testbench:
--   Channel 0: 1..25 row-major
--   Channel 1: 2 x channel 0  (2..50)
--   Channel 2: -1 x channel 0  (-1..-25)
--
-- ---- Timing (5-cycle latency: 4 from stream_conv3x3_3chan_cell + 1 BN+ReLU) --
--   Outputs 1-3: main loop i=18, 19, 20
--   Outputs 4-6: main loop i=23, 24, 25
--   Outputs 7-9: drain d=1..5 (5-clock drain to flush the extra BN+ReLU stage)
--
-- ---- What this validates -----------------------------------------------
-- Confirms stream_conv3x3_3chan_kernel0_bn_relu produces, in ONE streaming
-- pass, the same 9 Q.16 fixed-point INT32/48 values that
-- scripts/generate_kernel0_bn_relu_fixed_point_vectors.py computes for
-- kernel 0's folded Conv-BN-ReLU stage on the toy input. It does NOT
-- validate the other 31 output channels, does NOT implement padding, and
-- has NOT been run on real FPGA hardware -- this is a simulation-only
-- functional check of the kernel-0 folded Conv-BN-ReLU proof-of-concept.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.first_conv_bn_relu_kernel0_pkg.all;

entity tb_stream_conv3x3_3chan_kernel0_bn_relu is
end entity tb_stream_conv3x3_3chan_kernel0_bn_relu;

architecture sim of tb_stream_conv3x3_3chan_kernel0_bn_relu is

    constant CLK_PERIOD : time     := 10 ns;
    constant IMG_W      : positive := 5;

    signal clk      : std_logic := '0';
    signal rst      : std_logic := '1';
    signal valid_in : std_logic := '0';

    signal pixel_c0 : signed(7 downto 0) := (others => '0');
    signal pixel_c1 : signed(7 downto 0) := (others => '0');
    signal pixel_c2 : signed(7 downto 0) := (others => '0');

    signal valid_out    : std_logic;
    signal y_bn_relu_fx : signed(47 downto 0);

begin

    clk <= not clk after CLK_PERIOD / 2;

    dut : entity work.stream_conv3x3_3chan_kernel0_bn_relu
        generic map (IMG_WIDTH => IMG_W)
        port map (
            clk      => clk,
            rst      => rst,
            valid_in => valid_in,
            pixel_c0 => pixel_c0,
            pixel_c1 => pixel_c1,
            pixel_c2 => pixel_c2,
            valid_out    => valid_out,
            y_bn_relu_fx => y_bn_relu_fx
        );

    stim : process

        variable out_count : integer := 0;

        procedure check_output(out_num : integer) is
            variable expected : integer;
            variable got      : integer;
        begin
            expected := K0_BN_RELU_EXPECTED_FX(out_num - 1);
            got      := to_integer(y_bn_relu_fx);
            assert got = expected
                report "FAIL output " & integer'image(out_num) &
                       ": y_bn_relu_fx = " & integer'image(got) &
                       "  expected " & integer'image(expected)
                severity failure;
            report "PASS output " & integer'image(out_num) &
                   ": y_bn_relu_fx = " & integer'image(got) &
                   "  (Q." & integer'image(FRAC_BITS) & " fixed-point, ReLU applied)";
        end procedure check_output;

    begin
        -- ---- Reset (3 clocks) ----------------------------------------
        rst      <= '1';
        valid_in <= '0';
        pixel_c0 <= (others => '0');
        pixel_c1 <= (others => '0');
        pixel_c2 <= (others => '0');
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        rst  <= '0';
        wait until rising_edge(clk);
        wait for 1 ns;

        -- ---- Stream 5x5 image (one pixel triplet per clock) ----------
        -- 5-cycle cell latency (4-cycle raw conv + 1-cycle BN+ReLU):
        --   first output visible at i=18 (one cycle later than the
        --   4-cycle-latency raw-conv-only testbenches, which see their
        --   first output at i=17).

        valid_in <= '1';
        for i in 1 to 25 loop
            pixel_c0 <= to_signed(i,    8);
            pixel_c1 <= to_signed(2*i,  8);
            pixel_c2 <= to_signed(-i,   8);
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out = '1' then
                out_count := out_count + 1;
                check_output(out_count);
            end if;
        end loop;

        -- ---- Drain: 5 clocks to flush the extra BN+ReLU pipeline stage --
        valid_in <= '0';
        for d in 1 to 5 loop
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out = '1' then
                out_count := out_count + 1;
                check_output(out_count);
            end if;
        end loop;

        -- ---- Final checks --------------------------------------------
        assert out_count = 9
            report "FAIL: expected exactly 9 valid output positions, observed " &
                   integer'image(out_count)
            severity failure;

        report "=== All stream_conv3x3_3chan_kernel0_bn_relu tests PASSED ===" &
               "  (9 / 9 outputs match Python Q.16 fixed-point golden vectors)"
               severity note;
        report "    Kernel 0 folded Conv-BN-ReLU, enc1.block.0/1 from" &
               " alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt" severity note;
        report "    NOTE: kernel-0-only proof-of-concept. Not all 32 channels," &
               " not board-tested, not a measured speedup/power claim." severity note;

        wait;
    end process stim;

end architecture sim;
