-- tb_stream_conv3x3_3chan_all32_kernels_real_tile_bn_relu_q20.vhd
-- Self-checking testbench: REAL-TILE Q.20 verification of ALL 32 output
-- channels of the first Conv-BN-ReLU stage.
--
-- This EXTENDS the original real-tile verification subset (kernel 0 and
-- kernel 2 only, Q.16 then Q.20 --
-- hardware/vhdl_conv3x3/reports/real_tile_first_layer_vhdl_verification_summary.md,
-- hardware/vhdl_conv3x3/reports/real_tile_fixed_point_precision_sensitivity_summary.md)
-- to the COMPLETE first Conv2d layer's 32 output channels, using the
-- IDENTICAL real 6x6x3 UAVSAR sub-block (tile_16_42.tif, row_offset=125,
-- col_offset=125) and the SAME 16 valid 3x3 windows per kernel already
-- used for the kernel0/kernel2 subset.
--
-- Every one of the 32 DUTs instantiated below
-- (stream_conv3x3_3chan_kernel{0..31}_bn_relu_real_tile_q20) is
-- structurally IDENTICAL: the SAME existing, unmodified
-- stream_conv3x3_3chan_cell sub-component, the SAME two-stage registered
-- Q.20 BatchNorm-fold + ReLU pipeline, differing ONLY in which kernel's
-- folded INT8 weights and Q.20 SCALE_FX/BIAS_FX constants they use. This
-- is NOT a new hardware architecture and NOT full 32-output resource
-- sharing (that is a DIFFERENT, separate design,
-- stream_conv3x3_3chan_32out_bn_relu_time_mux, not touched here) -- this
-- is 32 INDEPENDENT single-kernel real-tile pipelines, all fed the SAME
-- real pixel stream in parallel within this one simulation, each checked
-- against its own kernel's Python Q.20 golden vectors.
--
-- ---- Source of the real patch --------------------------------------------
-- Tile        : tile_16_42.tif (first row of heldout_fp2_test.csv)
-- Checkpoint  : models/alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt
-- Generated by: scripts/generate_real_tile_bn_relu_fixed_point_vectors.py
--               (--kernel-id 0 through 31, --frac-bits 20, --variant-suffix _q20)
-- Normalization: FloodTileDataset._normalize_per_tile (train_unet_baseline_tuned.py)
-- Quantization : per-tile scale_x (analyze_first_layer_fixed_point_segmentation_impact.py
--                convention), applied to the FULL tile, then a 6x6 sub-block
--                sliced from the already-quantized INT8 tile -- IDENTICAL
--                real pixel stimulus to the kernel0/kernel2 subset
--                (real_tile_stimulus_pkg, not regenerated for this task).
--
-- ---- All 32 DUTs see the IDENTICAL pixel stream --------------------------
-- All 32 kernels are different output channels of the SAME trained
-- Conv2d layer, evaluated on the SAME real patch -- so all 32 DUTs are
-- driven by the same pixel_c0/c1/c2 signals in this testbench, and
-- (since all share the identical stream_conv3x3_3chan_cell/window3x3_stream
-- architecture and IMG_WIDTH) their valid_out pulses occur on IDENTICAL
-- clock cycles; only their y_bn_relu_fx values differ (different folded
-- weights, different per-kernel Q.20 SCALE_FX/BIAS_FX).
--
-- ---- Checking style (deliberately NOT severity failure per-check) --------
-- Same convention as the original kernel0/kernel2 combined testbench:
-- mismatches are reported as WARNINGS (not immediate FAILUREs) so the
-- simulation continues through all 32*16=512 checks and this testbench
-- can report a max-absolute-integer-difference summary across every
-- check, not just the first mismatch. A single final assertion (severity
-- failure) fires at the very end if any check failed.
--
-- ---- What this validates -----------------------------------------------
-- Confirms the EXISTING, UNMODIFIED (per-kernel, mechanically templated)
-- folded Conv-BN-ReLU pipelined datapath produces the SAME Q.20
-- fixed-point integer values as the Python golden-vector generator, for
-- ALL 32 output channels, on the SAME REAL UAVSAR-tile-derived patch
-- already used for the kernel0/kernel2 subset. It does NOT implement
-- padding, has NOT been run on real FPGA hardware, is NOT full FPGA
-- U-Net, NOT board deployment, and NOT full-image streaming -- this is
-- simulation-only verification of one small real patch's 16 valid
-- windows, for all 32 output channels.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use work.real_tile_stimulus_pkg.all;
use work.first_conv_bn_relu_kernel0_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel1_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel2_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel3_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel4_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel5_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel6_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel7_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel8_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel9_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel10_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel11_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel12_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel13_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel14_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel15_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel16_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel17_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel18_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel19_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel20_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel21_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel22_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel23_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel24_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel25_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel26_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel27_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel28_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel29_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel30_real_tile_q20_pkg.all;
use work.first_conv_bn_relu_kernel31_real_tile_q20_pkg.all;

entity tb_stream_conv3x3_3chan_all32_kernels_real_tile_bn_relu_q20 is
end entity tb_stream_conv3x3_3chan_all32_kernels_real_tile_bn_relu_q20;

architecture sim of tb_stream_conv3x3_3chan_all32_kernels_real_tile_bn_relu_q20 is

    constant CLK_PERIOD   : time    := 10 ns;
    constant N_POSITIONS  : integer := (BLOCK_SIZE - 2) * (BLOCK_SIZE - 2);
    constant DRAIN_CYCLES : integer := 15;   -- generous margin beyond the fixed
                                              -- 6-cycle datapath latency
    constant NUM_KERNELS  : integer := 32;

    signal clk      : std_logic := '0';
    signal rst      : std_logic := '1';
    signal valid_in : std_logic := '0';

    signal pixel_c0 : signed(7 downto 0) := (others => '0');
    signal pixel_c1 : signed(7 downto 0) := (others => '0');
    signal pixel_c2 : signed(7 downto 0) := (others => '0');

    signal valid_out_k0    : std_logic;
    signal y_bn_relu_fx_k0 : signed(47 downto 0);
    signal valid_out_k1    : std_logic;
    signal y_bn_relu_fx_k1 : signed(47 downto 0);
    signal valid_out_k2    : std_logic;
    signal y_bn_relu_fx_k2 : signed(47 downto 0);
    signal valid_out_k3    : std_logic;
    signal y_bn_relu_fx_k3 : signed(47 downto 0);
    signal valid_out_k4    : std_logic;
    signal y_bn_relu_fx_k4 : signed(47 downto 0);
    signal valid_out_k5    : std_logic;
    signal y_bn_relu_fx_k5 : signed(47 downto 0);
    signal valid_out_k6    : std_logic;
    signal y_bn_relu_fx_k6 : signed(47 downto 0);
    signal valid_out_k7    : std_logic;
    signal y_bn_relu_fx_k7 : signed(47 downto 0);
    signal valid_out_k8    : std_logic;
    signal y_bn_relu_fx_k8 : signed(47 downto 0);
    signal valid_out_k9    : std_logic;
    signal y_bn_relu_fx_k9 : signed(47 downto 0);
    signal valid_out_k10    : std_logic;
    signal y_bn_relu_fx_k10 : signed(47 downto 0);
    signal valid_out_k11    : std_logic;
    signal y_bn_relu_fx_k11 : signed(47 downto 0);
    signal valid_out_k12    : std_logic;
    signal y_bn_relu_fx_k12 : signed(47 downto 0);
    signal valid_out_k13    : std_logic;
    signal y_bn_relu_fx_k13 : signed(47 downto 0);
    signal valid_out_k14    : std_logic;
    signal y_bn_relu_fx_k14 : signed(47 downto 0);
    signal valid_out_k15    : std_logic;
    signal y_bn_relu_fx_k15 : signed(47 downto 0);
    signal valid_out_k16    : std_logic;
    signal y_bn_relu_fx_k16 : signed(47 downto 0);
    signal valid_out_k17    : std_logic;
    signal y_bn_relu_fx_k17 : signed(47 downto 0);
    signal valid_out_k18    : std_logic;
    signal y_bn_relu_fx_k18 : signed(47 downto 0);
    signal valid_out_k19    : std_logic;
    signal y_bn_relu_fx_k19 : signed(47 downto 0);
    signal valid_out_k20    : std_logic;
    signal y_bn_relu_fx_k20 : signed(47 downto 0);
    signal valid_out_k21    : std_logic;
    signal y_bn_relu_fx_k21 : signed(47 downto 0);
    signal valid_out_k22    : std_logic;
    signal y_bn_relu_fx_k22 : signed(47 downto 0);
    signal valid_out_k23    : std_logic;
    signal y_bn_relu_fx_k23 : signed(47 downto 0);
    signal valid_out_k24    : std_logic;
    signal y_bn_relu_fx_k24 : signed(47 downto 0);
    signal valid_out_k25    : std_logic;
    signal y_bn_relu_fx_k25 : signed(47 downto 0);
    signal valid_out_k26    : std_logic;
    signal y_bn_relu_fx_k26 : signed(47 downto 0);
    signal valid_out_k27    : std_logic;
    signal y_bn_relu_fx_k27 : signed(47 downto 0);
    signal valid_out_k28    : std_logic;
    signal y_bn_relu_fx_k28 : signed(47 downto 0);
    signal valid_out_k29    : std_logic;
    signal y_bn_relu_fx_k29 : signed(47 downto 0);
    signal valid_out_k30    : std_logic;
    signal y_bn_relu_fx_k30 : signed(47 downto 0);
    signal valid_out_k31    : std_logic;
    signal y_bn_relu_fx_k31 : signed(47 downto 0);

begin

    clk <= not clk after CLK_PERIOD / 2;

    dut_k0 : entity work.stream_conv3x3_3chan_kernel0_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k0, y_bn_relu_fx => y_bn_relu_fx_k0
        );

    dut_k1 : entity work.stream_conv3x3_3chan_kernel1_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k1, y_bn_relu_fx => y_bn_relu_fx_k1
        );

    dut_k2 : entity work.stream_conv3x3_3chan_kernel2_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k2, y_bn_relu_fx => y_bn_relu_fx_k2
        );

    dut_k3 : entity work.stream_conv3x3_3chan_kernel3_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k3, y_bn_relu_fx => y_bn_relu_fx_k3
        );

    dut_k4 : entity work.stream_conv3x3_3chan_kernel4_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k4, y_bn_relu_fx => y_bn_relu_fx_k4
        );

    dut_k5 : entity work.stream_conv3x3_3chan_kernel5_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k5, y_bn_relu_fx => y_bn_relu_fx_k5
        );

    dut_k6 : entity work.stream_conv3x3_3chan_kernel6_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k6, y_bn_relu_fx => y_bn_relu_fx_k6
        );

    dut_k7 : entity work.stream_conv3x3_3chan_kernel7_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k7, y_bn_relu_fx => y_bn_relu_fx_k7
        );

    dut_k8 : entity work.stream_conv3x3_3chan_kernel8_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k8, y_bn_relu_fx => y_bn_relu_fx_k8
        );

    dut_k9 : entity work.stream_conv3x3_3chan_kernel9_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k9, y_bn_relu_fx => y_bn_relu_fx_k9
        );

    dut_k10 : entity work.stream_conv3x3_3chan_kernel10_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k10, y_bn_relu_fx => y_bn_relu_fx_k10
        );

    dut_k11 : entity work.stream_conv3x3_3chan_kernel11_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k11, y_bn_relu_fx => y_bn_relu_fx_k11
        );

    dut_k12 : entity work.stream_conv3x3_3chan_kernel12_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k12, y_bn_relu_fx => y_bn_relu_fx_k12
        );

    dut_k13 : entity work.stream_conv3x3_3chan_kernel13_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k13, y_bn_relu_fx => y_bn_relu_fx_k13
        );

    dut_k14 : entity work.stream_conv3x3_3chan_kernel14_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k14, y_bn_relu_fx => y_bn_relu_fx_k14
        );

    dut_k15 : entity work.stream_conv3x3_3chan_kernel15_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k15, y_bn_relu_fx => y_bn_relu_fx_k15
        );

    dut_k16 : entity work.stream_conv3x3_3chan_kernel16_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k16, y_bn_relu_fx => y_bn_relu_fx_k16
        );

    dut_k17 : entity work.stream_conv3x3_3chan_kernel17_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k17, y_bn_relu_fx => y_bn_relu_fx_k17
        );

    dut_k18 : entity work.stream_conv3x3_3chan_kernel18_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k18, y_bn_relu_fx => y_bn_relu_fx_k18
        );

    dut_k19 : entity work.stream_conv3x3_3chan_kernel19_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k19, y_bn_relu_fx => y_bn_relu_fx_k19
        );

    dut_k20 : entity work.stream_conv3x3_3chan_kernel20_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k20, y_bn_relu_fx => y_bn_relu_fx_k20
        );

    dut_k21 : entity work.stream_conv3x3_3chan_kernel21_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k21, y_bn_relu_fx => y_bn_relu_fx_k21
        );

    dut_k22 : entity work.stream_conv3x3_3chan_kernel22_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k22, y_bn_relu_fx => y_bn_relu_fx_k22
        );

    dut_k23 : entity work.stream_conv3x3_3chan_kernel23_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k23, y_bn_relu_fx => y_bn_relu_fx_k23
        );

    dut_k24 : entity work.stream_conv3x3_3chan_kernel24_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k24, y_bn_relu_fx => y_bn_relu_fx_k24
        );

    dut_k25 : entity work.stream_conv3x3_3chan_kernel25_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k25, y_bn_relu_fx => y_bn_relu_fx_k25
        );

    dut_k26 : entity work.stream_conv3x3_3chan_kernel26_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k26, y_bn_relu_fx => y_bn_relu_fx_k26
        );

    dut_k27 : entity work.stream_conv3x3_3chan_kernel27_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k27, y_bn_relu_fx => y_bn_relu_fx_k27
        );

    dut_k28 : entity work.stream_conv3x3_3chan_kernel28_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k28, y_bn_relu_fx => y_bn_relu_fx_k28
        );

    dut_k29 : entity work.stream_conv3x3_3chan_kernel29_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k29, y_bn_relu_fx => y_bn_relu_fx_k29
        );

    dut_k30 : entity work.stream_conv3x3_3chan_kernel30_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k30, y_bn_relu_fx => y_bn_relu_fx_k30
        );

    dut_k31 : entity work.stream_conv3x3_3chan_kernel31_bn_relu_real_tile_q20
        generic map (IMG_WIDTH => BLOCK_SIZE)
        port map (
            clk => clk, rst => rst, valid_in => valid_in,
            pixel_c0 => pixel_c0, pixel_c1 => pixel_c1, pixel_c2 => pixel_c2,
            valid_out => valid_out_k31, y_bn_relu_fx => y_bn_relu_fx_k31
        );

    stim : process
        variable out_count_k0 : integer := 0;
        variable out_count_k1 : integer := 0;
        variable out_count_k2 : integer := 0;
        variable out_count_k3 : integer := 0;
        variable out_count_k4 : integer := 0;
        variable out_count_k5 : integer := 0;
        variable out_count_k6 : integer := 0;
        variable out_count_k7 : integer := 0;
        variable out_count_k8 : integer := 0;
        variable out_count_k9 : integer := 0;
        variable out_count_k10 : integer := 0;
        variable out_count_k11 : integer := 0;
        variable out_count_k12 : integer := 0;
        variable out_count_k13 : integer := 0;
        variable out_count_k14 : integer := 0;
        variable out_count_k15 : integer := 0;
        variable out_count_k16 : integer := 0;
        variable out_count_k17 : integer := 0;
        variable out_count_k18 : integer := 0;
        variable out_count_k19 : integer := 0;
        variable out_count_k20 : integer := 0;
        variable out_count_k21 : integer := 0;
        variable out_count_k22 : integer := 0;
        variable out_count_k23 : integer := 0;
        variable out_count_k24 : integer := 0;
        variable out_count_k25 : integer := 0;
        variable out_count_k26 : integer := 0;
        variable out_count_k27 : integer := 0;
        variable out_count_k28 : integer := 0;
        variable out_count_k29 : integer := 0;
        variable out_count_k30 : integer := 0;
        variable out_count_k31 : integer := 0;
        variable pass_count   : integer := 0;
        variable fail_count   : integer := 0;
        variable max_abs_diff : integer := 0;
        variable total_checked : integer := 0;
        variable expected     : integer;
        variable got          : integer;
        variable diff         : integer;

        procedure check_output(kernel_id : integer; out_num : integer;
                                expected_v : integer; got_v : integer) is
        begin
            diff := abs(got_v - expected_v);
            if diff > max_abs_diff then
                max_abs_diff := diff;
            end if;
            total_checked := total_checked + 1;
            if got_v = expected_v then
                pass_count := pass_count + 1;
            else
                fail_count := fail_count + 1;
                report "FAIL kernel " & integer'image(kernel_id) &
                       " output " & integer'image(out_num) &
                       ": y_bn_relu_fx = " & integer'image(got_v) &
                       "  expected " & integer'image(expected_v) &
                       "  abs_diff = " & integer'image(diff)
                    severity warning;
            end if;
        end procedure check_output;

    begin
        -- ---- Reset (3 clocks) ----------------------------------------
        rst      <= '1';
        valid_in <= '0';
        pixel_c0 <= (others => '0');
        pixel_c1 <= (others => '0');
        pixel_c2 <= (others => '0');
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        wait until rising_edge(clk);
        rst  <= '0';
        wait until rising_edge(clk);
        wait for 1 ns;

        -- ---- Stream the REAL BLOCK_SIZE x BLOCK_SIZE patch (one pixel
        -- triplet per clock, row-major, matching real_tile_stimulus_pkg's
        -- flat layout) -- IDENTICAL stimulus to the kernel0/kernel2
        -- combined testbench. ----------------------------------------------------
        valid_in <= '1';
        for i in 0 to BLOCK_SIZE * BLOCK_SIZE - 1 loop
            pixel_c0 <= to_signed(REAL_TILE_CH0(i), 8);
            pixel_c1 <= to_signed(REAL_TILE_CH1(i), 8);
            pixel_c2 <= to_signed(REAL_TILE_CH2(i), 8);
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out_k0 = '1' then
                out_count_k0 := out_count_k0 + 1;
                expected := K0_RT_BN_RELU_EXPECTED_FX(out_count_k0 - 1);
                got      := to_integer(y_bn_relu_fx_k0);
                check_output(0, out_count_k0, expected, got);
            end if;
            if valid_out_k1 = '1' then
                out_count_k1 := out_count_k1 + 1;
                expected := K1_RT_BN_RELU_EXPECTED_FX(out_count_k1 - 1);
                got      := to_integer(y_bn_relu_fx_k1);
                check_output(1, out_count_k1, expected, got);
            end if;
            if valid_out_k2 = '1' then
                out_count_k2 := out_count_k2 + 1;
                expected := K2_RT_BN_RELU_EXPECTED_FX(out_count_k2 - 1);
                got      := to_integer(y_bn_relu_fx_k2);
                check_output(2, out_count_k2, expected, got);
            end if;
            if valid_out_k3 = '1' then
                out_count_k3 := out_count_k3 + 1;
                expected := K3_RT_BN_RELU_EXPECTED_FX(out_count_k3 - 1);
                got      := to_integer(y_bn_relu_fx_k3);
                check_output(3, out_count_k3, expected, got);
            end if;
            if valid_out_k4 = '1' then
                out_count_k4 := out_count_k4 + 1;
                expected := K4_RT_BN_RELU_EXPECTED_FX(out_count_k4 - 1);
                got      := to_integer(y_bn_relu_fx_k4);
                check_output(4, out_count_k4, expected, got);
            end if;
            if valid_out_k5 = '1' then
                out_count_k5 := out_count_k5 + 1;
                expected := K5_RT_BN_RELU_EXPECTED_FX(out_count_k5 - 1);
                got      := to_integer(y_bn_relu_fx_k5);
                check_output(5, out_count_k5, expected, got);
            end if;
            if valid_out_k6 = '1' then
                out_count_k6 := out_count_k6 + 1;
                expected := K6_RT_BN_RELU_EXPECTED_FX(out_count_k6 - 1);
                got      := to_integer(y_bn_relu_fx_k6);
                check_output(6, out_count_k6, expected, got);
            end if;
            if valid_out_k7 = '1' then
                out_count_k7 := out_count_k7 + 1;
                expected := K7_RT_BN_RELU_EXPECTED_FX(out_count_k7 - 1);
                got      := to_integer(y_bn_relu_fx_k7);
                check_output(7, out_count_k7, expected, got);
            end if;
            if valid_out_k8 = '1' then
                out_count_k8 := out_count_k8 + 1;
                expected := K8_RT_BN_RELU_EXPECTED_FX(out_count_k8 - 1);
                got      := to_integer(y_bn_relu_fx_k8);
                check_output(8, out_count_k8, expected, got);
            end if;
            if valid_out_k9 = '1' then
                out_count_k9 := out_count_k9 + 1;
                expected := K9_RT_BN_RELU_EXPECTED_FX(out_count_k9 - 1);
                got      := to_integer(y_bn_relu_fx_k9);
                check_output(9, out_count_k9, expected, got);
            end if;
            if valid_out_k10 = '1' then
                out_count_k10 := out_count_k10 + 1;
                expected := K10_RT_BN_RELU_EXPECTED_FX(out_count_k10 - 1);
                got      := to_integer(y_bn_relu_fx_k10);
                check_output(10, out_count_k10, expected, got);
            end if;
            if valid_out_k11 = '1' then
                out_count_k11 := out_count_k11 + 1;
                expected := K11_RT_BN_RELU_EXPECTED_FX(out_count_k11 - 1);
                got      := to_integer(y_bn_relu_fx_k11);
                check_output(11, out_count_k11, expected, got);
            end if;
            if valid_out_k12 = '1' then
                out_count_k12 := out_count_k12 + 1;
                expected := K12_RT_BN_RELU_EXPECTED_FX(out_count_k12 - 1);
                got      := to_integer(y_bn_relu_fx_k12);
                check_output(12, out_count_k12, expected, got);
            end if;
            if valid_out_k13 = '1' then
                out_count_k13 := out_count_k13 + 1;
                expected := K13_RT_BN_RELU_EXPECTED_FX(out_count_k13 - 1);
                got      := to_integer(y_bn_relu_fx_k13);
                check_output(13, out_count_k13, expected, got);
            end if;
            if valid_out_k14 = '1' then
                out_count_k14 := out_count_k14 + 1;
                expected := K14_RT_BN_RELU_EXPECTED_FX(out_count_k14 - 1);
                got      := to_integer(y_bn_relu_fx_k14);
                check_output(14, out_count_k14, expected, got);
            end if;
            if valid_out_k15 = '1' then
                out_count_k15 := out_count_k15 + 1;
                expected := K15_RT_BN_RELU_EXPECTED_FX(out_count_k15 - 1);
                got      := to_integer(y_bn_relu_fx_k15);
                check_output(15, out_count_k15, expected, got);
            end if;
            if valid_out_k16 = '1' then
                out_count_k16 := out_count_k16 + 1;
                expected := K16_RT_BN_RELU_EXPECTED_FX(out_count_k16 - 1);
                got      := to_integer(y_bn_relu_fx_k16);
                check_output(16, out_count_k16, expected, got);
            end if;
            if valid_out_k17 = '1' then
                out_count_k17 := out_count_k17 + 1;
                expected := K17_RT_BN_RELU_EXPECTED_FX(out_count_k17 - 1);
                got      := to_integer(y_bn_relu_fx_k17);
                check_output(17, out_count_k17, expected, got);
            end if;
            if valid_out_k18 = '1' then
                out_count_k18 := out_count_k18 + 1;
                expected := K18_RT_BN_RELU_EXPECTED_FX(out_count_k18 - 1);
                got      := to_integer(y_bn_relu_fx_k18);
                check_output(18, out_count_k18, expected, got);
            end if;
            if valid_out_k19 = '1' then
                out_count_k19 := out_count_k19 + 1;
                expected := K19_RT_BN_RELU_EXPECTED_FX(out_count_k19 - 1);
                got      := to_integer(y_bn_relu_fx_k19);
                check_output(19, out_count_k19, expected, got);
            end if;
            if valid_out_k20 = '1' then
                out_count_k20 := out_count_k20 + 1;
                expected := K20_RT_BN_RELU_EXPECTED_FX(out_count_k20 - 1);
                got      := to_integer(y_bn_relu_fx_k20);
                check_output(20, out_count_k20, expected, got);
            end if;
            if valid_out_k21 = '1' then
                out_count_k21 := out_count_k21 + 1;
                expected := K21_RT_BN_RELU_EXPECTED_FX(out_count_k21 - 1);
                got      := to_integer(y_bn_relu_fx_k21);
                check_output(21, out_count_k21, expected, got);
            end if;
            if valid_out_k22 = '1' then
                out_count_k22 := out_count_k22 + 1;
                expected := K22_RT_BN_RELU_EXPECTED_FX(out_count_k22 - 1);
                got      := to_integer(y_bn_relu_fx_k22);
                check_output(22, out_count_k22, expected, got);
            end if;
            if valid_out_k23 = '1' then
                out_count_k23 := out_count_k23 + 1;
                expected := K23_RT_BN_RELU_EXPECTED_FX(out_count_k23 - 1);
                got      := to_integer(y_bn_relu_fx_k23);
                check_output(23, out_count_k23, expected, got);
            end if;
            if valid_out_k24 = '1' then
                out_count_k24 := out_count_k24 + 1;
                expected := K24_RT_BN_RELU_EXPECTED_FX(out_count_k24 - 1);
                got      := to_integer(y_bn_relu_fx_k24);
                check_output(24, out_count_k24, expected, got);
            end if;
            if valid_out_k25 = '1' then
                out_count_k25 := out_count_k25 + 1;
                expected := K25_RT_BN_RELU_EXPECTED_FX(out_count_k25 - 1);
                got      := to_integer(y_bn_relu_fx_k25);
                check_output(25, out_count_k25, expected, got);
            end if;
            if valid_out_k26 = '1' then
                out_count_k26 := out_count_k26 + 1;
                expected := K26_RT_BN_RELU_EXPECTED_FX(out_count_k26 - 1);
                got      := to_integer(y_bn_relu_fx_k26);
                check_output(26, out_count_k26, expected, got);
            end if;
            if valid_out_k27 = '1' then
                out_count_k27 := out_count_k27 + 1;
                expected := K27_RT_BN_RELU_EXPECTED_FX(out_count_k27 - 1);
                got      := to_integer(y_bn_relu_fx_k27);
                check_output(27, out_count_k27, expected, got);
            end if;
            if valid_out_k28 = '1' then
                out_count_k28 := out_count_k28 + 1;
                expected := K28_RT_BN_RELU_EXPECTED_FX(out_count_k28 - 1);
                got      := to_integer(y_bn_relu_fx_k28);
                check_output(28, out_count_k28, expected, got);
            end if;
            if valid_out_k29 = '1' then
                out_count_k29 := out_count_k29 + 1;
                expected := K29_RT_BN_RELU_EXPECTED_FX(out_count_k29 - 1);
                got      := to_integer(y_bn_relu_fx_k29);
                check_output(29, out_count_k29, expected, got);
            end if;
            if valid_out_k30 = '1' then
                out_count_k30 := out_count_k30 + 1;
                expected := K30_RT_BN_RELU_EXPECTED_FX(out_count_k30 - 1);
                got      := to_integer(y_bn_relu_fx_k30);
                check_output(30, out_count_k30, expected, got);
            end if;
            if valid_out_k31 = '1' then
                out_count_k31 := out_count_k31 + 1;
                expected := K31_RT_BN_RELU_EXPECTED_FX(out_count_k31 - 1);
                got      := to_integer(y_bn_relu_fx_k31);
                check_output(31, out_count_k31, expected, got);
            end if;
        end loop;

        -- ---- Drain: flush the pipeline for all 32 DUTs ------------------
        valid_in <= '0';
        for d in 1 to DRAIN_CYCLES loop
            wait until rising_edge(clk);
            wait for 1 ns;

            if valid_out_k0 = '1' then
                out_count_k0 := out_count_k0 + 1;
                expected := K0_RT_BN_RELU_EXPECTED_FX(out_count_k0 - 1);
                got      := to_integer(y_bn_relu_fx_k0);
                check_output(0, out_count_k0, expected, got);
            end if;
            if valid_out_k1 = '1' then
                out_count_k1 := out_count_k1 + 1;
                expected := K1_RT_BN_RELU_EXPECTED_FX(out_count_k1 - 1);
                got      := to_integer(y_bn_relu_fx_k1);
                check_output(1, out_count_k1, expected, got);
            end if;
            if valid_out_k2 = '1' then
                out_count_k2 := out_count_k2 + 1;
                expected := K2_RT_BN_RELU_EXPECTED_FX(out_count_k2 - 1);
                got      := to_integer(y_bn_relu_fx_k2);
                check_output(2, out_count_k2, expected, got);
            end if;
            if valid_out_k3 = '1' then
                out_count_k3 := out_count_k3 + 1;
                expected := K3_RT_BN_RELU_EXPECTED_FX(out_count_k3 - 1);
                got      := to_integer(y_bn_relu_fx_k3);
                check_output(3, out_count_k3, expected, got);
            end if;
            if valid_out_k4 = '1' then
                out_count_k4 := out_count_k4 + 1;
                expected := K4_RT_BN_RELU_EXPECTED_FX(out_count_k4 - 1);
                got      := to_integer(y_bn_relu_fx_k4);
                check_output(4, out_count_k4, expected, got);
            end if;
            if valid_out_k5 = '1' then
                out_count_k5 := out_count_k5 + 1;
                expected := K5_RT_BN_RELU_EXPECTED_FX(out_count_k5 - 1);
                got      := to_integer(y_bn_relu_fx_k5);
                check_output(5, out_count_k5, expected, got);
            end if;
            if valid_out_k6 = '1' then
                out_count_k6 := out_count_k6 + 1;
                expected := K6_RT_BN_RELU_EXPECTED_FX(out_count_k6 - 1);
                got      := to_integer(y_bn_relu_fx_k6);
                check_output(6, out_count_k6, expected, got);
            end if;
            if valid_out_k7 = '1' then
                out_count_k7 := out_count_k7 + 1;
                expected := K7_RT_BN_RELU_EXPECTED_FX(out_count_k7 - 1);
                got      := to_integer(y_bn_relu_fx_k7);
                check_output(7, out_count_k7, expected, got);
            end if;
            if valid_out_k8 = '1' then
                out_count_k8 := out_count_k8 + 1;
                expected := K8_RT_BN_RELU_EXPECTED_FX(out_count_k8 - 1);
                got      := to_integer(y_bn_relu_fx_k8);
                check_output(8, out_count_k8, expected, got);
            end if;
            if valid_out_k9 = '1' then
                out_count_k9 := out_count_k9 + 1;
                expected := K9_RT_BN_RELU_EXPECTED_FX(out_count_k9 - 1);
                got      := to_integer(y_bn_relu_fx_k9);
                check_output(9, out_count_k9, expected, got);
            end if;
            if valid_out_k10 = '1' then
                out_count_k10 := out_count_k10 + 1;
                expected := K10_RT_BN_RELU_EXPECTED_FX(out_count_k10 - 1);
                got      := to_integer(y_bn_relu_fx_k10);
                check_output(10, out_count_k10, expected, got);
            end if;
            if valid_out_k11 = '1' then
                out_count_k11 := out_count_k11 + 1;
                expected := K11_RT_BN_RELU_EXPECTED_FX(out_count_k11 - 1);
                got      := to_integer(y_bn_relu_fx_k11);
                check_output(11, out_count_k11, expected, got);
            end if;
            if valid_out_k12 = '1' then
                out_count_k12 := out_count_k12 + 1;
                expected := K12_RT_BN_RELU_EXPECTED_FX(out_count_k12 - 1);
                got      := to_integer(y_bn_relu_fx_k12);
                check_output(12, out_count_k12, expected, got);
            end if;
            if valid_out_k13 = '1' then
                out_count_k13 := out_count_k13 + 1;
                expected := K13_RT_BN_RELU_EXPECTED_FX(out_count_k13 - 1);
                got      := to_integer(y_bn_relu_fx_k13);
                check_output(13, out_count_k13, expected, got);
            end if;
            if valid_out_k14 = '1' then
                out_count_k14 := out_count_k14 + 1;
                expected := K14_RT_BN_RELU_EXPECTED_FX(out_count_k14 - 1);
                got      := to_integer(y_bn_relu_fx_k14);
                check_output(14, out_count_k14, expected, got);
            end if;
            if valid_out_k15 = '1' then
                out_count_k15 := out_count_k15 + 1;
                expected := K15_RT_BN_RELU_EXPECTED_FX(out_count_k15 - 1);
                got      := to_integer(y_bn_relu_fx_k15);
                check_output(15, out_count_k15, expected, got);
            end if;
            if valid_out_k16 = '1' then
                out_count_k16 := out_count_k16 + 1;
                expected := K16_RT_BN_RELU_EXPECTED_FX(out_count_k16 - 1);
                got      := to_integer(y_bn_relu_fx_k16);
                check_output(16, out_count_k16, expected, got);
            end if;
            if valid_out_k17 = '1' then
                out_count_k17 := out_count_k17 + 1;
                expected := K17_RT_BN_RELU_EXPECTED_FX(out_count_k17 - 1);
                got      := to_integer(y_bn_relu_fx_k17);
                check_output(17, out_count_k17, expected, got);
            end if;
            if valid_out_k18 = '1' then
                out_count_k18 := out_count_k18 + 1;
                expected := K18_RT_BN_RELU_EXPECTED_FX(out_count_k18 - 1);
                got      := to_integer(y_bn_relu_fx_k18);
                check_output(18, out_count_k18, expected, got);
            end if;
            if valid_out_k19 = '1' then
                out_count_k19 := out_count_k19 + 1;
                expected := K19_RT_BN_RELU_EXPECTED_FX(out_count_k19 - 1);
                got      := to_integer(y_bn_relu_fx_k19);
                check_output(19, out_count_k19, expected, got);
            end if;
            if valid_out_k20 = '1' then
                out_count_k20 := out_count_k20 + 1;
                expected := K20_RT_BN_RELU_EXPECTED_FX(out_count_k20 - 1);
                got      := to_integer(y_bn_relu_fx_k20);
                check_output(20, out_count_k20, expected, got);
            end if;
            if valid_out_k21 = '1' then
                out_count_k21 := out_count_k21 + 1;
                expected := K21_RT_BN_RELU_EXPECTED_FX(out_count_k21 - 1);
                got      := to_integer(y_bn_relu_fx_k21);
                check_output(21, out_count_k21, expected, got);
            end if;
            if valid_out_k22 = '1' then
                out_count_k22 := out_count_k22 + 1;
                expected := K22_RT_BN_RELU_EXPECTED_FX(out_count_k22 - 1);
                got      := to_integer(y_bn_relu_fx_k22);
                check_output(22, out_count_k22, expected, got);
            end if;
            if valid_out_k23 = '1' then
                out_count_k23 := out_count_k23 + 1;
                expected := K23_RT_BN_RELU_EXPECTED_FX(out_count_k23 - 1);
                got      := to_integer(y_bn_relu_fx_k23);
                check_output(23, out_count_k23, expected, got);
            end if;
            if valid_out_k24 = '1' then
                out_count_k24 := out_count_k24 + 1;
                expected := K24_RT_BN_RELU_EXPECTED_FX(out_count_k24 - 1);
                got      := to_integer(y_bn_relu_fx_k24);
                check_output(24, out_count_k24, expected, got);
            end if;
            if valid_out_k25 = '1' then
                out_count_k25 := out_count_k25 + 1;
                expected := K25_RT_BN_RELU_EXPECTED_FX(out_count_k25 - 1);
                got      := to_integer(y_bn_relu_fx_k25);
                check_output(25, out_count_k25, expected, got);
            end if;
            if valid_out_k26 = '1' then
                out_count_k26 := out_count_k26 + 1;
                expected := K26_RT_BN_RELU_EXPECTED_FX(out_count_k26 - 1);
                got      := to_integer(y_bn_relu_fx_k26);
                check_output(26, out_count_k26, expected, got);
            end if;
            if valid_out_k27 = '1' then
                out_count_k27 := out_count_k27 + 1;
                expected := K27_RT_BN_RELU_EXPECTED_FX(out_count_k27 - 1);
                got      := to_integer(y_bn_relu_fx_k27);
                check_output(27, out_count_k27, expected, got);
            end if;
            if valid_out_k28 = '1' then
                out_count_k28 := out_count_k28 + 1;
                expected := K28_RT_BN_RELU_EXPECTED_FX(out_count_k28 - 1);
                got      := to_integer(y_bn_relu_fx_k28);
                check_output(28, out_count_k28, expected, got);
            end if;
            if valid_out_k29 = '1' then
                out_count_k29 := out_count_k29 + 1;
                expected := K29_RT_BN_RELU_EXPECTED_FX(out_count_k29 - 1);
                got      := to_integer(y_bn_relu_fx_k29);
                check_output(29, out_count_k29, expected, got);
            end if;
            if valid_out_k30 = '1' then
                out_count_k30 := out_count_k30 + 1;
                expected := K30_RT_BN_RELU_EXPECTED_FX(out_count_k30 - 1);
                got      := to_integer(y_bn_relu_fx_k30);
                check_output(30, out_count_k30, expected, got);
            end if;
            if valid_out_k31 = '1' then
                out_count_k31 := out_count_k31 + 1;
                expected := K31_RT_BN_RELU_EXPECTED_FX(out_count_k31 - 1);
                got      := to_integer(y_bn_relu_fx_k31);
                check_output(31, out_count_k31, expected, got);
            end if;
        end loop;

        -- ---- Structural checks: exactly N_POSITIONS outputs per kernel --
        assert out_count_k0 = N_POSITIONS
            report "FAIL: kernel 0 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k0)
            severity warning;
        if out_count_k0 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k1 = N_POSITIONS
            report "FAIL: kernel 1 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k1)
            severity warning;
        if out_count_k1 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k2 = N_POSITIONS
            report "FAIL: kernel 2 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k2)
            severity warning;
        if out_count_k2 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k3 = N_POSITIONS
            report "FAIL: kernel 3 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k3)
            severity warning;
        if out_count_k3 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k4 = N_POSITIONS
            report "FAIL: kernel 4 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k4)
            severity warning;
        if out_count_k4 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k5 = N_POSITIONS
            report "FAIL: kernel 5 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k5)
            severity warning;
        if out_count_k5 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k6 = N_POSITIONS
            report "FAIL: kernel 6 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k6)
            severity warning;
        if out_count_k6 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k7 = N_POSITIONS
            report "FAIL: kernel 7 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k7)
            severity warning;
        if out_count_k7 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k8 = N_POSITIONS
            report "FAIL: kernel 8 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k8)
            severity warning;
        if out_count_k8 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k9 = N_POSITIONS
            report "FAIL: kernel 9 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k9)
            severity warning;
        if out_count_k9 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k10 = N_POSITIONS
            report "FAIL: kernel 10 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k10)
            severity warning;
        if out_count_k10 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k11 = N_POSITIONS
            report "FAIL: kernel 11 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k11)
            severity warning;
        if out_count_k11 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k12 = N_POSITIONS
            report "FAIL: kernel 12 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k12)
            severity warning;
        if out_count_k12 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k13 = N_POSITIONS
            report "FAIL: kernel 13 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k13)
            severity warning;
        if out_count_k13 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k14 = N_POSITIONS
            report "FAIL: kernel 14 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k14)
            severity warning;
        if out_count_k14 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k15 = N_POSITIONS
            report "FAIL: kernel 15 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k15)
            severity warning;
        if out_count_k15 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k16 = N_POSITIONS
            report "FAIL: kernel 16 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k16)
            severity warning;
        if out_count_k16 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k17 = N_POSITIONS
            report "FAIL: kernel 17 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k17)
            severity warning;
        if out_count_k17 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k18 = N_POSITIONS
            report "FAIL: kernel 18 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k18)
            severity warning;
        if out_count_k18 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k19 = N_POSITIONS
            report "FAIL: kernel 19 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k19)
            severity warning;
        if out_count_k19 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k20 = N_POSITIONS
            report "FAIL: kernel 20 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k20)
            severity warning;
        if out_count_k20 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k21 = N_POSITIONS
            report "FAIL: kernel 21 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k21)
            severity warning;
        if out_count_k21 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k22 = N_POSITIONS
            report "FAIL: kernel 22 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k22)
            severity warning;
        if out_count_k22 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k23 = N_POSITIONS
            report "FAIL: kernel 23 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k23)
            severity warning;
        if out_count_k23 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k24 = N_POSITIONS
            report "FAIL: kernel 24 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k24)
            severity warning;
        if out_count_k24 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k25 = N_POSITIONS
            report "FAIL: kernel 25 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k25)
            severity warning;
        if out_count_k25 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k26 = N_POSITIONS
            report "FAIL: kernel 26 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k26)
            severity warning;
        if out_count_k26 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k27 = N_POSITIONS
            report "FAIL: kernel 27 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k27)
            severity warning;
        if out_count_k27 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k28 = N_POSITIONS
            report "FAIL: kernel 28 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k28)
            severity warning;
        if out_count_k28 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k29 = N_POSITIONS
            report "FAIL: kernel 29 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k29)
            severity warning;
        if out_count_k29 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k30 = N_POSITIONS
            report "FAIL: kernel 30 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k30)
            severity warning;
        if out_count_k30 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;
        assert out_count_k31 = N_POSITIONS
            report "FAIL: kernel 31 expected exactly " & integer'image(N_POSITIONS) &
                   " valid output positions, observed " & integer'image(out_count_k31)
            severity warning;
        if out_count_k31 /= N_POSITIONS then
            fail_count := fail_count + 1;
        end if;

        -- ---- Concise summary report (PASS/FAIL count + max abs diff) --
        report "=== REAL-TILE ALL-32-KERNEL Q.20 first-layer Conv-BN-ReLU verification summary ===" severity note;
        report "    Total kernels checked  = " & integer'image(NUM_KERNELS) severity note;
        report "    Total output values checked = " & integer'image(total_checked) severity note;
        report "    PASS count = " & integer'image(pass_count) &
               "   FAIL count = " & integer'image(fail_count) severity note;
        report "    Max absolute integer difference (Q.20 fixed-point) = " &
               integer'image(max_abs_diff) severity note;
        report "    Real tile: tile_16_42.tif, 6x6 sub-block, row_offset=125, col_offset=125" severity note;

        if fail_count = 0 then
            report "=== All tb_stream_conv3x3_3chan_all32_kernels_real_tile_bn_relu_q20 tests PASSED ===" &
                   "  (" & integer'image(pass_count) & " / " & integer'image(pass_count) &
                   " outputs match Python Q.20 fixed-point golden vectors on REAL UAVSAR tile data, "
                   & "all 32 output channels)"
                severity note;
        else
            report "=== " & integer'image(fail_count) & " CHECK(S) FAILED ===" severity failure;
        end if;
        report "    All-32-kernel first Conv-BN-ReLU stage (REAL TILE tile_16_42.tif), enc1.block.0/1 from" &
               " alea_tuned_filtered_strict_fp2_focaldice_adamw_20epochs_best.pt" severity note;
        report "    NOTE: simulation-only verification. NOT full FPGA U-Net, NOT board deployment," &
               " NOT full-image streaming." severity note;

        wait;
    end process stim;

end architecture sim;
